import { describe, expect, it } from "vitest";

import { AI_MODEL_ROUTING_POLICY_VERSION } from "../analysis/aiModelRoutingPolicy";
import {
  BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_ID,
  BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_REVISION,
  MAX_BROADCAST_TRANSCRIPT_QWEN_DURATION_MS,
} from "../analysis/broadcastTranscriptQwen";
import {
  BROADCAST_TRANSCRIPT_HEALTH_SERVICE_VERSION,
  BROADCAST_TRANSCRIPT_PRIMARY_MEDIA_TYPE,
  BROADCAST_TRANSCRIPT_PROVIDER_CONFIGURATION_VERSION,
  BROADCAST_TRANSCRIPT_ROUTE_MANIFEST_SCHEMA_VERSION,
  BROADCAST_TRANSCRIPT_TRANSPORT_VERSION,
  createBroadcastTranscriptRouteSelection,
  type BroadcastTranscriptRouteManifest,
} from "../analysis/broadcastTranscriptRouteManifest";
import {
  broadcastTranscriptProviderReceiptCheckpointModelRevision,
  createBroadcastTranscriptProviderReceiptCheckpoint,
  recordBroadcastTranscriptCaptionReceipt,
  serializeBroadcastTranscriptProviderReceiptCheckpoint,
} from "../analysis/broadcastTranscriptProviderReceiptCheckpoint";
import {
  createBroadcastTranscriptResolvedEvidenceCheckpoint,
  serializeBroadcastTranscriptResolvedEvidenceCheckpoint,
} from "../analysis/broadcastTranscriptResolvedEvidence";
import {
  createYouTubeCaptionTranscriptCellOutcomes,
} from "../analysis/youtubeCaptionTrack";
import {
  BROADCAST_CONTEXT_SESSION_SCHEMA_VERSION,
  type BroadcastContextSessionRecord,
} from "../storage/broadcastContextSessionStore";
import { inspectCurrentTranscriptCheckpoint } from "./analysisPipelineSuccess";
import {
  createCurrentProviderTranscriptSourceIdentityFence,
  transcriptOperationKey,
} from "./transcriptPhase";

const RUN_ID = "caption-ledger-run";
const INPUT_SIGNATURE = `sha256:${"a".repeat(64)}`;
const CONTENT_FINGERPRINT =
  `local-file-sampled-sha256-v1:${"b".repeat(64)}`;
const VIDEO_ID = "abcdefghijk";
const SOURCE_DURATION_MS = 180_000;
const PLAN = [
  { chunkId: "asr-0-1xg0", sourceStartMs: 0, sourceEndMs: 90_000 },
  {
    chunkId: "asr-1xg0-3uw0",
    sourceStartMs: 90_000,
    sourceEndMs: SOURCE_DURATION_MS,
  },
] as const;

async function captionSettledSession(): Promise<BroadcastContextSessionRecord> {
  const routeManifest: BroadcastTranscriptRouteManifest = {
    schemaVersion: BROADCAST_TRANSCRIPT_ROUTE_MANIFEST_SCHEMA_VERSION,
    serviceVersion: BROADCAST_TRANSCRIPT_HEALTH_SERVICE_VERSION,
    routingPolicyVersion: AI_MODEL_ROUTING_POLICY_VERSION,
    providerConfigurationVersion:
      BROADCAST_TRANSCRIPT_PROVIDER_CONFIGURATION_VERSION,
    transportVersion: BROADCAST_TRANSCRIPT_TRANSPORT_VERSION,
    transportMode: "free-r2",
    maximumChunkDurationMs: MAX_BROADCAST_TRANSCRIPT_QWEN_DURATION_MS,
    primaryMediaType: BROADCAST_TRANSCRIPT_PRIMARY_MEDIA_TYPE,
    provider: "qwen",
    modelId: BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_ID,
    modelRevision: BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_REVISION,
    effectiveFallback: { mode: "disabled" },
  };
  const route = await createBroadcastTranscriptRouteSelection(routeManifest);
  const captionTrack = {
    videoId: VIDEO_ID,
    languageCode: "ko",
    isAutoGenerated: true,
    events: [
      { startMs: 5_000, durationMs: 1_000, text: "첫 셀의 자막" },
      { startMs: 95_000, durationMs: 1_000, text: "둘째 셀의 자막" },
    ],
  } as const;
  const outcomes = createYouTubeCaptionTranscriptCellOutcomes(
    captionTrack,
    PLAN,
    SOURCE_DURATION_MS,
  );
  let provider = createBroadcastTranscriptProviderReceiptCheckpoint({
    sourceFingerprint: INPUT_SIGNATURE,
    sourceDurationMs: SOURCE_DURATION_MS,
    route,
    plannedCells: PLAN,
  });
  for (const outcome of outcomes) {
    provider = recordBroadcastTranscriptCaptionReceipt(
      provider,
      outcome.chunkId,
      captionTrack,
      outcome.chapter,
    );
  }
  const modelRevision =
    broadcastTranscriptProviderReceiptCheckpointModelRevision(provider);
  const transcriptSealOperationKey = transcriptOperationKey(
    RUN_ID,
    CONTENT_FINGERPRINT,
    "event-boost",
    0,
    await createCurrentProviderTranscriptSourceIdentityFence(null),
  );
  const evidence = createBroadcastTranscriptResolvedEvidenceCheckpoint({
    sourceFingerprint: INPUT_SIGNATURE,
    sourceDurationMs: SOURCE_DURATION_MS,
    transcriptInputSignature: transcriptSealOperationKey,
    modelRevision,
    plannedCells: PLAN,
  });
  return {
    kind: "broadcastContextSession",
    runId: RUN_ID,
    schemaVersion: BROADCAST_CONTEXT_SESSION_SCHEMA_VERSION,
    inputSignature: INPUT_SIGNATURE,
    sourceDurationMs: SOURCE_DURATION_MS,
    completeAudioCoverage: true,
    chapters: outcomes.map(({ chapter }, index) => ({
      ...chapter,
      chapterId: `transcript-${index + 1}`,
    })),
    gapChunkIds: [],
    fragmentGaps: [],
    transcriptEvidenceInputSignature:
      evidence.transcriptInputSignature,
    transcriptEvidenceCheckpointJson:
      serializeBroadcastTranscriptResolvedEvidenceCheckpoint(evidence),
    transcriptVisualInspectionCheckpointJson: null,
    transcriptProviderReceiptInputSignature:
      provider.routeManifestFingerprint,
    transcriptProviderReceiptCheckpointJson:
      serializeBroadcastTranscriptProviderReceiptCheckpoint(provider),
    modelRevision,
    sourceCastRosterId: null,
    transcriptSealOperationKey,
    participantGroundingInputSignature: null,
    participantGroundingPlanFingerprint: null,
    participantGroundingCheckpointJson: null,
    contextInputSignature: null,
    contextInputCheckpointJson: null,
    contextPhaseLedgerJson: null,
    contextResultJson: null,
    refinementTranscriptInputSignature: null,
    refinementTranscriptCheckpointJson: null,
    refinementEvidenceLedgerJson: null,
    refinementInputSignature: null,
    refinementCandidatesJson: null,
    recordedAt: "2026-07-29T00:00:00.000Z",
  };
}

describe("current transcript caption settlement", () => {
  it("accepts captions only through exact evidence and provider ledgers", async () => {
    const session = await captionSettledSession();

    await expect(
      inspectCurrentTranscriptCheckpoint({
        session,
        sourceContentFingerprint: CONTENT_FINGERPRINT,
        expectedCaptionVideoId: VIDEO_ID,
      }),
    ).resolves.toBe(true);
  });

  it("rejects null ledgers, changed chapter content, and another video id", async () => {
    const session = await captionSettledSession();
    const withoutLedgers: BroadcastContextSessionRecord = {
      ...session,
      transcriptEvidenceInputSignature: null,
      transcriptEvidenceCheckpointJson: null,
      transcriptProviderReceiptInputSignature: null,
      transcriptProviderReceiptCheckpointJson: null,
    };
    const changedChapter: BroadcastContextSessionRecord = {
      ...session,
      chapters: session.chapters.map((chapter, index) =>
        index === 0
          ? { ...chapter, summaryKo: "저장 후 바뀐 자막" }
          : chapter,
      ),
    };

    await expect(
      inspectCurrentTranscriptCheckpoint({
        session: withoutLedgers,
        sourceContentFingerprint: CONTENT_FINGERPRINT,
        expectedCaptionVideoId: VIDEO_ID,
      }),
    ).resolves.toBe(false);
    await expect(
      inspectCurrentTranscriptCheckpoint({
        session: changedChapter,
        sourceContentFingerprint: CONTENT_FINGERPRINT,
        expectedCaptionVideoId: VIDEO_ID,
      }),
    ).resolves.toBe(false);
    await expect(
      inspectCurrentTranscriptCheckpoint({
        session,
        sourceContentFingerprint: CONTENT_FINGERPRINT,
        expectedCaptionVideoId: "zyxwvutsrqp",
      }),
    ).resolves.toBe(false);
  });
});
