import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";

import {
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
} from "../../src/analysis/channelPreanalysisBundle.ts";
import { normalizeChannelVideoTitle } from "../../src/analysis/channelPreanalysisCatalog.ts";
import { AI_BROADCAST_CONTEXT_ROUTING_REVISION } from "../../src/analysis/aiModelRoutingPolicy.ts";
import { BROADCAST_CONTEXT_SCHEMA_VERSION } from "../../src/analysis/broadcastContextProtocol.ts";
import { AMORETTO_CHANNEL_PREANALYSIS_SOURCE } from "../../src/analysis/channelPreanalysisSources.ts";
import {
  canonicalChannelPreanalysisVisualFingerprintArtifactId,
  canonicalChannelPreanalysisVisualFingerprintStorageKey,
  createChannelPreanalysisVisualFingerprint,
  serializeChannelPreanalysisVisualFingerprint,
} from "../../src/analysis/channelPreanalysisVisualFingerprint.ts";
import {
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_ALGORITHM,
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SCHEMA_VERSION,
  channelPreanalysisVisualCoveragePlannedSampleCount,
} from "../../src/analysis/channelPreanalysisVisualCoverage.ts";
import {
  loadChannelPreanalysisReviewInput,
  prepareChannelPreanalysisReviewVideo,
  selectChannelPreanalysisReviewQueue,
} from "./channel-preanalysis-review-job.mjs";

const VIDEO_ID = "KzAW3yow80Q";
const DURATION_MS = 120_000;
const CREATED_AT = "2026-08-02T01:00:00.000Z";
const sha256 = (bytes) =>
  `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
const serialize = (value) => `${JSON.stringify(value, null, 2)}\n`;

function visualAnalysis() {
  const plannedSampleCount =
    channelPreanalysisVisualCoveragePlannedSampleCount(DURATION_MS);
  return {
    receipt: {
      schemaVersion: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SCHEMA_VERSION,
      algorithm: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_ALGORITHM,
      status: "complete",
      sourceDurationMs: DURATION_MS,
      sampleIntervalMs: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
      plannedSampleCount,
      analyzedSampleCount: plannedSampleCount,
      firstSampleTimestampMs: 0,
      lastSampleTimestampMs:
        (plannedSampleCount - 1) *
        CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
      coveredThroughMs: DURATION_MS,
      gaps: [],
      sourceFingerprintArtifactId:
        canonicalChannelPreanalysisVisualFingerprintArtifactId(VIDEO_ID),
      sourceFingerprintDigest: null,
      visualSeedCount: 0,
      visualSeedTimestampsMs: [],
    },
    seeds: [],
  };
}

const chapters = [
  {
    chapterId: "chapter-1",
    startMs: 0,
    endMs: DURATION_MS,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "스트리머가 음식에 관한 경험과 반응을 이야기합니다.",
  },
];

async function contextBundle() {
  return createChannelPreanalysisBundle({
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: "음식 토크 다시보기",
    durationMs: DURATION_MS,
    publishedAt: "2026-08-01T00:00:00.000Z",
    catalogRevision: 1,
    state: "context-ready",
    captionTrack: {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: false,
      events: [
        { startMs: 40_000, durationMs: 3_000, text: "드디어 성공했어요." },
      ],
    },
    chapters,
    broadcastContext: {
      schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
      broadcastSummaryKo: "여러 음식 경험과 예상 밖 반응이 이어지는 방송입니다.",
      hostStreamerProfile: null,
      recurringThemesKo: ["음식 토크"],
      annotations: [],
      semanticChaptersSupported: true,
      semanticChapters: [
        {
          semanticChapterId: "semantic-1",
          startChapterId: "chapter-1",
          endChapterId: "chapter-1",
          startMs: 0,
          endMs: DURATION_MS,
          titleKo: "음식 토크",
          summaryKo: "음식에 대한 경험과 반응을 설명합니다.",
          kind: "story-progress",
          salience: "primary",
          relatedCandidateIds: [],
          uncertaintiesKo: [],
        },
      ],
      discoveredLeadsSupported: true,
      discoveredLeads: [],
      coverage: {
        status: "complete",
        coveredMs: DURATION_MS,
        coverageRatio: 1,
        gaps: [],
        partialChapterIds: [],
      },
    },
    contextProvenance: {
      generatedAt: CREATED_AT,
      modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
      contextReceipt: {
        contractVersion: "3.0.0",
        routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
        modelId: "qwen3.7-plus",
        modelRevision: "review-job-test-v1",
      },
      evidenceScope: "youtube-caption-transcript-only",
      localVisualVerificationRequired: true,
    },
    provenance: createDefaultChannelPreanalysisProvenance(VIDEO_ID, CREATED_AT),
  });
}

async function fixture(t) {
  const root = await mkdtemp(join(tmpdir(), "exclipper-review-job-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const catalogDir = join(root, AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId);
  await mkdir(catalogDir, { recursive: true });
  const bundle = await contextBundle();
  const bytes = Buffer.from(serialize(bundle), "utf8");
  const storageKey = `${AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId}/videos/${VIDEO_ID}.v1.json`;
  const artifact = {
    artifactId: `youtube-caption-bundle:${VIDEO_ID}:v1`,
    videoId: VIDEO_ID,
    kind: "transcript",
    revision: 1,
    storageKey,
    contentDigest: sha256(bytes),
    byteLength: bytes.byteLength,
    createdAt: CREATED_AT,
  };
  const fingerprint = createChannelPreanalysisVisualFingerprint({
    videoId: VIDEO_ID,
    sourceDurationMs: DURATION_MS,
    createdAt: CREATED_AT,
    anchors: Array.from({ length: 8 }, (_, index) => ({
      timestampMs: 10_000 + index * 14_000,
      dHash64: (index + 1).toString(16).padStart(16, "0"),
      blockHash64: (index + 17).toString(16).padStart(16, "0"),
      meanLuma: 30 + index,
      edgeEnergy: 20 + index,
    })),
  });
  const fingerprintBytes = Buffer.from(
    serializeChannelPreanalysisVisualFingerprint(fingerprint),
    "utf8",
  );
  const fingerprintArtifact = {
    artifactId: canonicalChannelPreanalysisVisualFingerprintArtifactId(VIDEO_ID),
    videoId: VIDEO_ID,
    kind: "fingerprint",
    revision: 1,
    storageKey: canonicalChannelPreanalysisVisualFingerprintStorageKey(
      VIDEO_ID,
      AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId,
    ),
    contentDigest: sha256(fingerprintBytes),
    byteLength: fingerprintBytes.byteLength,
    createdAt: CREATED_AT,
  };
  const video = {
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: bundle.title,
    normalizedTitle: normalizeChannelVideoTitle(bundle.title),
    durationMs: DURATION_MS,
    publishedAt: bundle.publishedAt,
    updatedAt: bundle.publishedAt,
    watchUrl: `https://www.youtube.com/watch?v=${VIDEO_ID}`,
    state: "context-ready",
    revision: 1,
    artifactIds: [artifact.artifactId, fingerprintArtifact.artifactId],
    registeredLocalSampledFingerprints: [],
    retry: null,
  };
  const manifest = {
    schemaVersion: 1,
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    channelHandle: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelHandle,
    revision: 1,
    generatedAt: CREATED_AT,
    videos: [video],
    artifacts: [artifact, fingerprintArtifact],
  };
  const path = join(catalogDir, "videos", `${VIDEO_ID}.v1.json`);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, bytes);
  const fingerprintPath = join(
    catalogDir,
    "videos",
    `${VIDEO_ID}.visual-fingerprint.v1.json`,
  );
  await writeFile(fingerprintPath, fingerprintBytes);
  await writeFile(join(catalogDir, "catalog.json"), serialize(manifest));
  return { root, catalogDir, bundle, manifest, video };
}

test("review queue gives one new upload and one due recovery a fair bounded slot", () => {
  const video = (videoId, state, publishedAt, retry = null) => ({
    videoId,
    state,
    publishedAt,
    retry,
  });
  const due = {
    stage: "review",
    lastSuccessfulState: "context-ready",
    nextAttemptAt: "2026-08-01T00:00:00.000Z",
  };
  const manifest = {
    videos: [
      video("AAAAAAAAAAA", "context-ready", "2026-08-02T01:00:00.000Z"),
      video("BBBBBBBBBBB", "context-ready", "2026-08-02T02:00:00.000Z"),
      video("CCCCCCCCCCC", "retryable", "2026-07-30T00:00:00.000Z", due),
    ],
  };
  assert.deepEqual(
    selectChannelPreanalysisReviewQueue(manifest, {
      nowMs: Date.parse("2026-08-02T03:00:00.000Z"),
      maxVideos: 2,
    }).map(({ videoId }) => videoId),
    ["BBBBBBBBBBB", "CCCCCCCCCCC"],
  );
});

test("an exact manual review bypasses only the retry time backoff", () => {
  const futureRetry = {
    stage: "review",
    lastSuccessfulState: "context-ready",
    nextAttemptAt: "2026-08-03T00:00:00.000Z",
  };
  const exact = {
    videoId: VIDEO_ID,
    state: "retryable",
    publishedAt: "2026-08-01T00:00:00.000Z",
    retry: futureRetry,
  };
  const manifest = { videos: [exact] };
  const nowMs = Date.parse("2026-08-02T03:00:00.000Z");

  assert.deepEqual(
    selectChannelPreanalysisReviewQueue(manifest, { nowMs, videoId: VIDEO_ID }),
    [exact],
  );
  assert.deepEqual(
    selectChannelPreanalysisReviewQueue(manifest, { nowMs }),
    [],
  );
});

test("automatic review excludes videos older than seven days while exact review remains available", () => {
  const old = {
    videoId: VIDEO_ID,
    state: "context-ready",
    publishedAt: "2026-07-25T02:59:59.999Z",
    retry: null,
  };
  const nowMs = Date.parse("2026-08-01T03:00:00.000Z");

  assert.deepEqual(
    selectChannelPreanalysisReviewQueue({ videos: [old] }, { nowMs }),
    [],
  );
  assert.deepEqual(
    selectChannelPreanalysisReviewQueue(
      { videos: [old] },
      { nowMs, videoId: VIDEO_ID },
    ),
    [old],
  );
});

test("an exact manual review selects an already closed video for current-pipeline refresh", () => {
  const exact = {
    videoId: VIDEO_ID,
    state: "review-ready",
    publishedAt: "2026-08-01T00:00:00.000Z",
    retry: null,
  };

  assert.deepEqual(
    selectChannelPreanalysisReviewQueue(
      { videos: [exact] },
      { nowMs: Date.parse("2026-08-02T03:00:00.000Z"), videoId: VIDEO_ID },
    ),
    [exact],
  );
  assert.deepEqual(
    selectChannelPreanalysisReviewQueue(
      { videos: [exact] },
      { nowMs: Date.parse("2026-08-02T03:00:00.000Z") },
    ),
    [],
  );
});

test("an exact manual review cannot bypass an incomplete upstream state", () => {
  const video = {
    videoId: VIDEO_ID,
    state: "retryable",
    publishedAt: "2026-08-01T00:00:00.000Z",
    retry: {
      stage: "context",
      lastSuccessfulState: "transcript-ready",
      nextAttemptAt: "2026-08-03T00:00:00.000Z",
    },
  };

  assert.deepEqual(
    selectChannelPreanalysisReviewQueue(
      { videos: [video] },
      { nowMs: Date.parse("2026-08-02T03:00:00.000Z"), videoId: VIDEO_ID },
    ),
    [],
  );
});

test("loads the exact durable context artifact and rejects a changed byte", async (t) => {
  const data = await fixture(t);
  const loaded = await loadChannelPreanalysisReviewInput({
    catalogDir: data.catalogDir,
    source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
    video: data.video,
  });
  assert.equal(loaded.contextBundle.videoId, VIDEO_ID);
  assert.equal(loaded.visualFingerprint.videoId, VIDEO_ID);
  await writeFile(join(data.catalogDir, "videos", `${VIDEO_ID}.v1.json`), "changed");
  await assert.rejects(
    loadChannelPreanalysisReviewInput({
      catalogDir: data.catalogDir,
      source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
      video: data.video,
    }),
    (error) => error.code === "CONTEXT_ARTIFACT_DIGEST_MISMATCH",
  );
});

test("one scheduled video reaches the publisher only after download, full features, media and review closure", async (t) => {
  const data = await fixture(t);
  const workRoot = join(data.root, "work");
  const downloadedDirectory = join(workRoot, "downloaded");
  const sourcePath = join(downloadedDirectory, "source.mkv");
  const calls = [];
  const completedCheckpoint = {
    checkpointKey: "completed-checkpoint",
    candidateId: "completed-candidate",
    status: "analyzed",
  };
  const retryableCheckpoint = {
    checkpointKey: "retryable-checkpoint",
    candidateId: "retryable-candidate",
    status: "retryable",
    attemptOrdinal: 1,
    retryGrantId: "scheduled-semantic-1-restart",
  };
  const checkpointStore = {
    load: async () => {
      calls.push("checkpoint-load");
      return {
        previousCandidateResults: [completedCheckpoint],
        retryableDiagnostics: [retryableCheckpoint],
      };
    },
    onCandidateCheckpoint: async () => {},
    finalizeAfterPublisherSuccess: async () => calls.push("checkpoint-finalize"),
  };
  const reviewBundle = { exact: "verified-review" };
  const publication = await prepareChannelPreanalysisReviewVideo(
    {
      catalogDir: data.catalogDir,
      source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
      video: data.video,
      createCandidateAnalyzer: async () => {
        calls.push("candidate-analyzer");
        return async () => assert.fail("stub runner owns analysis");
      },
      ytDlpPath: "yt-dlp-test",
      ytDlpEnvironment: { PATH: "bounded" },
      workRoot,
    },
    {
      nowIso: () => "2026-08-02T04:00:00.000Z",
      createCheckpointStore: () => checkpointStore,
      downloadMedia: async (_input, options) => {
        calls.push("download");
        assert.equal(options.ytDlpPath, "yt-dlp-test");
        await mkdir(downloadedDirectory, { recursive: true });
        await writeFile(sourcePath, "media");
        return { sourcePath, workingDirectory: downloadedDirectory };
      },
      probeMedia: async () => {
        calls.push("probe");
        return { durationMs: DURATION_MS };
      },
      extractAudioFeatures: async () => {
        calls.push("audio-features");
        return { sourceDurationMs: DURATION_MS, coverageComplete: true, windows: [] };
      },
      extractVisualCoverage: async (_path, _durationMs, options) => {
        calls.push("visual-coverage");
        const result = visualAnalysis();
        result.receipt.sourceFingerprintDigest =
          options.sourceFingerprintArtifact.contentDigest;
        return result;
      },
      createMediaExtractor: () => {
        calls.push("media-extractor");
        return async () => ({ frames: [], audio: null });
      },
      runReview: async (input) => {
        calls.push("review-runner");
        assert.deepEqual(input.previousCandidateResults, [
          completedCheckpoint,
          retryableCheckpoint,
        ]);
        assert.equal(input.participantGrounding.status, "sealed");
        return {
          status: "complete",
          reviewBundle,
          retryCandidateIds: [],
        };
      },
      publishReview: async (
        _input,
        { prepareReview, forceRefresh, requiredPipelineRevision },
      ) => {
        calls.push("publisher");
        assert.equal(forceRefresh, false);
        assert.equal(
          requiredPipelineRevision,
          "scheduled-review-ready-v8",
        );
        const prepared = await prepareReview({ artifactRevision: 2 });
        assert.equal(prepared, reviewBundle);
        return { state: "review-ready", reviewBundle, video: { revision: 2 } };
      },
    },
  );

  assert.equal(publication.state, "review-ready");
  assert.deepEqual(calls, [
    "publisher",
    "download",
    "probe",
    "audio-features",
    "visual-coverage",
    "checkpoint-load",
    "media-extractor",
    "candidate-analyzer",
    "review-runner",
    "checkpoint-finalize",
  ]);
  assert.equal(await stat(downloadedDirectory).catch(() => null), null);
});

test("an orphan publication reconstructs and finalizes its exact checkpoint store", async (t) => {
  const data = await fixture(t);
  const calls = [];
  const publication = await prepareChannelPreanalysisReviewVideo(
    {
      catalogDir: data.catalogDir,
      source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
      video: data.video,
      createCandidateAnalyzer: async () =>
        assert.fail("orphan recovery must not create an analyzer"),
      workRoot: join(data.root, "orphan-work"),
    },
    {
      createCheckpointStore: ({ runIdentity }) => {
        calls.push(["checkpoint-store", runIdentity]);
        return {
          load: async () => assert.fail("orphan recovery must not load candidates"),
          onCandidateCheckpoint: async () => {},
          finalizeAfterPublisherSuccess: async (value) => {
            calls.push(["checkpoint-finalize", value.video.revision]);
          },
        };
      },
      downloadMedia: async () => assert.fail("orphan recovery must not download media"),
      publishReview: async (_input, options) => {
        assert.equal(options.forceRefresh, false);
        assert.equal(options.requiredPipelineRevision, "scheduled-review-ready-v8");
        return {
          state: "review-ready",
          reviewBundle: { artifactRevision: 2 },
          video: { videoId: VIDEO_ID, state: "review-ready", revision: 2 },
        };
      },
    },
  );

  assert.equal(publication.state, "review-ready");
  assert.equal(calls.length, 2);
  assert.equal(calls[0][0], "checkpoint-store");
  assert.equal(calls[0][1].artifactRevision, 2);
  assert.equal(calls[0][1].pipelineRevision, "scheduled-review-ready-v8");
  assert.deepEqual(calls[1], ["checkpoint-finalize", 2]);
});

test("parallel media scans both stop before a failed job removes their shared download", async (t) => {
  const data = await fixture(t);
  const workRoot = join(data.root, "parallel-work");
  const downloadedDirectory = join(workRoot, "downloaded");
  const sourcePath = join(downloadedDirectory, "source.mkv");
  const audioError = new Error("audio scan failed");
  let releaseVisual;
  let markVisualStarted;
  const visualRelease = new Promise((resolve) => {
    releaseVisual = resolve;
  });
  const visualStarted = new Promise((resolve) => {
    markVisualStarted = resolve;
  });

  const pending = prepareChannelPreanalysisReviewVideo(
    {
      catalogDir: data.catalogDir,
      source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
      video: data.video,
      createCandidateAnalyzer: async () =>
        assert.fail("A failed media scan must not create the candidate analyzer."),
      workRoot,
    },
    {
      downloadMedia: async () => {
        await mkdir(downloadedDirectory, { recursive: true });
        await writeFile(sourcePath, "media");
        return { sourcePath, workingDirectory: downloadedDirectory };
      },
      probeMedia: async () => ({ durationMs: DURATION_MS }),
      extractAudioFeatures: async () => {
        throw audioError;
      },
      extractVisualCoverage: async () => {
        markVisualStarted();
        await visualRelease;
        return visualAnalysis();
      },
      publishReview: async (_input, { prepareReview }) =>
        prepareReview({ artifactRevision: 2 }),
    },
  );

  await visualStarted;
  assert.notEqual(await stat(downloadedDirectory).catch(() => null), null);
  releaseVisual();
  await assert.rejects(pending, (error) => error === audioError);
  assert.equal(await stat(downloadedDirectory).catch(() => null), null);
});

test("real runner, publisher and checkpoint finalizer close over their distinct context digests", async (t) => {
  const data = await fixture(t);
  const workRoot = join(data.root, "work");
  const downloadedDirectory = join(workRoot, "downloaded");
  const sourcePath = join(downloadedDirectory, "source.mkv");

  const publication = await prepareChannelPreanalysisReviewVideo(
    {
      catalogDir: data.catalogDir,
      source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
      video: data.video,
      createCandidateAnalyzer: async ({ participantGrounding }) => {
        assert.equal(participantGrounding.status, "sealed");
        return async () => assert.fail("A verified-empty run has no candidate to analyze.");
      },
      workRoot,
    },
    {
      nowIso: () => "2026-08-02T05:00:00.000Z",
      downloadMedia: async () => {
        await mkdir(downloadedDirectory, { recursive: true });
        await writeFile(sourcePath, "media");
        return { sourcePath, workingDirectory: downloadedDirectory };
      },
      probeMedia: async () => ({ durationMs: DURATION_MS }),
      extractAudioFeatures: async () => ({
        sourceDurationMs: DURATION_MS,
        plannedWindowCount: 0,
        analyzedWindowCount: 0,
        coverageComplete: true,
        windows: [],
      }),
      extractVisualCoverage: async (_path, _durationMs, options) => {
        const result = visualAnalysis();
        result.receipt.sourceFingerprintDigest =
          options.sourceFingerprintArtifact.contentDigest;
        return result;
      },
      createMediaExtractor: () => async () =>
        assert.fail("A verified-empty run has no candidate media to extract."),
    },
  );

  assert.equal(publication.state, "review-ready");
  assert.equal(publication.reviewBundle.certificate.outcome, "verified-empty");
  assert.notEqual(
    publication.reviewBundle.broadcastContextDigest,
    data.manifest.artifacts[0].contentDigest,
  );
  assert.equal(publication.video.artifactIds.length, 3);
  assert.equal(await stat(downloadedDirectory).catch(() => null), null);
});
