import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";

import {
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
} from "../../src/analysis/channelPreanalysisBundle.ts";
import { createBroadcastParticipantGrounding } from "../../src/analysis/broadcastParticipantGrounding.ts";
import { AI_BROADCAST_CONTEXT_ROUTING_REVISION } from "../../src/analysis/aiModelRoutingPolicy.ts";
import {
  candidatePassBContextFingerprint,
  createCandidatePassBVerificationReceipt,
} from "../../src/analysis/candidateFinalVerification.ts";
import {
  CANDIDATE_PASS_B_DISPATCH_INTENT_SCHEMA_VERSION,
  CANDIDATE_PASS_B_FRAME_EXTRACTION_REVISION,
  CANDIDATE_PASS_B_MEDIA_RECEIPT_SCHEMA_VERSION,
  CANDIDATE_PASS_B_QWEN_MODEL_ID,
  CANDIDATE_PASS_B_QWEN_MODEL_REVISION,
  CANDIDATE_PASS_B_ROUTING_MODEL_REVISION,
  CANDIDATE_PASS_B_SAMPLE_RATE_HZ,
  CANDIDATE_PASS_B_SETTLEMENT_SCHEMA_VERSION,
} from "../../src/analysis/candidatePassBWorkerProtocol.ts";
import { BROADCAST_CONTEXT_SCHEMA_VERSION } from "../../src/analysis/broadcastContextProtocol.ts";
import { AMORETTO_CHANNEL_PREANALYSIS_SOURCE } from "../../src/analysis/channelPreanalysisSources.ts";
import { verifyChannelPreanalysisReviewBundleIntegrity } from "../../src/analysis/channelPreanalysisReviewBundle.ts";
import {
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_ALGORITHM,
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SCHEMA_VERSION,
  channelPreanalysisVisualCoveragePlannedSampleCount,
} from "../../src/analysis/channelPreanalysisVisualCoverage.ts";
import { runChannelPreanalysisReview } from "./channel-preanalysis-review-runner.mjs";

const VIDEO_ID = "KzAW3yow80Q";
const DURATION_MS = 120_000;
const CREATED_AT = "2026-08-02T04:00:00.000Z";
const digest = (character) => `sha256:${character.repeat(64)}`;
const chapters = [
  {
    chapterId: "chapter-1",
    startMs: 0,
    endMs: 60_000,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "방송을 시작하고 오늘의 이야기를 준비합니다.",
  },
  {
    chapterId: "chapter-2",
    startMs: 60_000,
    endMs: DURATION_MS,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "조용한 도전을 성공한 뒤 스트리머가 기뻐합니다.",
  },
];

function context(discoveredLeads = [
  {
    leadId: "quiet-success",
    startChapterId: "chapter-2",
    endChapterId: "chapter-2",
    startMs: 60_000,
    endMs: 105_000,
    category: "quiet-achievement",
    confidence: 0.92,
    eventSummaryKo: "여러 번 시도한 목표를 조용히 성공했습니다.",
    whyThisMomentKo: "앞선 실패가 누적되어 성공의 의미가 큽니다.",
    evidenceCueKo: "성공 직후 안도하며 웃는 대사가 이어집니다.",
    uncertaintiesKo: [],
  },
]) {
  return {
    schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
    broadcastSummaryKo: "방송 전반에서 여러 번 도전한 뒤 마지막에 목표를 달성합니다.",
    hostStreamerProfile: null,
    recurringThemesKo: ["반복 도전과 성공"],
    annotations: [],
    semanticChaptersSupported: true,
    semanticChapters: [
      {
        semanticChapterId: "semantic-1",
        startChapterId: "chapter-1",
        endChapterId: "chapter-2",
        startMs: 0,
        endMs: DURATION_MS,
        titleKo: "도전과 성공",
        summaryKo: "준비부터 성공까지 이어지는 방송 흐름입니다.",
        kind: "story-progress",
        salience: "primary",
        relatedCandidateIds: [],
        uncertaintiesKo: [],
      },
    ],
    discoveredLeadsSupported: true,
    discoveredLeads,
    coverage: {
      status: "complete",
      coveredMs: DURATION_MS,
      coverageRatio: 1,
      gaps: [],
      partialChapterIds: [],
    },
  };
}

async function contextReadyBundle(discoveredLeads) {
  return createChannelPreanalysisBundle({
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: "테스트 방송",
    durationMs: DURATION_MS,
    publishedAt: "2026-08-02T00:00:00.000Z",
    catalogRevision: 1,
    state: "context-ready",
    captionTrack: {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: false,
      events: [
        { startMs: 50_000, durationMs: 5_000, text: "이번에도 다시 해 볼게요." },
        { startMs: 72_000, durationMs: 4_000, text: "됐다. 드디어 성공했어." },
        { startMs: 96_000, durationMs: 4_000, text: "정말 오래 걸렸네요." },
      ],
    },
    chapters,
    broadcastContext: context(discoveredLeads),
    contextProvenance: {
      generatedAt: "2026-08-02T03:00:00.000Z",
      modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
      contextReceipt: {
        contractVersion: "2.0.0",
        routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
        modelId: "qwen3.7-plus",
        modelRevision: "scheduled-context-test-v1",
      },
      evidenceScope: "youtube-caption-transcript-only",
      localVisualVerificationRequired: true,
    },
    provenance: createDefaultChannelPreanalysisProvenance(
      VIDEO_ID,
      "2026-08-02T02:00:00.000Z",
    ),
  });
}

function audioFeatures() {
  const windows = Array.from({ length: 120 }, (_, index) => ({
    startMs: index * 1_000,
    endMs: (index + 1) * 1_000,
    rms: 0,
    peak: 0,
    zeroCrossingRate: 0,
    speechBandEnergyRatio: 0,
  }));
  return {
    sourceDurationMs: DURATION_MS,
    plannedWindowCount: windows.length,
    analyzedWindowCount: windows.length,
    coverageComplete: true,
    windows,
  };
}

function participantGrounding() {
  return createBroadcastParticipantGrounding({
    sourceDurationMs: DURATION_MS,
    castRosterId: null,
    chapters,
  });
}

function visualCoverage(visualSeedCount = 0) {
  const plannedSampleCount =
    channelPreanalysisVisualCoveragePlannedSampleCount(DURATION_MS);
  return {
    schemaVersion: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SCHEMA_VERSION,
    algorithm: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_ALGORITHM,
    status: "complete",
    sourceDurationMs: DURATION_MS,
    sampleIntervalMs: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
    plannedSampleCount,
    analyzedSampleCount: plannedSampleCount,
    firstSampleTimestampMs: 0,
    lastSampleTimestampMs:
      (plannedSampleCount - 1) *
      CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
    coveredThroughMs: DURATION_MS,
    gaps: [],
    sourceFingerprintArtifactId:
      `youtube-storyboard-visual-fingerprint:${VIDEO_ID}:v1`,
    sourceFingerprintDigest: digest("8"),
    visualSeedCount,
    visualSeedTimestampsMs: visualSeedCount === 0 ? [] : [60_000],
  };
}

function quietVisualSeed() {
  return {
    seedId: "visual-change-1-60000",
    startMs: 37_500,
    endMs: 82_500,
    focusMs: 60_000,
    score: 0.81,
    eventKo: "조용한 화면 사건",
    whyKo: "음량 변화 없이 화면에서 중요한 상태 변화가 나타났습니다.",
    evidenceKo: "분산 화면 변화 점수 0.310",
  };
}

const JPEG_BYTES = Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0, 0, 0xff, 0xd9]);
const JPEG_DIGEST = `sha256:${createHash("sha256").update(JPEG_BYTES).digest("hex")}`;

function completeMedia() {
  return {
    frames: [5_000, 15_000, 25_000, 35_000].map((timestampMs) => ({
      timestampMs,
      mimeType: "image/jpeg",
      byteLength: JPEG_BYTES.length,
      contentDigest: JPEG_DIGEST,
      extractionRevision: CANDIDATE_PASS_B_FRAME_EXTRACTION_REVISION,
      dataBase64: JPEG_BYTES.toString("base64"),
    })),
    audio: { rawAudio: Buffer.from([1, 2, 3]) },
  };
}

function analyzer(overrideInsight = {}) {
  return async ({ candidate, context: candidateContext, frames }) => {
    assert.equal(frames.length, 4);
    const mediaFrames = frames.map((frame) => ({
      timestampMs: frame.timestampMs,
      mimeType: frame.mimeType,
      byteLength: frame.byteLength,
      contentDigest: frame.contentDigest,
      extractionRevision: frame.extractionRevision,
    }));
    const dispatch = {
      schemaVersion: CANDIDATE_PASS_B_DISPATCH_INTENT_SCHEMA_VERSION,
      operationId: `candidate-pass-b.${candidate.candidateId}`,
      analysisRunId: "scheduled-review-test",
      candidateId: candidate.candidateId,
      sourceFingerprint: "scheduled-source-test",
      sourceStartMs: candidate.startMs,
      sourceEndMs: candidate.endMs,
      contextFingerprint: candidatePassBContextFingerprint(candidateContext),
      outputLanguage: "ko",
      castRosterId: null,
      routingModelRevision: CANDIDATE_PASS_B_ROUTING_MODEL_REVISION,
      attemptOrdinal: 0,
      retryGrantId: null,
      transportMode: "paid-direct",
      mediaReceipt: {
        schemaVersion: CANDIDATE_PASS_B_MEDIA_RECEIPT_SCHEMA_VERSION,
        frameExtractionRevision: CANDIDATE_PASS_B_FRAME_EXTRACTION_REVISION,
        frames: mediaFrames,
        audio: {
          kind: "audible-audio",
          wavByteLength: 32_044,
          wavContentDigest: digest("5"),
          sampleRateHz: CANDIDATE_PASS_B_SAMPLE_RATE_HZ,
          sampleCount: 16_000,
        },
        providerPayloadDigest: digest("6"),
      },
    };
    const settlement = {
      schemaVersion: CANDIDATE_PASS_B_SETTLEMENT_SCHEMA_VERSION,
      status: "completed",
      operationId: dispatch.operationId,
      providerPayloadDigest: dispatch.mediaReceipt.providerPayloadDigest,
      outputLanguage: "ko",
      castRosterId: null,
      responseDigest: digest("7"),
      providerModelId: CANDIDATE_PASS_B_QWEN_MODEL_ID,
      providerModelRevision: CANDIDATE_PASS_B_QWEN_MODEL_REVISION,
    };
    const receipt = createCandidatePassBVerificationReceipt(
      candidateContext,
      25_000,
      {
        candidateId: candidate.candidateId,
        sourceStartMs: candidate.startMs,
        sourceEndMs: candidate.endMs,
        routingModelRevision: CANDIDATE_PASS_B_ROUTING_MODEL_REVISION,
        refinementEvidenceProjectionFingerprint: null,
        outputLanguage: "ko",
        castRosterId: null,
      },
      dispatch,
      settlement,
    );
    assert.ok(receipt);
    return {
      insight: {
        eventSummaryKo: "오랜 도전 끝에 목표를 달성했습니다.",
        reactionSummaryKo: "스트리머가 안도하며 기뻐합니다.",
        whyGoodClipKo: "앞선 실패와 성공의 보상이 한 구간에 담겼습니다.",
        uncertaintiesKo: [],
        participantPresence: "present-unidentified",
        participantSummaryKo: "화면에 진행자가 있지만 이름 근거는 없습니다.",
        identifiedParticipants: [],
        clipDecision: "recommend",
        contextConsistency: "consistent",
        programMaterial: "streamer-event",
        ...overrideInsight,
      },
      model: {
        id: CANDIDATE_PASS_B_QWEN_MODEL_ID,
        revision: CANDIDATE_PASS_B_QWEN_MODEL_REVISION,
      },
      verificationReceipt: receipt,
    };
  };
}

function runnerInput(bundle, overrides = {}) {
  return {
    sourceId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId,
    artifactRevision: 1,
    createdAt: CREATED_AT,
    pipelineRevision: "scheduled-review-test-v1",
    bundle,
    audioFeatures: audioFeatures(),
    visualCoverage: visualCoverage(),
    visualCandidateSeeds: [],
    participantGrounding: participantGrounding(),
    extractCandidateMedia: async () => completeMedia(),
    analyzeCandidate: analyzer(),
    candidateConcurrency: 2,
    ...overrides,
  };
}

test("semantic and audio inputs produce one self-contained verified review artifact", async () => {
  const result = await runChannelPreanalysisReview(runnerInput(await contextReadyBundle()));
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.candidates.length, 1);
  assert.equal(result.reviewBundle.certificate.outcome, "review-ready");
  assert.equal(result.reviewBundle.candidates[0].frames.length, 4);
  assert.equal(JSON.stringify(result.reviewBundle).includes("rawAudio"), false);
  assert.equal(result.reviewBundle.participantGrounding.resolutionStatus, "media-reviewed");
  assert.deepEqual(
    result.reviewBundle.participantGrounding.adapterReceipts
      .slice(1)
      .map(({ status, inputCount, processedCount }) => ({
        status,
        inputCount,
        processedCount,
      })),
    [
      { status: "completed", inputCount: 1, processedCount: 1 },
      { status: "completed", inputCount: 1, processedCount: 1 },
    ],
  );
  assert.ok(
    result.reviewBundle.participantGrounding.evidence.some(
      ({ kind }) => kind === "visible-participant-unidentified",
    ),
  );
  assert.ok(
    result.reviewBundle.participantGrounding.evidence.some(
      ({ kind }) => kind === "speaker-unidentified",
    ),
  );
  await verifyChannelPreanalysisReviewBundleIntegrity(result.reviewBundle);
});

test("missing visual coverage fails closed before verified-empty publication", async () => {
  await assert.rejects(
    runChannelPreanalysisReview(
      runnerInput(await contextReadyBundle([]), {
        visualCoverage: undefined,
      }),
    ),
    (error) => error.code === "VISUAL_COVERAGE_INCOMPLETE",
  );
});

test("a source with complete static visual coverage and no other lead is verified-empty", async () => {
  let mediaCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle([]), {
      extractCandidateMedia: async () => {
        mediaCalls += 1;
        return completeMedia();
      },
      analyzeCandidate: async () => assert.fail("AI must not run without candidates"),
    }),
  );
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "verified-empty");
  assert.deepEqual(result.reviewBundle.candidates, []);
  assert.equal(result.reviewBundle.participantGrounding.resolutionStatus, "media-reviewed");
  assert.ok(
    result.reviewBundle.participantGrounding.adapterReceipts
      .slice(1)
      .every(({ status, inputCount }) => status === "completed" && inputCount === 0),
  );
  assert.equal(mediaCalls, 0);
});

test("a quiet visual event enters four-frame AI verification without an audio or semantic lead", async () => {
  let aiCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle([]), {
      visualCoverage: visualCoverage(1),
      visualCandidateSeeds: [quietVisualSeed()],
      analyzeCandidate: async (input) => {
        aiCalls += 1;
        assert.deepEqual(input.candidate.sourceKinds, ["visual"]);
        assert.equal(input.frames.length, 4);
        return analyzer()(input);
      },
    }),
  );
  assert.equal(aiCalls, 1);
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "review-ready");
  assert.equal(result.reviewBundle.visualCoverage.visualSeedCount, 1);
});

test("three frames stop that candidate before AI and preserve a retry checkpoint", async () => {
  let aiCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle(), {
      extractCandidateMedia: async () => ({
        ...completeMedia(),
        frames: completeMedia().frames.slice(0, 3),
      }),
      analyzeCandidate: async () => {
        aiCalls += 1;
        return analyzer()();
      },
    }),
  );
  assert.equal(result.status, "incomplete");
  assert.equal(result.reviewBundle, null);
  assert.equal(result.candidateResults[0].status, "retryable");
  assert.equal(result.candidateResults[0].errorCode, "FRAME_BUNDLE_INCOMPLETE");
  assert.equal(aiCalls, 0);
});

test("AI-confirmed music is a terminal exclusion and can yield verified-empty", async () => {
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle(), {
      analyzeCandidate: analyzer({
        clipDecision: "reject",
        programMaterial: "music-or-intermission",
      }),
    }),
  );
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "verified-empty");
  assert.equal(result.candidateResults[0].status, "analyzed");
});

test("completed per-candidate checkpoints skip media extraction and AI on resume", async () => {
  const bundle = await contextReadyBundle();
  const first = await runChannelPreanalysisReview(runnerInput(bundle));
  let calls = 0;
  const resumed = await runChannelPreanalysisReview(
    runnerInput(bundle, {
      previousCandidateResults: first.candidateResults,
      extractCandidateMedia: async () => {
        calls += 1;
        return completeMedia();
      },
      analyzeCandidate: async () => {
        calls += 1;
        return null;
      },
    }),
  );
  assert.equal(resumed.status, "complete");
  assert.equal(calls, 0);
  assert.deepEqual(resumed.reviewBundle, first.reviewBundle);
});
