import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";

import {
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
} from "../../src/analysis/channelPreanalysisBundle.ts";
import {
  normalizeChannelVideoTitle,
} from "../../src/analysis/channelPreanalysisCatalog.ts";
import { parseChannelPreanalysisManifest } from "../../src/analysis/channelPreanalysisClient.ts";
import { createBroadcastParticipantGrounding } from "../../src/analysis/broadcastParticipantGrounding.ts";
import { AI_BROADCAST_CONTEXT_ROUTING_REVISION } from "../../src/analysis/aiModelRoutingPolicy.ts";
import { BROADCAST_CONTEXT_SCHEMA_VERSION } from "../../src/analysis/broadcastContextProtocol.ts";
import {
  CHANNEL_PREANALYSIS_PARTICIPANT_PROVENANCE_SCHEMA_VERSION,
  CHANNEL_PREANALYSIS_REVIEW_BUNDLE_SCHEMA_VERSION,
  CHANNEL_PREANALYSIS_REVIEW_CERTIFICATE_SCHEMA_VERSION,
  channelPreanalysisReviewBundleArtifactId,
  channelPreanalysisReviewBundleStorageKey,
  createChannelPreanalysisReviewContentDigests,
  parseChannelPreanalysisReviewBundle,
  validateChannelPreanalysisReviewBundle,
  verifyChannelPreanalysisReviewBundleIntegrity,
} from "../../src/analysis/channelPreanalysisReviewBundle.ts";
import { AMORETTO_CHANNEL_PREANALYSIS_SOURCE } from "../../src/analysis/channelPreanalysisSources.ts";
import {
  canonicalChannelPreanalysisVisualFingerprintArtifactId,
  canonicalChannelPreanalysisVisualFingerprintStorageKey,
  createChannelPreanalysisVisualFingerprint,
  serializeChannelPreanalysisVisualFingerprint,
} from "../../src/analysis/channelPreanalysisVisualFingerprint.ts";
import { createChannelPreanalysisVisualCoverageReceipt } from "../../src/analysis/channelPreanalysisVisualCoverage.ts";
import { publishChannelPreanalysisReview } from "./channel-preanalysis-review-publisher.mjs";
import { verifyPersistedChannelCatalogSnapshot } from "../sync-amoretto-preanalysis.mjs";

const VIDEO_ID = "KzAW3yow80Q";
const DURATION_MS = 120_000;
const PUBLISHED_AT = "2026-08-01T12:00:00.000Z";
const CONTEXT_AT = "2026-08-02T01:00:00.000Z";
const REVIEW_AT = "2026-08-02T02:00:00.000Z";
const COMMIT_AT = "2026-08-02T03:00:00.000Z";
const TITLE = "음식 토크 다시보기";

const sha256 = (bytes) =>
  `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
const serialize = (value) => `${JSON.stringify(value, null, 2)}\n`;
const VISUAL_FINGERPRINT_TEXT =
  serializeChannelPreanalysisVisualFingerprint(
    createChannelPreanalysisVisualFingerprint({
      videoId: VIDEO_ID,
      sourceDurationMs: DURATION_MS,
      createdAt: CONTEXT_AT,
      anchors: Array.from({ length: 8 }, (_, index) => ({
        timestampMs: 10_000 + index * 14_000,
        dHash64: (index + 1).toString(16).padStart(16, "0"),
        blockHash64: (index + 17).toString(16).padStart(16, "0"),
        meanLuma: 30 + index,
        edgeEnergy: 20 + index,
      })),
    }),
  );

const chapters = [
  {
    chapterId: "chapter-1",
    startMs: 0,
    endMs: 60_000,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "방송을 시작하고 오늘 이야기할 음식 주제를 소개합니다.",
  },
  {
    chapterId: "chapter-2",
    startMs: 60_000,
    endMs: DURATION_MS,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "음식 경험을 이야기하며 방송을 차분하게 마무리합니다.",
  },
];

function broadcastContext() {
  return {
    schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
    broadcastSummaryKo:
      "스트리머가 여러 음식 경험을 순서대로 이야기하고 자신의 취향을 설명한 방송입니다.",
    hostStreamerProfile: null,
    recurringThemesKo: ["음식 경험", "취향 토크"],
    annotations: [],
    semanticChaptersSupported: true,
    semanticChapters: [
      {
        semanticChapterId: "semantic-1",
        startChapterId: "chapter-1",
        endChapterId: "chapter-2",
        startMs: 0,
        endMs: DURATION_MS,
        titleKo: "음식 취향 토크",
        summaryKo: "음식 이름을 맞히고 경험과 취향을 이어서 이야기합니다.",
        kind: "story-progress",
        salience: "primary",
        relatedCandidateIds: [],
        uncertaintiesKo: [],
      },
    ],
    discoveredLeadsSupported: true,
    discoveredLeads: [],
    coverage: {
      status: "complete",
      coveredMs: DURATION_MS,
      coverageRatio: 1,
      gaps: [],
      partialChapterIds: [],
    },
  };
}

async function createContextBundle() {
  return createChannelPreanalysisBundle({
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: TITLE,
    durationMs: DURATION_MS,
    publishedAt: PUBLISHED_AT,
    catalogRevision: 1,
    state: "context-ready",
    captionTrack: {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: false,
      events: [
        { startMs: 4_000, durationMs: 3_000, text: "오늘은 음식 이야기를 해볼게요." },
        { startMs: 64_000, durationMs: 4_000, text: "이 음식은 생각보다 맛있었어요." },
      ],
    },
    chapters,
    broadcastContext: broadcastContext(),
    contextProvenance: {
      generatedAt: CONTEXT_AT,
      modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
      contextReceipt: {
        contractVersion: "2.0.0",
        routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
        modelId: "qwen3.7-plus",
        modelRevision: "publisher-test-v1",
      },
      evidenceScope: "youtube-caption-transcript-only",
      localVisualVerificationRequired: true,
    },
    provenance: createDefaultChannelPreanalysisProvenance(VIDEO_ID, CONTEXT_AT),
  });
}

async function verifiedEmptyReview(
  contextBundle,
  revision,
  pipelineRevision = "scheduled-review-test-v1",
) {
  const source = {
    sourceId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId,
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
  };
  const participantGrounding = createBroadcastParticipantGrounding({
    sourceDurationMs: DURATION_MS,
    castRosterId: null,
    chapters,
  }, {
    visualIdentity: {
      receipt: { adapter: "visual-identity", revision: "test-visual-v1", status: "completed", inputCount: 0, processedCount: 0, unavailableReason: null },
      evidence: [],
    },
    voiceIdentity: {
      receipt: { adapter: "voice-identity", revision: "test-voice-v1", status: "completed", inputCount: 0, processedCount: 0, unavailableReason: null },
      evidence: [],
    },
  });
  const visualCoverage = createChannelPreanalysisVisualCoverageReceipt({
    sourceDurationMs: DURATION_MS,
    videoId: VIDEO_ID,
    sourceFingerprintDigest: sha256(
      Buffer.from(VISUAL_FINGERPRINT_TEXT, "utf8"),
    ),
    visualSeedTimestampsMs: [],
  });
  const digests = await createChannelPreanalysisReviewContentDigests({
    source,
    broadcastContext: contextBundle.broadcastContext,
    visualCoverage,
    participantGrounding,
    candidates: [],
  });
  const bundle = validateChannelPreanalysisReviewBundle({
    schemaVersion: CHANNEL_PREANALYSIS_REVIEW_BUNDLE_SCHEMA_VERSION,
    artifactId: channelPreanalysisReviewBundleArtifactId(VIDEO_ID, revision),
    artifactRevision: revision,
    createdAt: REVIEW_AT,
    source,
    sourceDurationMs: DURATION_MS,
    transcriptDigest: contextBundle.transcriptDigest,
    broadcastContext: contextBundle.broadcastContext,
    broadcastContextDigest: digests.broadcastContextDigest,
    visualCoverage,
    participantGrounding,
    participantGroundingProvenance: {
      schemaVersion: CHANNEL_PREANALYSIS_PARTICIPANT_PROVENANCE_SCHEMA_VERSION,
      checkpointDigest: digests.participantGroundingDigest,
      generatedAt: REVIEW_AT,
      pipelineRevision,
    },
    candidates: [],
    certificate: {
      schemaVersion: CHANNEL_PREANALYSIS_REVIEW_CERTIFICATE_SCHEMA_VERSION,
      pipelineRevision,
      outcome: "verified-empty",
      sourceIdentityDigest: digests.sourceIdentityDigest,
      transcriptDigest: contextBundle.transcriptDigest,
      broadcastContextDigest: digests.broadcastContextDigest,
      participantGroundingDigest: digests.participantGroundingDigest,
      visualCoverageDigest: digests.visualCoverageDigest,
      candidateSetDigest: digests.candidateSetDigest,
      finalCandidateIds: [],
    },
  });
  await verifyChannelPreanalysisReviewBundleIntegrity(bundle);
  return bundle;
}

function localArtifactPath(catalogDir, storageKey) {
  const prefix = `${AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId}/`;
  assert.equal(storageKey.startsWith(prefix), true);
  return join(catalogDir, storageKey.slice(prefix.length));
}

async function writeStorage(catalogDir, storageKey, bytes) {
  const path = localArtifactPath(catalogDir, storageKey);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, bytes);
  return path;
}

async function createFixture(t) {
  const catalogDir = await mkdtemp(join(tmpdir(), "exclipper-review-publisher-"));
  t.after(() => rm(catalogDir, { force: true, recursive: true }));
  const contextBundle = await createContextBundle();
  const contextText = serialize(contextBundle);
  const contextBytes = Buffer.from(contextText, "utf8");
  const contextStorageKey =
    `${AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId}/videos/${VIDEO_ID}.v1.json`;
  const contextArtifact = {
    artifactId: `youtube-caption-bundle:${VIDEO_ID}:v1`,
    videoId: VIDEO_ID,
    kind: "transcript",
    revision: 1,
    storageKey: contextStorageKey,
    contentDigest: sha256(contextBytes),
    byteLength: contextBytes.byteLength,
    createdAt: CONTEXT_AT,
  };
  const fingerprintText = VISUAL_FINGERPRINT_TEXT;
  const fingerprintBytes = Buffer.from(fingerprintText, "utf8");
  const fingerprintStorageKey =
    canonicalChannelPreanalysisVisualFingerprintStorageKey(
      VIDEO_ID,
      AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId,
    );
  const fingerprintArtifact = {
    artifactId: canonicalChannelPreanalysisVisualFingerprintArtifactId(VIDEO_ID),
    videoId: VIDEO_ID,
    kind: "fingerprint",
    revision: 1,
    storageKey: fingerprintStorageKey,
    contentDigest: sha256(fingerprintBytes),
    byteLength: fingerprintBytes.byteLength,
    createdAt: CONTEXT_AT,
  };
  const video = {
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: TITLE,
    normalizedTitle: normalizeChannelVideoTitle(TITLE),
    durationMs: DURATION_MS,
    publishedAt: PUBLISHED_AT,
    updatedAt: PUBLISHED_AT,
    watchUrl: `https://www.youtube.com/watch?v=${VIDEO_ID}`,
    state: "context-ready",
    revision: 1,
    artifactIds: [contextArtifact.artifactId, fingerprintArtifact.artifactId],
    registeredLocalSampledFingerprints: [],
    retry: null,
  };
  const manifest = {
    schemaVersion: 1,
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    channelHandle: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelHandle,
    revision: 1,
    generatedAt: CONTEXT_AT,
    videos: [video],
    artifacts: [contextArtifact, fingerprintArtifact],
  };
  parseChannelPreanalysisManifest(serialize(manifest),
    AMORETTO_CHANNEL_PREANALYSIS_SOURCE);
  const contextPath = await writeStorage(
    catalogDir,
    contextStorageKey,
    contextBytes,
  );
  const fingerprintPath = await writeStorage(
    catalogDir,
    fingerprintStorageKey,
    fingerprintBytes,
  );
  await writeFile(join(catalogDir, "catalog.json"), serialize(manifest));
  return {
    catalogDir,
    contextBundle,
    contextBytes,
    contextPath,
    fingerprintBytes,
    fingerprintPath,
    manifest,
    video,
  };
}

function publishInput(fixture) {
  return {
    catalogDir: fixture.catalogDir,
    source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
    video: fixture.video,
    contextBundle: fixture.contextBundle,
  };
}

async function assertInputsRemain(fixture) {
  assert.deepEqual(await readFile(fixture.contextPath), fixture.contextBytes);
  assert.deepEqual(await readFile(fixture.fingerprintPath), fixture.fingerprintBytes);
}

test("recovers a verified crash-before-manifest orphan without rerunning review AI", async (t) => {
  const fixture = await createFixture(t);
  const orphan = await verifiedEmptyReview(fixture.contextBundle, 2);
  const reviewStorageKey = channelPreanalysisReviewBundleStorageKey(
    AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId,
    VIDEO_ID,
    2,
  );
  await writeStorage(fixture.catalogDir, reviewStorageKey, serialize(orphan));
  let prepareCalls = 0;

  const result = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: async () => {
        prepareCalls += 1;
        throw new Error("orphan recovery must not call the provider");
      },
      nowIso: () => COMMIT_AT,
    },
  );

  assert.equal(result.state, "review-ready");
  assert.equal(result.recovered, true);
  assert.equal(result.reviewBundle.certificate.outcome, "verified-empty");
  assert.equal(prepareCalls, 0);
  const manifest = parseChannelPreanalysisManifest(
    await readFile(join(fixture.catalogDir, "catalog.json"), "utf8"),
    AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
  );
  assert.equal(manifest.videos[0].revision, 2);
  assert.equal(manifest.artifacts.filter(({ kind }) => kind === "review").length, 1);
  await assertInputsRemain(fixture);
});

test("preserves the context checkpoint and source artifacts when review preparation fails", async (t) => {
  const fixture = await createFixture(t);
  let prepareCalls = 0;
  const providerError = Object.assign(new Error("temporary provider outage"), {
    code: "PROVIDER_UNAVAILABLE",
  });

  const result = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: async () => {
        prepareCalls += 1;
        throw providerError;
      },
      nowIso: () => COMMIT_AT,
    },
  );

  assert.equal(prepareCalls, 1);
  assert.equal(result.state, "retryable");
  assert.equal(result.errorCode, "PROVIDER_UNAVAILABLE");
  assert.deepEqual(result.video.artifactIds, fixture.video.artifactIds);
  assert.deepEqual(result.video.retry, {
    stage: "review",
    lastSuccessfulState: "context-ready",
    attemptCount: 1,
    nextAttemptAt: "2026-08-02T06:00:00.000Z",
    errorCode: "PROVIDER_UNAVAILABLE",
  });
  assert.equal(result.manifest.artifacts.some(({ kind }) => kind === "review"), false);
  await assertInputsRemain(fixture);
});

test("a review retry reuses the attempted revision so candidate checkpoints remain resumable", async (t) => {
  const fixture = await createFixture(t);
  const failed = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: async () => {
        throw Object.assign(new Error("temporary failure"), {
          code: "CANDIDATE_ANALYSIS_FAILED",
        });
      },
      nowIso: () => COMMIT_AT,
    },
  );
  assert.equal(failed.state, "retryable");
  assert.equal(failed.video.revision, 2);

  let resumedRevision = null;
  const resumed = await publishChannelPreanalysisReview(
    {
      catalogDir: fixture.catalogDir,
      source: AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
      video: failed.video,
      contextBundle: fixture.contextBundle,
    },
    {
      prepareReview: async ({ artifactRevision }) => {
        resumedRevision = artifactRevision;
        return verifiedEmptyReview(fixture.contextBundle, artifactRevision);
      },
      nowIso: () => "2026-08-02T07:00:00.000Z",
    },
  );
  assert.equal(resumedRevision, 2);
  assert.equal(resumed.state, "review-ready");
  assert.equal(resumed.video.revision, 2);
});

test("a normal publication rejects a bundle from another pipeline revision", async (t) => {
  const fixture = await createFixture(t);
  const result = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      requiredPipelineRevision: "scheduled-review-test-v2",
      prepareReview: ({ artifactRevision }) =>
        verifiedEmptyReview(fixture.contextBundle, artifactRevision),
      nowIso: () => COMMIT_AT,
    },
  );

  assert.equal(result.state, "retryable");
  assert.equal(result.errorCode, "REVIEW_PIPELINE_REVISION_MISMATCH");
  assert.equal(result.video.state, "retryable");
  assert.equal(result.manifest.artifacts.some(({ kind }) => kind === "review"), false);
});

test("publishes one verified-empty bundle only after immutable readback", async (t) => {
  const fixture = await createFixture(t);
  let prepareCalls = 0;

  const result = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: async ({ artifactRevision, contextBundle, source, video }) => {
        prepareCalls += 1;
        assert.equal(artifactRevision, 2);
        assert.equal(contextBundle.transcriptDigest, fixture.contextBundle.transcriptDigest);
        assert.equal(source.sourceId, AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId);
        assert.equal(video.videoId, VIDEO_ID);
        return verifiedEmptyReview(fixture.contextBundle, artifactRevision);
      },
      nowIso: () => COMMIT_AT,
    },
  );

  assert.equal(prepareCalls, 1);
  assert.equal(result.state, "review-ready");
  assert.equal(result.recovered, false);
  assert.equal(result.video.revision, 2);
  assert.equal(result.reviewBundle.certificate.outcome, "verified-empty");
  const reviewPath = localArtifactPath(
    fixture.catalogDir,
    result.artifact.storageKey,
  );
  const reviewText = await readFile(reviewPath, "utf8");
  const persisted = parseChannelPreanalysisReviewBundle(reviewText);
  await verifyChannelPreanalysisReviewBundleIntegrity(persisted);
  assert.equal(sha256(Buffer.from(reviewText, "utf8")), result.artifact.contentDigest);
  assert.equal(Buffer.byteLength(reviewText), result.artifact.byteLength);
  await assertInputsRemain(fixture);
});

test("an explicit refresh atomically replaces a closed review with the next revision", async (t) => {
  const fixture = await createFixture(t);
  const first = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: ({ artifactRevision }) =>
        verifiedEmptyReview(fixture.contextBundle, artifactRevision),
      nowIso: () => COMMIT_AT,
    },
  );
  let refreshedRevision = null;

  const refreshed = await publishChannelPreanalysisReview(
    {
      ...publishInput(fixture),
      video: first.video,
    },
    {
      forceRefresh: true,
      requiredPipelineRevision: "scheduled-review-test-v2",
      prepareReview: ({ artifactRevision }) => {
        refreshedRevision = artifactRevision;
        return verifiedEmptyReview(
          fixture.contextBundle,
          artifactRevision,
          "scheduled-review-test-v2",
        );
      },
      nowIso: () => "2026-08-02T04:00:00.000Z",
    },
  );

  assert.equal(refreshedRevision, 3);
  assert.equal(refreshed.state, "review-ready");
  assert.equal(refreshed.video.revision, 3);
  assert.equal(refreshed.reviewBundle.artifactRevision, 3);
  assert.equal(
    refreshed.manifest.artifacts.filter(({ kind }) => kind === "review").length,
    1,
  );
  const currentReviewArtifact = refreshed.manifest.artifacts.find(
    ({ kind }) => kind === "review",
  );
  assert.equal(
    currentReviewArtifact?.artifactId,
    channelPreanalysisReviewBundleArtifactId(VIDEO_ID, 3),
  );
  assert.equal(
    refreshed.video.artifactIds.includes(currentReviewArtifact.artifactId),
    true,
  );
  await assertInputsRemain(fixture);
});

test("an explicit refresh reuses a closed review from the required pipeline", async (t) => {
  const fixture = await createFixture(t);
  const first = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: ({ artifactRevision }) =>
        verifiedEmptyReview(fixture.contextBundle, artifactRevision),
      nowIso: () => COMMIT_AT,
    },
  );
  let prepareCalls = 0;

  const repeated = await publishChannelPreanalysisReview(
    {
      ...publishInput(fixture),
      video: first.video,
    },
    {
      forceRefresh: true,
      requiredPipelineRevision: "scheduled-review-test-v1",
      prepareReview: async () => {
        prepareCalls += 1;
        throw new Error("a current review must not be paid for twice");
      },
      nowIso: () => "2026-08-02T04:00:00.000Z",
    },
  );

  assert.equal(repeated.state, "review-ready");
  assert.equal(repeated.recovered, true);
  assert.equal(repeated.video.revision, 2);
  assert.equal(prepareCalls, 0);
});

test("a failed explicit refresh preserves the previously published review closure", async (t) => {
  const fixture = await createFixture(t);
  const first = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: ({ artifactRevision }) =>
        verifiedEmptyReview(fixture.contextBundle, artifactRevision),
      nowIso: () => COMMIT_AT,
    },
  );

  const failed = await publishChannelPreanalysisReview(
    {
      ...publishInput(fixture),
      video: first.video,
    },
    {
      forceRefresh: true,
      requiredPipelineRevision: "scheduled-review-test-v2",
      prepareReview: async () => {
        throw Object.assign(new Error("temporary provider outage"), {
          code: "PROVIDER_UNAVAILABLE",
        });
      },
      nowIso: () => "2026-08-02T04:00:00.000Z",
    },
  );

  assert.equal(failed.state, "retryable");
  assert.equal(failed.errorCode, "PROVIDER_UNAVAILABLE");
  assert.equal(failed.preservedReview, true);
  assert.equal(failed.video.state, "review-ready");
  assert.equal(failed.video.revision, 2);
  const persisted = parseChannelPreanalysisManifest(
    await readFile(join(fixture.catalogDir, "catalog.json"), "utf8"),
    AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
  );
  assert.equal(persisted.videos[0].state, "review-ready");
  assert.equal(persisted.videos[0].revision, 2);
  assert.equal(persisted.artifacts.filter(({ kind }) => kind === "review").length, 1);
  await assertInputsRemain(fixture);
});

test("the catalog snapshot verifier accepts the full review closure and rejects changed review bytes", async (t) => {
  const fixture = await createFixture(t);
  const reviewInputManifest = {
    ...fixture.manifest,
    videos: fixture.manifest.videos.map((video) => ({
      ...video,
      artifactIds: video.artifactIds.filter((artifactId) =>
        artifactId.startsWith("youtube-caption-bundle:") ||
        artifactId.startsWith("youtube-storyboard-visual-fingerprint:"),
      ),
    })),
    artifacts: fixture.manifest.artifacts.filter(
      ({ kind }) => kind === "transcript" || kind === "fingerprint",
    ),
  };
  await writeFile(
    join(fixture.catalogDir, "catalog.json"),
    serialize(reviewInputManifest),
  );
  const result = await publishChannelPreanalysisReview(
    publishInput(fixture),
    {
      prepareReview: ({ artifactRevision }) =>
        verifiedEmptyReview(fixture.contextBundle, artifactRevision),
      nowIso: () => COMMIT_AT,
    },
  );
  const verified = await verifyPersistedChannelCatalogSnapshot(
    fixture.catalogDir,
    AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
  );
  assert.equal(verified.videos[0].state, "review-ready");

  const reviewPath = localArtifactPath(
    fixture.catalogDir,
    result.artifact.storageKey,
  );
  const changed = await readFile(reviewPath);
  changed[changed.byteLength - 2] ^= 1;
  await writeFile(reviewPath, changed);
  await assert.rejects(
    verifyPersistedChannelCatalogSnapshot(
      fixture.catalogDir,
      AMORETTO_CHANNEL_PREANALYSIS_SOURCE,
    ),
    (error) =>
      error.code === "ARTIFACT_DIGEST_MISMATCH" ||
      error.code === "REVIEW_ARTIFACT_INVALID",
  );
});
