import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";

import {
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
} from "../../src/analysis/channelPreanalysisBundle.ts";
import { createBroadcastParticipantGrounding } from "../../src/analysis/broadcastParticipantGrounding.ts";
import { AI_BROADCAST_CONTEXT_ROUTING_REVISION } from "../../src/analysis/aiModelRoutingPolicy.ts";
import {
  candidatePassBContextFingerprint,
  createCandidatePassBVerificationReceipt,
} from "../../src/analysis/candidateFinalVerification.ts";
import {
  CANDIDATE_PASS_B_DISPATCH_INTENT_SCHEMA_VERSION,
  CANDIDATE_PASS_B_FRAME_EXTRACTION_REVISION,
  CANDIDATE_PASS_B_MEDIA_RECEIPT_SCHEMA_VERSION,
  CANDIDATE_PASS_B_QWEN_MODEL_ID,
  CANDIDATE_PASS_B_QWEN_MODEL_REVISION,
  CANDIDATE_PASS_B_ROUTING_MODEL_REVISION,
  CANDIDATE_PASS_B_SAMPLE_RATE_HZ,
  CANDIDATE_PASS_B_SETTLEMENT_SCHEMA_VERSION,
} from "../../src/analysis/candidatePassBWorkerProtocol.ts";
import { BROADCAST_CONTEXT_SCHEMA_VERSION } from "../../src/analysis/broadcastContextProtocol.ts";
import { AMORETTO_CHANNEL_PREANALYSIS_SOURCE } from "../../src/analysis/channelPreanalysisSources.ts";
import { verifyChannelPreanalysisReviewBundleIntegrity } from "../../src/analysis/channelPreanalysisReviewBundle.ts";
import {
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_ALGORITHM,
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
  CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SCHEMA_VERSION,
  channelPreanalysisVisualCoveragePlannedSampleCount,
} from "../../src/analysis/channelPreanalysisVisualCoverage.ts";
import { runChannelPreanalysisReview } from "./channel-preanalysis-review-runner.mjs";

const VIDEO_ID = "KzAW3yow80Q";
const DURATION_MS = 120_000;
const CREATED_AT = "2026-08-02T04:00:00.000Z";
const digest = (character) => `sha256:${character.repeat(64)}`;
const chapters = [
  {
    chapterId: "chapter-1",
    startMs: 0,
    endMs: 60_000,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "방송을 시작하고 오늘의 이야기를 준비합니다.",
  },
  {
    chapterId: "chapter-2",
    startMs: 60_000,
    endMs: DURATION_MS,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "조용한 도전을 성공한 뒤 스트리머가 기뻐합니다.",
  },
];

function context(discoveredLeads = [
  {
    leadId: "quiet-success",
    startChapterId: "chapter-2",
    endChapterId: "chapter-2",
    startMs: 60_000,
    endMs: 105_000,
    category: "quiet-achievement",
    confidence: 0.92,
    eventSummaryKo: "여러 번 시도한 목표를 조용히 성공했습니다.",
    whyThisMomentKo: "앞선 실패가 누적되어 성공의 의미가 큽니다.",
    evidenceCueKo: "성공 직후 안도하며 웃는 대사가 이어집니다.",
    uncertaintiesKo: [],
  },
], annotations = []) {
  return {
    schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
    broadcastSummaryKo: "방송 전반에서 여러 번 도전한 뒤 마지막에 목표를 달성합니다.",
    hostStreamerProfile: null,
    recurringThemesKo: ["반복 도전과 성공"],
    annotations,
    semanticChaptersSupported: true,
    semanticChapters: [
      {
        semanticChapterId: "semantic-1",
        startChapterId: "chapter-1",
        endChapterId: "chapter-2",
        startMs: 0,
        endMs: DURATION_MS,
        titleKo: "도전과 성공",
        summaryKo: "준비부터 성공까지 이어지는 방송 흐름입니다.",
        kind: "story-progress",
        salience: "primary",
        relatedCandidateIds: [],
        uncertaintiesKo: [],
      },
    ],
    discoveredLeadsSupported: true,
    discoveredLeads,
    coverage: {
      status: "complete",
      coveredMs: DURATION_MS,
      coverageRatio: 1,
      gaps: [],
      partialChapterIds: [],
    },
  };
}

async function contextReadyBundle(discoveredLeads, annotations) {
  return createChannelPreanalysisBundle({
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: "테스트 방송",
    durationMs: DURATION_MS,
    publishedAt: "2026-08-02T00:00:00.000Z",
    catalogRevision: 1,
    state: "context-ready",
    captionTrack: {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: false,
      events: [
        { startMs: 50_000, durationMs: 5_000, text: "이번에도 다시 해 볼게요." },
        { startMs: 72_000, durationMs: 4_000, text: "됐다. 드디어 성공했어." },
        { startMs: 96_000, durationMs: 4_000, text: "정말 오래 걸렸네요." },
      ],
    },
    chapters,
    broadcastContext: context(discoveredLeads, annotations),
    contextProvenance: {
      generatedAt: "2026-08-02T03:00:00.000Z",
      modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
      contextReceipt: {
        contractVersion: "2.0.0",
        routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
        modelId: "qwen3.7-plus",
        modelRevision: "scheduled-context-test-v1",
      },
      evidenceScope: "youtube-caption-transcript-only",
      localVisualVerificationRequired: true,
    },
    provenance: createDefaultChannelPreanalysisProvenance(
      VIDEO_ID,
      "2026-08-02T02:00:00.000Z",
    ),
  });
}

function audioFeatures() {
  const windows = Array.from({ length: 120 }, (_, index) => ({
    startMs: index * 1_000,
    endMs: (index + 1) * 1_000,
    rms: 0,
    peak: 0,
    zeroCrossingRate: 0,
    speechBandEnergyRatio: 0,
  }));
  return {
    sourceDurationMs: DURATION_MS,
    plannedWindowCount: windows.length,
    analyzedWindowCount: windows.length,
    coverageComplete: true,
    windows,
  };
}

function participantGrounding() {
  return createBroadcastParticipantGrounding({
    sourceDurationMs: DURATION_MS,
    castRosterId: null,
    chapters,
  });
}

function visualCoverage(visualSeedCount = 0) {
  const plannedSampleCount =
    channelPreanalysisVisualCoveragePlannedSampleCount(DURATION_MS);
  return {
    schemaVersion: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SCHEMA_VERSION,
    algorithm: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_ALGORITHM,
    status: "complete",
    sourceDurationMs: DURATION_MS,
    sampleIntervalMs: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
    plannedSampleCount,
    analyzedSampleCount: plannedSampleCount,
    firstSampleTimestampMs: 0,
    lastSampleTimestampMs:
      (plannedSampleCount - 1) *
      CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
    coveredThroughMs: DURATION_MS,
    gaps: [],
    sourceFingerprintArtifactId:
      `youtube-storyboard-visual-fingerprint:${VIDEO_ID}:v1`,
    sourceFingerprintDigest: digest("8"),
    visualSeedCount,
    visualSeedTimestampsMs: visualSeedCount === 0 ? [] : [60_000],
  };
}

function quietVisualSeed() {
  return {
    seedId: "visual-change-1-60000",
    startMs: 37_500,
    endMs: 82_500,
    focusMs: 60_000,
    score: 0.81,
    eventKo: "조용한 화면 사건",
    whyKo: "음량 변화 없이 화면에서 중요한 상태 변화가 나타났습니다.",
    evidenceKo: "분산 화면 변화 점수 0.310",
  };
}

const JPEG_BYTES = Buffer.from([0xff, 0xd8, 0xff, 0xe0, 0, 0, 0xff, 0xd9]);
const JPEG_DIGEST = `sha256:${createHash("sha256").update(JPEG_BYTES).digest("hex")}`;

function completeMedia() {
  return {
    frames: [5_000, 15_000, 25_000, 35_000].map((timestampMs) => ({
      timestampMs,
      mimeType: "image/jpeg",
      byteLength: JPEG_BYTES.length,
      contentDigest: JPEG_DIGEST,
      extractionRevision: CANDIDATE_PASS_B_FRAME_EXTRACTION_REVISION,
      dataBase64: JPEG_BYTES.toString("base64"),
    })),
    audio: {
      rawAudio: Buffer.from([1, 2, 3]),
      contentDigest: digest("5"),
    },
  };
}

function analyzer(overrideInsight = {}) {
  return async ({
    candidate,
    context: candidateContext,
    frames,
    semanticAttempt = { attemptOrdinal: 0, retryGrantId: null },
  }) => {
    assert.equal(frames.length, 4);
    const mediaFrames = frames.map((frame) => ({
      timestampMs: frame.timestampMs,
      mimeType: frame.mimeType,
      byteLength: frame.byteLength,
      contentDigest: frame.contentDigest,
      extractionRevision: frame.extractionRevision,
    }));
    const dispatch = {
      schemaVersion: CANDIDATE_PASS_B_DISPATCH_INTENT_SCHEMA_VERSION,
      operationId:
        `candidate-pass-b.${candidate.candidateId}.${semanticAttempt.attemptOrdinal}`,
      analysisRunId: "scheduled-review-test",
      candidateId: candidate.candidateId,
      sourceFingerprint: "scheduled-source-test",
      sourceStartMs: candidate.startMs,
      sourceEndMs: candidate.endMs,
      contextFingerprint: candidatePassBContextFingerprint(candidateContext),
      outputLanguage: "ko",
      castRosterId: null,
      routingModelRevision: CANDIDATE_PASS_B_ROUTING_MODEL_REVISION,
      attemptOrdinal: semanticAttempt.attemptOrdinal,
      retryGrantId: semanticAttempt.retryGrantId,
      transportMode: "paid-direct",
      mediaReceipt: {
        schemaVersion: CANDIDATE_PASS_B_MEDIA_RECEIPT_SCHEMA_VERSION,
        frameExtractionRevision: CANDIDATE_PASS_B_FRAME_EXTRACTION_REVISION,
        frames: mediaFrames,
        audio: {
          kind: "audible-audio",
          wavByteLength: 32_044,
          wavContentDigest: digest("5"),
          sampleRateHz: CANDIDATE_PASS_B_SAMPLE_RATE_HZ,
          sampleCount: 16_000,
        },
        providerPayloadDigest: digest("6"),
      },
    };
    const settlement = {
      schemaVersion: CANDIDATE_PASS_B_SETTLEMENT_SCHEMA_VERSION,
      status: "completed",
      operationId: dispatch.operationId,
      providerPayloadDigest: dispatch.mediaReceipt.providerPayloadDigest,
      outputLanguage: "ko",
      castRosterId: null,
      responseDigest: digest("7"),
      providerModelId: CANDIDATE_PASS_B_QWEN_MODEL_ID,
      providerModelRevision: CANDIDATE_PASS_B_QWEN_MODEL_REVISION,
    };
    const receipt = createCandidatePassBVerificationReceipt(
      candidateContext,
      25_000,
      {
        candidateId: candidate.candidateId,
        sourceStartMs: candidate.startMs,
        sourceEndMs: candidate.endMs,
        routingModelRevision: CANDIDATE_PASS_B_ROUTING_MODEL_REVISION,
        refinementEvidenceProjectionFingerprint: null,
        outputLanguage: "ko",
        castRosterId: null,
      },
      dispatch,
      settlement,
    );
    assert.ok(receipt);
    return {
      insight: {
        eventSummaryKo: "오랜 도전 끝에 목표를 달성했습니다.",
        reactionSummaryKo: "스트리머가 안도하며 기뻐합니다.",
        whyGoodClipKo: "앞선 실패와 성공의 보상이 한 구간에 담겼습니다.",
        uncertaintiesKo: [],
        participantPresence: "present-unidentified",
        participantSummaryKo: "화면에 진행자가 있지만 이름 근거는 없습니다.",
        identifiedParticipants: [],
        clipDecision: "recommend",
        contextConsistency: "consistent",
        programMaterial: "streamer-event",
        ...overrideInsight,
      },
      model: {
        id: CANDIDATE_PASS_B_QWEN_MODEL_ID,
        revision: CANDIDATE_PASS_B_QWEN_MODEL_REVISION,
      },
      verificationReceipt: receipt,
    };
  };
}

function runnerInput(bundle, overrides = {}) {
  return {
    sourceId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.sourceId,
    artifactRevision: 1,
    createdAt: CREATED_AT,
    pipelineRevision: "scheduled-review-test-v1",
    bundle,
    audioFeatures: audioFeatures(),
    visualCoverage: visualCoverage(),
    visualCandidateSeeds: [],
    participantGrounding: participantGrounding(),
    extractCandidateMedia: async () => completeMedia(),
    analyzeCandidate: analyzer(),
    candidateConcurrency: 2,
    ...overrides,
  };
}

function contextFor(durationMs, sourceChapters, discoveredLeads) {
  return {
    schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
    broadcastSummaryKo: "방송 전체의 사건 흐름과 반응을 자막 근거로 정리했습니다.",
    hostStreamerProfile: null,
    recurringThemesKo: ["방송 사건과 반응"],
    annotations: [],
    semanticChaptersSupported: true,
    semanticChapters: [
      {
        semanticChapterId: "semantic-all",
        startChapterId: sourceChapters[0].chapterId,
        endChapterId: sourceChapters.at(-1).chapterId,
        startMs: 0,
        endMs: durationMs,
        titleKo: "전체 방송 흐름",
        summaryKo: "방송에서 일어난 사건과 스트리머의 반응이 시간순으로 이어집니다.",
        kind: "story-progress",
        salience: "primary",
        relatedCandidateIds: [],
        uncertaintiesKo: [],
      },
    ],
    discoveredLeadsSupported: true,
    discoveredLeads,
    coverage: {
      status: "complete",
      coveredMs: durationMs,
      coverageRatio: 1,
      gaps: [],
      partialChapterIds: [],
    },
  };
}

async function customBundle({ durationMs, sourceChapters, captionEvents, discoveredLeads }) {
  return createChannelPreanalysisBundle({
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: "후보 정책 검증 방송",
    durationMs,
    publishedAt: "2026-08-02T00:00:00.000Z",
    catalogRevision: 1,
    state: "context-ready",
    captionTrack: {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: false,
      events: captionEvents,
    },
    chapters: sourceChapters,
    broadcastContext: contextFor(durationMs, sourceChapters, discoveredLeads),
    contextProvenance: {
      generatedAt: "2026-08-02T03:00:00.000Z",
      modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
      contextReceipt: {
        contractVersion: "2.0.0",
        routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
        modelId: "qwen3.7-plus",
        modelRevision: "scheduled-context-test-v1",
      },
      evidenceScope: "youtube-caption-transcript-only",
      localVisualVerificationRequired: true,
    },
    provenance: createDefaultChannelPreanalysisProvenance(
      VIDEO_ID,
      "2026-08-02T02:00:00.000Z",
    ),
  });
}

function audioFeaturesFor(durationMs, reactionStartIndices = []) {
  const windowCount = durationMs / 1_000;
  const windows = Array.from({ length: windowCount }, (_, index) => {
    const rms = 0.055 + (index % 4) * 0.002;
    return {
      startMs: index * 1_000,
      endMs: (index + 1) * 1_000,
      rms,
      peak: Math.min(1, rms * 3),
      zeroCrossingRate: 0.09 + (index % 3) * 0.005,
      speechBandEnergyRatio: 0.52,
    };
  });
  for (const startIndex of reactionStartIndices) {
    [0.18, 0.25, 0.17, 0.23].forEach((rms, offset) => {
      const index = startIndex + offset;
      windows[index] = {
        startMs: index * 1_000,
        endMs: (index + 1) * 1_000,
        rms,
        peak: Math.min(0.92, rms * 3.1),
        zeroCrossingRate: 0.14 + (offset % 3) * 0.035,
        speechBandEnergyRatio: 0.72 + (offset % 2) * 0.08,
      };
    });
  }
  return {
    sourceDurationMs: durationMs,
    plannedWindowCount: windowCount,
    analyzedWindowCount: windowCount,
    coverageComplete: true,
    windows,
  };
}

function visualCoverageFor(durationMs, visualSeeds) {
  const plannedSampleCount =
    channelPreanalysisVisualCoveragePlannedSampleCount(durationMs);
  return {
    schemaVersion: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SCHEMA_VERSION,
    algorithm: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_ALGORITHM,
    status: "complete",
    sourceDurationMs: durationMs,
    sampleIntervalMs: CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
    plannedSampleCount,
    analyzedSampleCount: plannedSampleCount,
    firstSampleTimestampMs: 0,
    lastSampleTimestampMs:
      (plannedSampleCount - 1) *
      CHANNEL_PREANALYSIS_VISUAL_COVERAGE_SAMPLE_INTERVAL_MS,
    coveredThroughMs: durationMs,
    gaps: [],
    sourceFingerprintArtifactId:
      `youtube-storyboard-visual-fingerprint:${VIDEO_ID}:v1`,
    sourceFingerprintDigest: digest("8"),
    visualSeedCount: visualSeeds.length,
    visualSeedTimestampsMs: visualSeeds.map(({ focusMs }) => focusMs),
  };
}

function customRunnerInput(bundle, sourceChapters, overrides = {}) {
  return runnerInput(bundle, {
    audioFeatures: audioFeaturesFor(bundle.durationMs),
    visualCoverage: visualCoverageFor(bundle.durationMs, []),
    visualCandidateSeeds: [],
    participantGrounding: createBroadcastParticipantGrounding({
      sourceDurationMs: bundle.durationMs,
      castRosterId: null,
      chapters: sourceChapters,
    }),
    candidateConcurrency: 1,
    ...overrides,
  });
}

test("semantic and audio inputs produce one self-contained verified review artifact", async () => {
  const result = await runChannelPreanalysisReview(runnerInput(await contextReadyBundle()));
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.candidates.length, 1);
  assert.equal(result.reviewBundle.certificate.outcome, "review-ready");
  assert.equal(result.reviewBundle.candidates[0].frames.length, 4);
  assert.equal(JSON.stringify(result.reviewBundle).includes("rawAudio"), false);
  assert.equal(result.reviewBundle.participantGrounding.resolutionStatus, "media-reviewed");
  assert.deepEqual(
    result.reviewBundle.participantGrounding.adapterReceipts
      .slice(1)
      .map(({ status, inputCount, processedCount }) => ({
        status,
        inputCount,
        processedCount,
      })),
    [
      { status: "completed", inputCount: 1, processedCount: 1 },
      { status: "completed", inputCount: 1, processedCount: 1 },
    ],
  );
  assert.ok(
    result.reviewBundle.participantGrounding.evidence.some(
      ({ kind }) => kind === "visible-participant-unidentified",
    ),
  );
  assert.ok(
    result.reviewBundle.participantGrounding.evidence.some(
      ({ kind }) => kind === "speaker-unidentified",
    ),
  );
  await verifyChannelPreanalysisReviewBundleIntegrity(result.reviewBundle);
});

test("missing visual coverage fails closed before verified-empty publication", async () => {
  await assert.rejects(
    runChannelPreanalysisReview(
      runnerInput(await contextReadyBundle([]), {
        visualCoverage: undefined,
      }),
    ),
    (error) => error.code === "VISUAL_COVERAGE_INCOMPLETE",
  );
});

test("a source with complete static visual coverage and no other lead is verified-empty", async () => {
  let mediaCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle([]), {
      extractCandidateMedia: async () => {
        mediaCalls += 1;
        return completeMedia();
      },
      analyzeCandidate: async () => assert.fail("AI must not run without candidates"),
    }),
  );
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "verified-empty");
  assert.deepEqual(result.reviewBundle.candidates, []);
  assert.equal(result.reviewBundle.participantGrounding.resolutionStatus, "media-reviewed");
  assert.ok(
    result.reviewBundle.participantGrounding.adapterReceipts
      .slice(1)
      .every(({ status, inputCount }) => status === "completed" && inputCount === 0),
  );
  assert.equal(mediaCalls, 0);
});

test("an explicit music-only caption is removed before media and AI review", async () => {
  const durationMs = 120_000;
  const sourceChapters = [{
    chapterId: "opening-music",
    startMs: 0,
    endMs: durationMs,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "오프닝 음악 구간입니다.",
  }];
  const bundle = await customBundle({
    durationMs,
    sourceChapters,
    captionEvents: [{
      startMs: 45_000,
      durationMs: 2_000,
      text: "[음악] >> เฮ [음악]",
    }],
    discoveredLeads: [{
      leadId: "opening-music-lead",
      startChapterId: "opening-music",
      endChapterId: "opening-music",
      startMs: 30_000,
      endMs: 90_000,
      category: "context-dependent",
      confidence: 0.9,
      eventSummaryKo: "오프닝 음악이 재생됩니다.",
      whyThisMomentKo: "음악 구간입니다.",
      evidenceCueKo: "오프닝 음악",
      uncertaintiesKo: [],
    }],
  });
  let mediaCalls = 0;
  let aiCalls = 0;

  const result = await runChannelPreanalysisReview(customRunnerInput(bundle, sourceChapters, {
    extractCandidateMedia: async () => {
      mediaCalls += 1;
      return completeMedia();
    },
    analyzeCandidate: async () => {
      aiCalls += 1;
      return analyzer()();
    },
  }));

  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "verified-empty");
  assert.deepEqual(result.reviewBundle.candidates, []);
  assert.deepEqual(result.candidateResults, []);
  assert.equal(mediaCalls, 0);
  assert.equal(aiCalls, 0);
});

test("a quiet visual event enters four-frame AI verification without an audio or semantic lead", async () => {
  let aiCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle([]), {
      visualCoverage: visualCoverage(1),
      visualCandidateSeeds: [quietVisualSeed()],
      analyzeCandidate: async (input) => {
        aiCalls += 1;
        assert.deepEqual(input.candidate.sourceKinds, ["visual"]);
        assert.equal(input.frames.length, 4);
        return analyzer()(input);
      },
    }),
  );
  assert.equal(aiCalls, 1);
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "review-ready");
  assert.equal(result.reviewBundle.visualCoverage.visualSeedCount, 1);
});

test("three frames stop that candidate before AI and preserve a retry checkpoint", async () => {
  let aiCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle(), {
      extractCandidateMedia: async () => ({
        ...completeMedia(),
        frames: completeMedia().frames.slice(0, 3),
      }),
      analyzeCandidate: async () => {
        aiCalls += 1;
        return analyzer()();
      },
    }),
  );
  assert.equal(result.status, "incomplete");
  assert.equal(result.reviewBundle, null);
  assert.equal(result.candidateResults[0].status, "retryable");
  assert.equal(result.candidateResults[0].errorCode, "FRAME_BUNDLE_INCOMPLETE");
  assert.equal(aiCalls, 0);
});

test("AI-confirmed music is a terminal exclusion and can yield verified-empty", async () => {
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle(), {
      analyzeCandidate: analyzer({
        clipDecision: "reject",
        programMaterial: "music-or-intermission",
      }),
    }),
  );
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "verified-empty");
  assert.equal(result.candidateResults[0].status, "analyzed");
  assert.equal(result.candidateResults[0].resolution, "terminal-excluded");
  assert.equal(result.candidateResults[0].attemptOrdinal, 0);
});

for (const [label, insight] of [
  ["an uncertain verdict", { clipDecision: "uncertain" }],
  [
    "an unclear program-material verdict",
    { clipDecision: "reject", programMaterial: "routine-or-unclear" },
  ],
  [
    "a contradictory verdict",
    { clipDecision: "reject", contextConsistency: "conflict" },
  ],
  [
    "an incoherent verdict",
    { clipDecision: "recommend", programMaterial: "music-or-intermission" },
  ],
  [
    "an insufficient-context music verdict",
    {
      clipDecision: "reject",
      contextConsistency: "insufficient",
      programMaterial: "music-or-intermission",
    },
  ],
]) {
  test(`${label} becomes a fully-evidenced editor review after two bounded recoveries`, async () => {
    let aiCalls = 0;
    let mediaCalls = 0;
    const result = await runChannelPreanalysisReview(
      runnerInput(await contextReadyBundle(), {
        extractCandidateMedia: async () => {
          mediaCalls += 1;
          return completeMedia();
        },
        analyzeCandidate: async (input) => {
          aiCalls += 1;
          return analyzer({
            ...insight,
            uncertaintiesKo: ["추가 확인이 필요합니다."],
          })(input);
        },
      }),
    );
    assert.equal(result.status, "complete");
    assert.equal(result.reviewBundle.certificate.outcome, "review-ready");
    assert.equal(result.reviewBundle.candidates.length, 1);
    assert.equal(result.candidateResults[0].status, "analyzed");
    assert.equal(result.candidateResults[0].resolution, "editor-review");
    assert.equal(result.candidateResults[0].attemptOrdinal, 2);
    assert.equal(result.reviewBundle.candidates[0].insight.clipDecision,
      insight.clipDecision);
    assert.equal(mediaCalls, 1);
    assert.equal(aiCalls, 3);
    assert.deepEqual(result.retryCandidateIds, []);
  });
}

test("a crash resume repeats the durable semantic attempt instead of issuing another charge", async () => {
  const bundle = await contextReadyBundle();
  let aiCalls = 0;
  const persisted = [];
  const first = await runChannelPreanalysisReview(runnerInput(bundle, {
    analyzeCandidate: async (input) => {
      aiCalls += 1;
      if (input.semanticAttempt.attemptOrdinal === 0) {
        return analyzer({ clipDecision: "uncertain" })(input);
      }
      const error = new Error("transport retry budget exhausted");
      error.code = "RETRY_EXHAUSTED";
      throw error;
    },
    onCandidateCheckpoint: async (checkpoint) => {
      persisted.push(checkpoint);
    },
  }));
  assert.equal(first.status, "incomplete");
  assert.equal(first.candidateResults[0].status, "retryable");
  assert.equal(first.candidateResults[0].attemptOrdinal, 1);
  assert.notEqual(first.candidateResults[0].retryGrantId, null);
  assert.equal(
    first.candidateResults[0].lastRecord.verificationReceipt.dispatchIntent
      .attemptOrdinal,
    0,
  );
  assert.equal(persisted.at(-1).status, "retryable");

  let resumedAttempt = null;
  const recovered = await runChannelPreanalysisReview(runnerInput(bundle, {
    previousCandidateResults: first.candidateResults,
    analyzeCandidate: async (input) => {
      aiCalls += 1;
      resumedAttempt = input.semanticAttempt;
      return analyzer()(input);
    },
  }));
  assert.equal(aiCalls, 3);
  assert.deepEqual(resumedAttempt, {
    attemptOrdinal: 1,
    retryGrantId: first.candidateResults[0].retryGrantId,
  });
  assert.equal(recovered.status, "complete");
  assert.equal(recovered.reviewBundle.certificate.outcome, "review-ready");
  assert.equal(recovered.candidateResults[0].attemptOrdinal, 1);
  assert.equal(recovered.candidateResults[0].resolution, "publish");
});

test("provider terminal parse failures advance semantic identity while transport exhaustion does not", async () => {
  const attempts = [];
  let mediaCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle(), {
      extractCandidateMedia: async () => {
        mediaCalls += 1;
        return completeMedia();
      },
      analyzeCandidate: async (input) => {
        attempts.push(input.semanticAttempt);
        if (input.semanticAttempt.attemptOrdinal < 2) {
          const error = new Error("cached provider response cannot be parsed");
          error.code = input.semanticAttempt.attemptOrdinal === 0
            ? "RESPONSE_INVALID"
            : "RESPONSE_RECEIPT_INVALID";
          throw error;
        }
        return analyzer()(input);
      },
    }),
  );

  assert.equal(result.status, "complete");
  assert.equal(result.candidateResults[0].resolution, "publish");
  assert.deepEqual(attempts.map(({ attemptOrdinal }) => attemptOrdinal), [0, 1, 2]);
  assert.equal(new Set(attempts.slice(1).map(({ retryGrantId }) => retryGrantId)).size, 2);
  assert.equal(mediaCalls, 1);
});

test("terminal parse failures at the cap preserve an earlier uncertain result for editor review", async () => {
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle(), {
      analyzeCandidate: async (input) => {
        if (input.semanticAttempt.attemptOrdinal === 0) {
          return analyzer({
            clipDecision: "uncertain",
            uncertaintiesKo: ["추가 확인이 필요합니다."],
          })(input);
        }
        const error = new Error("cached provider response cannot be parsed");
        error.code = "RESPONSE_INVALID";
        throw error;
      },
    }),
  );

  assert.equal(result.status, "complete");
  assert.equal(result.candidateResults[0].resolution, "editor-review");
  assert.equal(result.candidateResults[0].attemptOrdinal, 0);
  assert.equal(result.reviewBundle.candidates[0].insight.clipDecision, "uncertain");
});

test("a text-only music annotation cannot bypass exact multimodal verification", async () => {
  let aiCalls = 0;
  const result = await runChannelPreanalysisReview(
    runnerInput(await contextReadyBundle(undefined, [{
      candidateId: "quiet-success",
      category: "music-or-intermission",
      clipDecision: "reject",
      confidence: 0.99,
      rejectionReasons: ["music-or-song"],
      contextSummaryKo: "자막 맥락만 보면 음악 구간일 가능성이 있습니다.",
      whyThisMomentKo: "대표 화면과 실제 오디오는 아직 확인하지 않았습니다.",
      relatedCandidateIds: [],
      uncertaintiesKo: ["멀티모달 확인 필요"],
    }]), {
      analyzeCandidate: async (input) => {
        aiCalls += 1;
        return analyzer()(input);
      },
    }),
  );
  assert.equal(aiCalls, 1);
  assert.equal(result.status, "complete");
  assert.equal(result.reviewBundle.certificate.outcome, "review-ready");
  assert.equal(result.reviewBundle.candidates.length, 1);
});

test("completed per-candidate checkpoints skip media extraction and AI on resume", async () => {
  const bundle = await contextReadyBundle();
  const first = await runChannelPreanalysisReview(runnerInput(bundle));
  let calls = 0;
  const resumed = await runChannelPreanalysisReview(
    runnerInput(bundle, {
      previousCandidateResults: first.candidateResults,
      extractCandidateMedia: async () => {
        calls += 1;
        return completeMedia();
      },
      analyzeCandidate: async () => {
        calls += 1;
        return null;
      },
    }),
  );
  assert.equal(resumed.status, "complete");
  assert.equal(calls, 0);
  assert.deepEqual(resumed.reviewBundle, first.reviewBundle);
});

test("caption cues localize broad same-chapter semantic leads without fusing them", async () => {
  const durationMs = 300_000;
  const sourceChapters = [{
    chapterId: "broad-chapter",
    startMs: 0,
    endMs: durationMs,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "두 사건이 멀리 떨어져 일어난 긴 주제 구간입니다.",
  }];
  const discoveredLeads = [
    {
      leadId: "first-incident",
      startChapterId: "broad-chapter",
      endChapterId: "broad-chapter",
      startMs: 0,
      endMs: durationMs,
      category: "apology-accountability",
      confidence: 0.95,
      eventSummaryKo: "첫 번째 사건 뒤 사과했습니다.",
      whyThisMomentKo: "사건과 수습이 함께 담깁니다.",
      evidenceCueKo: "첫 번째 사건 사과 단서",
      uncertaintiesKo: [],
    },
    {
      leadId: "second-success",
      startChapterId: "broad-chapter",
      endChapterId: "broad-chapter",
      startMs: 0,
      endMs: durationMs,
      category: "quiet-achievement",
      confidence: 0.94,
      eventSummaryKo: "두 번째 목표를 조용히 달성했습니다.",
      whyThisMomentKo: "긴 시도 끝의 성공 맥락이 있습니다.",
      evidenceCueKo: "두 번째 조용한 성공 단서",
      uncertaintiesKo: [],
    },
  ];
  const bundle = await customBundle({
    durationMs,
    sourceChapters,
    discoveredLeads,
    captionEvents: [
      { startMs: 25_000, durationMs: 2_000, text: "첫 번째 사건 사과 단서" },
      { startMs: 205_000, durationMs: 2_000, text: "두 번째 조용한 성공 단서" },
    ],
  });
  const visualSeed = {
    seedId: "visual-second-success",
    startMs: 150_000,
    endMs: 210_000,
    focusMs: 180_000,
    score: 0.99,
    eventKo: "화면 변화",
    whyKo: "두 번째 사건과 겹치는 화면 근거입니다.",
    evidenceKo: "화면 변화 점수 0.99",
  };
  const seen = [];

  const result = await runChannelPreanalysisReview(customRunnerInput(bundle, sourceChapters, {
    visualCoverage: visualCoverageFor(durationMs, [visualSeed]),
    visualCandidateSeeds: [visualSeed],
    analyzeCandidate: async (input) => {
      seen.push(input.candidate);
      return analyzer()(input);
    },
  }));

  assert.equal(result.status, "complete");
  assert.equal(seen.length, 2);
  const first = seen.find(({ originIds }) => originIds.includes("first-incident"));
  const second = seen.find(({ originIds }) => originIds.includes("second-success"));
  assert.deepEqual(
    { startMs: first.startMs, focusMs: first.focusMs, endMs: first.endMs },
    { startMs: 0, focusMs: 15_000, endMs: 60_000 },
  );
  assert.deepEqual(second.sourceKinds, ["semantic", "visual"]);
  assert.deepEqual(
    { startMs: second.startMs, focusMs: second.focusMs, endMs: second.endMs },
    { startMs: 165_000, focusMs: 195_000, endMs: 225_000 },
  );
});

test("candidate evidence and transcript context keep captions nearest the focus", async () => {
  const durationMs = 120_000;
  const sourceChapters = [{
    chapterId: "chapter-all",
    startMs: 0,
    endMs: durationMs,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: "화면 후보의 자막 근거를 검증합니다.",
  }];
  const captionEvents = Array.from({ length: 31 }, (_, index) => ({
    startMs: 35_000 + index * 1_000,
    durationMs: 700,
    text: index === 25 ? "후보 정점의 핵심 대사" : `순서 자막 ${index}`,
  }));
  const bundle = await customBundle({
    durationMs,
    sourceChapters,
    discoveredLeads: [],
    captionEvents,
  });
  const visualSeed = quietVisualSeed();
  let observed;

  const result = await runChannelPreanalysisReview(customRunnerInput(bundle, sourceChapters, {
    visualCoverage: visualCoverageFor(durationMs, [visualSeed]),
    visualCandidateSeeds: [visualSeed],
    analyzeCandidate: async (input) => {
      observed = input;
      return analyzer()(input);
    },
  }));

  assert.equal(result.status, "complete");
  assert.match(observed.context.transcriptKo, /후보 정점의 핵심 대사/u);
  assert.ok(observed.evidence.cues.some(({ text }) => text === "후보 정점의 핵심 대사"));
  assert.equal(observed.evidence.quality.receivedChunkCount, 29);
});

test("whole-context semantic leads take priority while audio and visual remain analyzed reserves", async () => {
  const durationMs = 2_000_000;
  const sourceChapters = Array.from({ length: 20 }, (_, index) => ({
    chapterId: `chapter-${index + 1}`,
    startMs: index * 100_000,
    endMs: (index + 1) * 100_000,
    evidenceMode: "complete-transcript",
    evidenceCoverageRatio: 1,
    summaryKo: `${index + 1}번째 방송 주제 구간입니다.`,
  }));
  const discoveredLeads = Array.from({ length: 14 }, (_, index) => ({
    leadId: `semantic-lead-${index + 1}`,
    startChapterId: sourceChapters[index].chapterId,
    endChapterId: sourceChapters[index].chapterId,
    startMs: sourceChapters[index].startMs,
    endMs: sourceChapters[index].endMs,
    category: "context-dependent",
    confidence: 0.99 - index * 0.01,
    eventSummaryKo: `${index + 1}번째 의미 사건입니다.`,
    whyThisMomentKo: "전체 흐름에서 독립적으로 검토할 사건입니다.",
    evidenceCueKo: `의미 단서 ${index + 1}`,
    uncertaintiesKo: [],
  }));
  const captionEvents = discoveredLeads.map((lead, index) => ({
    startMs: index * 100_000 + 10_000,
    durationMs: 2_000,
    text: lead.evidenceCueKo,
  }));
  const visualSeeds = [1_600_000, 1_700_000, 1_800_000, 1_900_000].map(
    (focusMs, index) => ({
      seedId: `visual-seed-${index + 1}`,
      startMs: focusMs - 22_500,
      endMs: focusMs + 22_500,
      focusMs,
      score: 0.98 - index * 0.01,
      eventKo: `${index + 1}번째 화면 사건`,
      whyKo: "독립된 화면 변화 후보입니다.",
      evidenceKo: "화면 변화 근거",
    }),
  );
  const run = async (leads) => {
    const bundle = await customBundle({
      durationMs,
      sourceChapters,
      discoveredLeads: leads,
      captionEvents,
    });
    const seen = [];
    const result = await runChannelPreanalysisReview(customRunnerInput(bundle, sourceChapters, {
      audioFeatures: audioFeaturesFor(durationMs, [1_100, 1_200, 1_300, 1_400]),
      visualCoverage: visualCoverageFor(durationMs, visualSeeds),
      visualCandidateSeeds: visualSeeds,
      analyzeCandidate: async (input) => {
        seen.push(input.candidate);
        return analyzer()(input);
      },
    }));
    assert.equal(result.status, "complete");
    return { seen, result };
  };

  const first = await run(discoveredLeads);
  const second = await run([...discoveredLeads].reverse());
  assert.equal(first.seen.length, 16);
  assert.equal(
    first.seen.filter(({ sourceKinds }) => sourceKinds.includes("semantic")).length,
    12,
  );
  assert.equal(
    first.seen.filter(({ sourceKinds }) => !sourceKinds.includes("semantic")).length,
    4,
  );
  assert.deepEqual(
    first.seen.map(({ candidateId }) => candidateId),
    second.seen.map(({ candidateId }) => candidateId),
  );
  assert.equal(first.result.reviewBundle.candidates.length, 12);
  assert.ok(first.result.reviewBundle.candidates.every(({ candidateId }) => {
    const analyzed = first.seen.find((candidate) => candidate.candidateId === candidateId);
    return analyzed?.sourceKinds.includes("semantic") === true;
  }));
  assert.ok(first.result.reviewBundle.candidates.some(({ candidateId }) =>
    first.seen.find(({ candidateId: analyzedId }) => analyzedId === candidateId)
      ?.originIds.includes("semantic-lead-12")
  ));
});
