import {
  createContentFingerprint,
  type ContentDigestAdapter,
} from "../security/contentFingerprint";
import {
  MAX_BROADCAST_CONTEXT_SOURCE_DURATION_MS,
} from "./broadcastContextProtocol";
import {
  broadcastRefinementTranscriptCheckpointCanComplete,
  parseBroadcastRefinementTranscriptCheckpointJson,
  serializeBroadcastRefinementTranscriptCheckpoint,
  type BroadcastRefinementTranscriptCheckpoint,
  type BroadcastRefinementTranscriptGapReason,
} from "./broadcastRefinementTranscriptCheckpoint";
import {
  DISCOVERED_LEAD_REFINEMENT_BUDGET_USD,
  DISCOVERED_LEAD_REFINEMENT_VERSION,
  MAX_CAPTION_DISCOVERED_LEADS_TO_REFINE,
  type DiscoveredLeadRefinementPlan,
} from "./discoveredLeadRefinement";
import {
  broadcastTranscriptProviderReceiptCheckpointModelRevision,
  parseBroadcastTranscriptProviderReceiptCheckpointJson,
  serializeBroadcastTranscriptProviderReceiptCheckpoint,
  type BroadcastTranscriptProviderReceiptCheckpoint,
} from "./broadcastTranscriptProviderReceiptCheckpoint";
import {
  MAX_BROADCAST_TRANSCRIPT_QWEN_TEXT_LENGTH,
} from "./broadcastTranscriptQwen";
import {
  MAX_BROADCAST_TRANSCRIPT_WORKER_CHUNKS,
  isBroadcastTranscriptChunkId,
} from "./broadcastTranscriptWorkerProtocol";
import {
  broadcastSpeechActivityCanSkipAsr,
  normalizeBroadcastSpeechActivityRunReceipt,
  type BroadcastSpeechActivityRunReceipt,
} from "./broadcastSpeechActivity";
import {
  MAX_YOUTUBE_CAPTION_EVENTS,
  MAX_YOUTUBE_CAPTION_EVENT_TEXT_LENGTH,
  YOUTUBE_VIDEO_ID_PATTERN,
  createYouTubeCaptionRefinementTranscripts,
  type YouTubeCaptionTrackResult,
} from "./youtubeCaptionTrack";

export const BROADCAST_REFINEMENT_EVIDENCE_LEDGER_SCHEMA_VERSION =
  "1.0.0" as const;
export const MAX_BROADCAST_REFINEMENT_EVIDENCE_ROUTE_ENTRIES = 32;
export const MAX_BROADCAST_REFINEMENT_EVIDENCE_LEDGER_BYTES =
  16 * 1024 * 1024;

const SHA256_PATTERN = /^sha256:[a-f0-9]{64}$/u;
const MAX_IDENTIFIER_LENGTH = 256;
const MAX_FENCE_LENGTH = 2_048;
const MAX_GENERATION = 1_000_000;
const LEDGER_FINGERPRINT_DOMAIN =
  "exclipper.broadcast-refinement-evidence-ledger.v1";
const SELECTED_LEAD_PLAN_FINGERPRINT_DOMAIN =
  "exclipper.broadcast-refinement-selected-lead-plan.v1";
const ROUTE_ENTRY_FINGERPRINT_DOMAIN =
  "exclipper.broadcast-refinement-evidence-route-entry.v1";
const ACTIVE_ROUTE_PROJECTION_FINGERPRINT_DOMAIN =
  "exclipper.broadcast-refinement-active-route-projection.v1";
const CAPTION_EVENT_SOURCE_FENCE_DOMAIN =
  "exclipper.broadcast-refinement-caption-event-source.v1";
const PROVIDER_CHECKPOINT_SIGNATURE_DOMAIN =
  "exclipper.broadcast-refinement-provider-checkpoint.v1";

export type BroadcastRefinementEvidenceRouteKind =
  | "youtube-caption"
  | "asr";
export type BroadcastRefinementEvidenceBillingClass = "free" | "paid";

interface BroadcastRefinementEvidenceCellBase {
  readonly segmentId: string;
  readonly leadId: string;
  readonly sourceStartMs: number;
  readonly sourceEndMs: number;
}

export type BroadcastRefinementCaptionCellSettlement =
  | (BroadcastRefinementEvidenceCellBase & {
      readonly status: "success";
      readonly textKo: string;
    })
  | (BroadcastRefinementEvidenceCellBase & {
      readonly status: "resolved";
      readonly reason: "no-speech";
    })
  | (BroadcastRefinementEvidenceCellBase & {
      readonly status: "gap";
      readonly reason: BroadcastRefinementTranscriptGapReason;
    });

export interface BroadcastRefinementEvidenceSettlementSummary {
  readonly plannedCellCount: number;
  readonly successCellCount: number;
  readonly resolvedCellCount: number;
  readonly gapCellCount: number;
  readonly missingCellCount: number;
  readonly status: "settled" | "blocked";
  readonly publicationEligible: boolean;
}

export interface BroadcastRefinementCaptionEvidencePayload {
  readonly kind: "youtube-caption-cells";
  readonly settlements: readonly BroadcastRefinementCaptionCellSettlement[];
  readonly verifiedNoSpeechEvidence:
    readonly BroadcastRefinementCaptionSpeechActivityEvidence[];
}

export interface BroadcastRefinementAsrEvidencePayload {
  readonly kind: "asr-refinement-checkpoints";
  readonly refinementCheckpoint: BroadcastRefinementTranscriptCheckpoint;
  readonly providerReceiptCheckpoint: BroadcastTranscriptProviderReceiptCheckpoint;
}

export type BroadcastRefinementEvidencePayload =
  | BroadcastRefinementCaptionEvidencePayload
  | BroadcastRefinementAsrEvidencePayload;

export interface BroadcastRefinementCaptionSourceIdentity {
  readonly videoId: string;
  readonly languageCode: string;
  readonly isAutoGenerated: boolean;
}

export interface BroadcastRefinementEvidenceRouteEntry {
  readonly entryFingerprint: string;
  readonly ordinal: number;
  readonly routeKind: BroadcastRefinementEvidenceRouteKind;
  readonly billingClass: BroadcastRefinementEvidenceBillingClass;
  readonly sourceFingerprint: string;
  readonly sourceDurationMs: number;
  readonly selectedLeadPlanFingerprint: string;
  readonly evidenceRevision: string;
  readonly captionEventSourceFence: string | null;
  readonly providerReceiptCheckpointSignature: string | null;
  readonly captionSource: BroadcastRefinementCaptionSourceIdentity | null;
  readonly evidencePayload: BroadcastRefinementEvidencePayload;
  readonly settlement: BroadcastRefinementEvidenceSettlementSummary;
}

export interface BroadcastRefinementEvidenceLedger {
  readonly schemaVersion:
    typeof BROADCAST_REFINEMENT_EVIDENCE_LEDGER_SCHEMA_VERSION;
  readonly generation: number;
  readonly sourceFingerprint: string;
  readonly sourceDurationMs: number;
  readonly selectedLeadPlan: DiscoveredLeadRefinementPlan;
  readonly selectedLeadPlanFingerprint: string;
  readonly activeRouteEntryFingerprint: string | null;
  readonly activeRouteProjectionFingerprint: string | null;
  readonly routeEntries: readonly BroadcastRefinementEvidenceRouteEntry[];
  readonly ledgerFingerprint: string;
}

export interface BroadcastRefinementEvidenceLedgerBinding {
  readonly sourceFingerprint: string;
  readonly sourceDurationMs: number;
  readonly selectedLeadPlan: DiscoveredLeadRefinementPlan;
}

export interface AppendBroadcastRefinementCaptionEvidenceInput
  extends BroadcastRefinementEvidenceLedgerBinding {
  readonly routeKind: "youtube-caption";
  readonly captionRevision: string;
  readonly captionTrack: YouTubeCaptionTrackResult;
  readonly verifiedNoSpeechEvidence:
    readonly BroadcastRefinementCaptionSpeechActivityEvidence[];
}

export interface AppendBroadcastRefinementAsrEvidenceInput
  extends BroadcastRefinementEvidenceLedgerBinding {
  readonly routeKind: "asr";
  readonly billingClass: BroadcastRefinementEvidenceBillingClass;
  readonly refinementCheckpoint: BroadcastRefinementTranscriptCheckpoint;
  readonly providerReceiptCheckpoint: BroadcastTranscriptProviderReceiptCheckpoint;
}

export type AppendBroadcastRefinementEvidenceInput =
  | AppendBroadcastRefinementCaptionEvidenceInput
  | AppendBroadcastRefinementAsrEvidenceInput;

export interface BroadcastRefinementActiveRouteProjection {
  readonly projectionFingerprint: string;
  readonly routeEntryFingerprint: string;
  readonly routeKind: BroadcastRefinementEvidenceRouteKind;
  readonly billingClass: BroadcastRefinementEvidenceBillingClass;
  readonly evidenceRevision: string;
  readonly publicationEligible: boolean;
}

export interface BroadcastRefinementCaptionSpeechActivityEvidence {
  readonly segmentId: string;
  readonly receipt: BroadcastSpeechActivityRunReceipt;
}

export interface CreateBroadcastRefinementCaptionSettlementsInput {
  readonly sourceDurationMs: number;
  readonly selectedLeadPlan: DiscoveredLeadRefinementPlan;
  readonly captionTrack: YouTubeCaptionTrackResult;
  readonly verifiedNoSpeechEvidence:
    readonly BroadcastRefinementCaptionSpeechActivityEvidence[];
}

export interface BroadcastRefinementActiveEvidencePayloadProjection {
  readonly routeEntryFingerprint: string;
  readonly routeKind: BroadcastRefinementEvidenceRouteKind;
  readonly billingClass: BroadcastRefinementEvidenceBillingClass;
  readonly evidencePayload: BroadcastRefinementEvidencePayload;
  readonly settlement: BroadcastRefinementEvidenceSettlementSummary;
}

export interface AppendBroadcastRefinementEvidenceRouteEntryResult {
  readonly ledger: BroadcastRefinementEvidenceLedger;
  readonly routeEntryFingerprint: string;
  readonly appended: boolean;
}

export type BroadcastRefinementEvidenceLedgerErrorCode =
  | "INVALID_LEDGER"
  | "STALE_BINDING"
  | "CAS_MISMATCH"
  | "ROUTE_ENTRY_LIMIT"
  | "UNKNOWN_ROUTE_ENTRY";

export class BroadcastRefinementEvidenceLedgerError extends Error {
  public readonly code: BroadcastRefinementEvidenceLedgerErrorCode;

  public constructor(
    code: BroadcastRefinementEvidenceLedgerErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "BroadcastRefinementEvidenceLedgerError";
    this.code = code;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hasExactKeys(
  value: Readonly<Record<string, unknown>>,
  expectedKeys: readonly string[],
): boolean {
  const actual = Object.keys(value).sort();
  const expected = [...expectedKeys].sort();
  return (
    actual.length === expected.length &&
    actual.every((key, index) => key === expected[index])
  );
}

function isBoundedString(
  value: unknown,
  maximumLength = MAX_FENCE_LENGTH,
): value is string {
  return (
    typeof value === "string" &&
    value.length > 0 &&
    value.length <= maximumLength &&
    value.trim() === value &&
    !/[\p{Cc}\p{Cf}]/u.test(value)
  );
}

function isSha256(value: unknown): value is string {
  return typeof value === "string" && SHA256_PATTERN.test(value);
}

function utf8ByteLength(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

function requireDigest(
  digestAdapter: ContentDigestAdapter | null,
): ContentDigestAdapter {
  if (digestAdapter === null) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "SHA-256 is required for refinement evidence ledger fences.",
    );
  }
  return digestAdapter;
}

function normalizedSelectedLeadPlan(
  value: unknown,
  sourceDurationMs: number,
): DiscoveredLeadRefinementPlan {
  if (
    !isRecord(value) ||
    !hasExactKeys(value, [
      "version",
      "selectedLeadIds",
      "segments",
      "estimatedAsrCostUsd",
    ]) ||
    value.version !== DISCOVERED_LEAD_REFINEMENT_VERSION ||
    !Array.isArray(value.selectedLeadIds) ||
    !Array.isArray(value.segments) ||
    value.selectedLeadIds.length > MAX_CAPTION_DISCOVERED_LEADS_TO_REFINE ||
    value.segments.length > MAX_BROADCAST_TRANSCRIPT_WORKER_CHUNKS ||
    typeof value.estimatedAsrCostUsd !== "number" ||
    !Number.isFinite(value.estimatedAsrCostUsd) ||
    value.estimatedAsrCostUsd < 0 ||
    value.estimatedAsrCostUsd >
      DISCOVERED_LEAD_REFINEMENT_BUDGET_USD + Number.EPSILON
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The selected refinement lead plan is outside its bounded contract.",
    );
  }
  const rawLeadIds: readonly unknown[] = value.selectedLeadIds;
  const selectedLeadIds: string[] = [];
  const selected = new Set<string>();
  for (const leadId of rawLeadIds) {
    if (
      !isBoundedString(leadId, MAX_IDENTIFIER_LENGTH) ||
      selected.has(leadId)
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "Selected refinement lead IDs must be unique bounded strings.",
      );
    }
    selected.add(leadId);
    selectedLeadIds.push(leadId);
  }
  const rawSegments: readonly unknown[] = value.segments;
  const segmentIds = new Set<string>();
  const coveredLeadIds = new Set<string>();
  const segments = rawSegments.map((raw) => {
    if (
      !isRecord(raw) ||
      !hasExactKeys(raw, [
        "segmentId",
        "leadId",
        "sourceStartMs",
        "sourceEndMs",
      ]) ||
      !isBroadcastTranscriptChunkId(raw.segmentId) ||
      segmentIds.has(raw.segmentId) ||
      !isBoundedString(raw.leadId, MAX_IDENTIFIER_LENGTH) ||
      !selected.has(raw.leadId) ||
      !Number.isSafeInteger(raw.sourceStartMs) ||
      !Number.isSafeInteger(raw.sourceEndMs) ||
      (raw.sourceStartMs as number) < 0 ||
      (raw.sourceEndMs as number) <= (raw.sourceStartMs as number) ||
      (raw.sourceEndMs as number) > sourceDurationMs
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "Refinement segments must exactly reference the selected source-bounded leads.",
      );
    }
    segmentIds.add(raw.segmentId);
    coveredLeadIds.add(raw.leadId);
    return {
      segmentId: raw.segmentId,
      leadId: raw.leadId,
      sourceStartMs: raw.sourceStartMs as number,
      sourceEndMs: raw.sourceEndMs as number,
    };
  });
  if (
    selectedLeadIds.some((leadId) => !coveredLeadIds.has(leadId)) ||
    (selectedLeadIds.length === 0 && segments.length !== 0)
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "Every selected refinement lead requires at least one planned segment.",
    );
  }
  return {
    version: DISCOVERED_LEAD_REFINEMENT_VERSION,
    selectedLeadIds,
    segments,
    estimatedAsrCostUsd: value.estimatedAsrCostUsd,
  };
}

async function selectedLeadPlanFingerprint(
  sourceFingerprint: string,
  sourceDurationMs: number,
  plan: DiscoveredLeadRefinementPlan,
  digestAdapter: ContentDigestAdapter,
): Promise<string> {
  return createContentFingerprint(
    [
      SELECTED_LEAD_PLAN_FINGERPRINT_DOMAIN,
      sourceFingerprint,
      String(sourceDurationMs),
      JSON.stringify(plan),
    ],
    digestAdapter,
  );
}

function normalizedCaptionTrack(
  value: unknown,
  sourceDurationMs: number,
): YouTubeCaptionTrackResult {
  if (
    !isRecord(value) ||
    !hasExactKeys(value, [
      "videoId",
      "languageCode",
      "isAutoGenerated",
      "events",
    ]) ||
    typeof value.videoId !== "string" ||
    !YOUTUBE_VIDEO_ID_PATTERN.test(value.videoId) ||
    !isBoundedString(value.languageCode, 35) ||
    typeof value.isAutoGenerated !== "boolean" ||
    !Array.isArray(value.events) ||
    value.events.length === 0 ||
    value.events.length > MAX_YOUTUBE_CAPTION_EVENTS
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The caption event source is invalid or unbounded.",
    );
  }
  const rawEvents: readonly unknown[] = value.events;
  let previousStartMs = -1;
  const events = rawEvents.map((raw) => {
    if (
      !isRecord(raw) ||
      !hasExactKeys(raw, ["startMs", "durationMs", "text"]) ||
      !Number.isSafeInteger(raw.startMs) ||
      !Number.isSafeInteger(raw.durationMs) ||
      (raw.startMs as number) < previousStartMs ||
      (raw.startMs as number) < 0 ||
      (raw.durationMs as number) < 0 ||
      (raw.startMs as number) > sourceDurationMs ||
      (raw.startMs as number) + (raw.durationMs as number) >
        sourceDurationMs ||
      !isBoundedString(raw.text, MAX_YOUTUBE_CAPTION_EVENT_TEXT_LENGTH)
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "Caption events must be chronological and source-bounded.",
      );
    }
    previousStartMs = raw.startMs as number;
    return {
      startMs: raw.startMs as number,
      durationMs: raw.durationMs as number,
      text: raw.text,
    };
  });
  return {
    videoId: value.videoId,
    languageCode: value.languageCode,
    isAutoGenerated: value.isAutoGenerated,
    events,
  };
}

function normalizedCaptionSpeechActivityEvidence(
  value: unknown,
  plan: DiscoveredLeadRefinementPlan,
  sourceDurationMs: number,
): readonly BroadcastRefinementCaptionSpeechActivityEvidence[] {
  if (!Array.isArray(value) || value.length > plan.segments.length) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "Caption no-speech evidence cannot exceed the selected lead plan.",
    );
  }
  const segmentById = new Map(
    plan.segments.map((segment) => [segment.segmentId, segment] as const),
  );
  const planOrdinal = new Map(
    plan.segments.map((segment, ordinal) => [segment.segmentId, ordinal]),
  );
  const seenSegmentIds = new Set<string>();
  return (value as readonly unknown[])
    .map((raw): BroadcastRefinementCaptionSpeechActivityEvidence => {
      if (
        !isRecord(raw) ||
        !hasExactKeys(raw, ["segmentId", "receipt"]) ||
        !isBoundedString(raw.segmentId, MAX_IDENTIFIER_LENGTH) ||
        seenSegmentIds.has(raw.segmentId)
      ) {
        throw new BroadcastRefinementEvidenceLedgerError(
          "INVALID_LEDGER",
          "Caption no-speech evidence must name unique planned cells.",
        );
      }
      const segment = segmentById.get(raw.segmentId);
      const receipt = normalizeBroadcastSpeechActivityRunReceipt(raw.receipt);
      if (
        segment === undefined ||
        receipt === null ||
        receipt.sourceDurationMs !== sourceDurationMs ||
        receipt.sourceStartMs !== segment.sourceStartMs ||
        receipt.sourceEndMs !== segment.sourceEndMs ||
        !receipt.coverage.complete ||
        receipt.cells.length === 0 ||
        !receipt.cells.every(broadcastSpeechActivityCanSkipAsr)
      ) {
        throw new BroadcastRefinementEvidenceLedgerError(
          "INVALID_LEDGER",
          "Caption no-speech evidence is not a complete exact-range VAD receipt.",
        );
      }
      seenSegmentIds.add(raw.segmentId);
      return {
        segmentId: raw.segmentId,
        receipt,
      };
    })
    .sort(
      (left, right) =>
        (planOrdinal.get(left.segmentId) ?? Number.MAX_SAFE_INTEGER) -
        (planOrdinal.get(right.segmentId) ?? Number.MAX_SAFE_INTEGER),
    );
}

/**
 * Derives every caption cell outcome from fenced inputs. Caption text always
 * wins as exact success. A textless cell can be resolved as no-speech only by
 * a complete exact-range VAD receipt; otherwise it remains an explicit gap.
 */
export function createBroadcastRefinementCaptionCellSettlements(
  input: CreateBroadcastRefinementCaptionSettlementsInput,
): readonly BroadcastRefinementCaptionCellSettlement[] {
  const plan = normalizedSelectedLeadPlan(
    input.selectedLeadPlan,
    input.sourceDurationMs,
  );
  const track = normalizedCaptionTrack(
    input.captionTrack,
    input.sourceDurationMs,
  );
  const verifiedNoSpeechEvidence =
    normalizedCaptionSpeechActivityEvidence(
      input.verifiedNoSpeechEvidence,
      plan,
      input.sourceDurationMs,
    );
  const verifiedNoSpeechSegmentIds = new Set(
    verifiedNoSpeechEvidence.map(({ segmentId }) => segmentId),
  );
  const transcriptByRange = new Map(
    createYouTubeCaptionRefinementTranscripts(track, plan).map(
      (transcript) => [
        `${transcript.sourceStartMs}:${transcript.sourceEndMs}`,
        transcript.textKo,
      ],
    ),
  );
  return plan.segments.map((segment) => {
    const textKo = transcriptByRange.get(
      `${segment.sourceStartMs}:${segment.sourceEndMs}`,
    );
    if (textKo !== undefined) {
      return {
        ...segment,
        status: "success" as const,
        textKo,
      };
    }
    if (verifiedNoSpeechSegmentIds.has(segment.segmentId)) {
      return {
        ...segment,
        status: "resolved" as const,
        reason: "no-speech" as const,
      };
    }
    return {
      ...segment,
      status: "gap" as const,
      reason: "outcome-unknown" as const,
    };
  });
}

function normalizedCaptionSettlements(
  value: unknown,
  plan: DiscoveredLeadRefinementPlan,
  verifiedNoSpeechSegmentIds: ReadonlySet<string>,
): readonly BroadcastRefinementCaptionCellSettlement[] {
  if (
    !Array.isArray(value) ||
    value.length > plan.segments.length
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "Caption settlements cannot exceed the selected lead plan.",
    );
  }
  const rawSettlements: readonly unknown[] = value;
  const segmentById = new Map(
    plan.segments.map((segment) => [segment.segmentId, segment]),
  );
  const planOrdinal = new Map(
    plan.segments.map((segment, ordinal) => [segment.segmentId, ordinal]),
  );
  const settledIds = new Set<string>();
  const settlements = rawSettlements.map(
    (raw): BroadcastRefinementCaptionCellSettlement => {
      if (
        !isRecord(raw) ||
        !isBoundedString(raw.segmentId, MAX_IDENTIFIER_LENGTH) ||
        settledIds.has(raw.segmentId)
      ) {
        throw new BroadcastRefinementEvidenceLedgerError(
          "INVALID_LEDGER",
          "Caption settlements must name unique planned cells.",
        );
      }
      const planned = segmentById.get(raw.segmentId);
      const hasExactBase =
        planned !== undefined &&
        raw.leadId === planned.leadId &&
        raw.sourceStartMs === planned.sourceStartMs &&
        raw.sourceEndMs === planned.sourceEndMs;
      if (!hasExactBase || planned === undefined) {
        throw new BroadcastRefinementEvidenceLedgerError(
          "INVALID_LEDGER",
          "Caption evidence does not match its exact selected lead cell.",
        );
      }
      settledIds.add(raw.segmentId);
      const base: BroadcastRefinementEvidenceCellBase = {
        segmentId: planned.segmentId,
        leadId: planned.leadId,
        sourceStartMs: planned.sourceStartMs,
        sourceEndMs: planned.sourceEndMs,
      };
      if (
        raw.status === "success" &&
        hasExactKeys(raw, [
          "segmentId",
          "leadId",
          "sourceStartMs",
          "sourceEndMs",
          "status",
          "textKo",
        ]) &&
        isBoundedString(
          raw.textKo,
          MAX_BROADCAST_TRANSCRIPT_QWEN_TEXT_LENGTH,
        )
      ) {
        return { ...base, status: "success", textKo: raw.textKo };
      }
      if (
        raw.status === "resolved" &&
        hasExactKeys(raw, [
          "segmentId",
          "leadId",
          "sourceStartMs",
          "sourceEndMs",
          "status",
          "reason",
        ]) &&
        raw.reason === "no-speech" &&
        verifiedNoSpeechSegmentIds.has(planned.segmentId)
      ) {
        return { ...base, status: "resolved", reason: "no-speech" };
      }
      if (
        raw.status === "gap" &&
        hasExactKeys(raw, [
          "segmentId",
          "leadId",
          "sourceStartMs",
          "sourceEndMs",
          "status",
          "reason",
        ]) &&
        [
          "in-flight",
          "decode-failed",
          "transcription-failed",
          "rate-limited",
          "outcome-unknown",
        ].includes(typeof raw.reason === "string" ? raw.reason : "")
      ) {
        return {
          ...base,
          status: "gap",
          reason: raw.reason as BroadcastRefinementTranscriptGapReason,
        };
      }
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "Caption settlement outcomes must be success, resolved, or an explicit gap.",
      );
    },
  );
  return settlements.sort(
    (left, right) =>
      (planOrdinal.get(left.segmentId) ?? Number.MAX_SAFE_INTEGER) -
      (planOrdinal.get(right.segmentId) ?? Number.MAX_SAFE_INTEGER),
  );
}

function settlementSummary(
  plannedCellCount: number,
  successCellCount: number,
  resolvedCellCount: number,
  gapCellCount: number,
): BroadcastRefinementEvidenceSettlementSummary {
  const accounted =
    successCellCount + resolvedCellCount + gapCellCount;
  const missingCellCount = plannedCellCount - accounted;
  if (
    !Number.isSafeInteger(plannedCellCount) ||
    [successCellCount, resolvedCellCount, gapCellCount, missingCellCount].some(
      (count) => !Number.isSafeInteger(count) || count < 0,
    )
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "Refinement evidence settlement counts are inconsistent.",
    );
  }
  const settled = gapCellCount === 0 && missingCellCount === 0;
  return {
    plannedCellCount,
    successCellCount,
    resolvedCellCount,
    gapCellCount,
    missingCellCount,
    status: settled ? "settled" : "blocked",
    publicationEligible: settled,
  };
}

function canonicalRefinementCheckpoint(
  value: BroadcastRefinementTranscriptCheckpoint,
): BroadcastRefinementTranscriptCheckpoint {
  const serialized = serializeBroadcastRefinementTranscriptCheckpoint(value);
  const parsed = parseBroadcastRefinementTranscriptCheckpointJson(serialized);
  if (parsed === null) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The ASR refinement checkpoint is not canonical.",
    );
  }
  return parsed;
}

function canonicalProviderCheckpoint(
  value: BroadcastTranscriptProviderReceiptCheckpoint,
): BroadcastTranscriptProviderReceiptCheckpoint {
  const serialized =
    serializeBroadcastTranscriptProviderReceiptCheckpoint(value);
  const parsed =
    parseBroadcastTranscriptProviderReceiptCheckpointJson(serialized);
  if (parsed === null) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The ASR provider receipt checkpoint is not canonical.",
    );
  }
  return parsed;
}

function expectedAsrChunks(plan: DiscoveredLeadRefinementPlan) {
  return [...plan.segments]
    .map((segment) => ({
      chunkId: segment.segmentId,
      sourceStartMs: segment.sourceStartMs,
      sourceEndMs: segment.sourceEndMs,
      kind: "event" as const,
    }))
    .sort(
      (left, right) =>
        left.sourceStartMs - right.sourceStartMs ||
        left.sourceEndMs - right.sourceEndMs ||
        left.chunkId.localeCompare(right.chunkId),
    );
}

function validatedAsrPayload(
  refinementCheckpointValue: BroadcastRefinementTranscriptCheckpoint,
  providerCheckpointValue: BroadcastTranscriptProviderReceiptCheckpoint,
  plan: DiscoveredLeadRefinementPlan,
  sourceFingerprint: string,
  sourceDurationMs: number,
): {
  readonly payload: BroadcastRefinementAsrEvidencePayload;
  readonly evidenceRevision: string;
  readonly settlement: BroadcastRefinementEvidenceSettlementSummary;
} {
  const refinementCheckpoint = canonicalRefinementCheckpoint(
    refinementCheckpointValue,
  );
  const providerReceiptCheckpoint = canonicalProviderCheckpoint(
    providerCheckpointValue,
  );
  const expectedChunks = expectedAsrChunks(plan);
  const expectedProviderCells = expectedChunks.map(
    ({ chunkId, sourceStartMs, sourceEndMs }) => ({
      chunkId,
      sourceStartMs,
      sourceEndMs,
    }),
  );
  if (
    JSON.stringify(refinementCheckpoint.plannedChunks) !==
      JSON.stringify(expectedChunks) ||
    JSON.stringify(providerReceiptCheckpoint.plannedCells) !==
      JSON.stringify(expectedProviderCells) ||
    providerReceiptCheckpoint.sourceFingerprint !== sourceFingerprint ||
    providerReceiptCheckpoint.sourceDurationMs !== sourceDurationMs
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "STALE_BINDING",
      "ASR checkpoints do not match the current source and selected lead plan.",
    );
  }
  const receiptByChunkId = new Map(
    providerReceiptCheckpoint.receipts.map((entry) => [
      entry.chunkId,
      entry,
    ]),
  );
  if (
    receiptByChunkId.size !==
    refinementCheckpoint.successfulFragments.length
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "Every successful ASR cell requires one exact provider receipt.",
    );
  }
  for (const fragment of refinementCheckpoint.successfulFragments) {
    const providerEntry = receiptByChunkId.get(fragment.chunkId);
    if (
      providerEntry === undefined ||
      providerEntry.sourceStartMs !== fragment.result.sourceStartMs ||
      providerEntry.sourceEndMs !== fragment.result.sourceEndMs ||
      JSON.stringify(providerEntry.receipt) !==
        JSON.stringify(fragment.result.providerReceipt)
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "ASR evidence and its provider receipt checkpoint disagree.",
      );
    }
  }
  for (const abstention of refinementCheckpoint.abstentions) {
    if (
      abstention.reason === "no-speech" &&
      (abstention.speechActivityReceipt === null ||
        abstention.speechActivityReceipt.sourceDurationMs !==
          sourceDurationMs)
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "ASR no-speech evidence requires one exact source-bound VAD receipt.",
      );
    }
  }
  const settlement = settlementSummary(
    expectedChunks.length,
    refinementCheckpoint.successfulFragments.length,
    refinementCheckpoint.abstentions.length,
    refinementCheckpoint.gaps.length,
  );
  if (
    settlement.publicationEligible !==
    broadcastRefinementTranscriptCheckpointCanComplete(
      refinementCheckpoint,
    )
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "ASR settlement disagrees with its refinement checkpoint.",
    );
  }
  return {
    payload: {
      kind: "asr-refinement-checkpoints",
      refinementCheckpoint,
      providerReceiptCheckpoint,
    },
    evidenceRevision:
      broadcastTranscriptProviderReceiptCheckpointModelRevision(
        providerReceiptCheckpoint,
      ),
    settlement,
  };
}

async function providerCheckpointSignature(
  checkpoint: BroadcastTranscriptProviderReceiptCheckpoint,
  digestAdapter: ContentDigestAdapter,
): Promise<string> {
  return createContentFingerprint(
    [
      PROVIDER_CHECKPOINT_SIGNATURE_DOMAIN,
      serializeBroadcastTranscriptProviderReceiptCheckpoint(checkpoint),
    ],
    digestAdapter,
  );
}

async function captionEventSourceFence(
  sourceFingerprint: string,
  sourceDurationMs: number,
  selectedLeadPlanFingerprintValue: string,
  captionRevision: string,
  track: YouTubeCaptionTrackResult,
  digestAdapter: ContentDigestAdapter,
): Promise<string> {
  return createContentFingerprint(
    [
      CAPTION_EVENT_SOURCE_FENCE_DOMAIN,
      sourceFingerprint,
      String(sourceDurationMs),
      selectedLeadPlanFingerprintValue,
      captionRevision,
      JSON.stringify(track),
    ],
    digestAdapter,
  );
}

async function routeEntryFingerprint(
  entry: Omit<
    BroadcastRefinementEvidenceRouteEntry,
    "entryFingerprint" | "ordinal"
  >,
  digestAdapter: ContentDigestAdapter,
): Promise<string> {
  return createContentFingerprint(
    [ROUTE_ENTRY_FINGERPRINT_DOMAIN, JSON.stringify(entry)],
    digestAdapter,
  );
}

function routeEntryFingerprintPayload(
  entry: Omit<BroadcastRefinementEvidenceRouteEntry, "entryFingerprint">,
): Omit<
  BroadcastRefinementEvidenceRouteEntry,
  "entryFingerprint" | "ordinal"
> {
  return {
    routeKind: entry.routeKind,
    billingClass: entry.billingClass,
    sourceFingerprint: entry.sourceFingerprint,
    sourceDurationMs: entry.sourceDurationMs,
    selectedLeadPlanFingerprint: entry.selectedLeadPlanFingerprint,
    evidenceRevision: entry.evidenceRevision,
    captionEventSourceFence: entry.captionEventSourceFence,
    providerReceiptCheckpointSignature:
      entry.providerReceiptCheckpointSignature,
    captionSource: entry.captionSource,
    evidencePayload: entry.evidencePayload,
    settlement: entry.settlement,
  };
}

async function activeProjectionFingerprint(
  sourceFingerprint: string,
  sourceDurationMs: number,
  selectedLeadPlanFingerprintValue: string,
  entryFingerprint: string,
  digestAdapter: ContentDigestAdapter,
): Promise<string> {
  return createContentFingerprint(
    [
      ACTIVE_ROUTE_PROJECTION_FINGERPRINT_DOMAIN,
      sourceFingerprint,
      String(sourceDurationMs),
      selectedLeadPlanFingerprintValue,
      entryFingerprint,
    ],
    digestAdapter,
  );
}

async function ledgerFingerprint(
  ledger: Omit<BroadcastRefinementEvidenceLedger, "ledgerFingerprint">,
  digestAdapter: ContentDigestAdapter,
): Promise<string> {
  return createContentFingerprint(
    [LEDGER_FINGERPRINT_DOMAIN, JSON.stringify(ledger)],
    digestAdapter,
  );
}

async function buildRouteEntry(
  ordinal: number,
  binding: {
    readonly sourceFingerprint: string;
    readonly sourceDurationMs: number;
    readonly selectedLeadPlan: DiscoveredLeadRefinementPlan;
    readonly selectedLeadPlanFingerprint: string;
  },
  input: AppendBroadcastRefinementEvidenceInput,
  digestAdapter: ContentDigestAdapter,
): Promise<BroadcastRefinementEvidenceRouteEntry> {
  let withoutFingerprint: Omit<
    BroadcastRefinementEvidenceRouteEntry,
    "entryFingerprint"
  >;
  if (input.routeKind === "youtube-caption") {
    if (!isBoundedString(input.captionRevision, 512)) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "The caption revision is invalid.",
      );
    }
    const track = normalizedCaptionTrack(
      input.captionTrack,
      binding.sourceDurationMs,
    );
    const verifiedNoSpeechEvidence =
      normalizedCaptionSpeechActivityEvidence(
        input.verifiedNoSpeechEvidence,
        binding.selectedLeadPlan,
        binding.sourceDurationMs,
      );
    const settlements = createBroadcastRefinementCaptionCellSettlements({
      sourceDurationMs: binding.sourceDurationMs,
      selectedLeadPlan: binding.selectedLeadPlan,
      captionTrack: track,
      verifiedNoSpeechEvidence,
    });
    const canonicalSettlements = normalizedCaptionSettlements(
      settlements,
      binding.selectedLeadPlan,
      new Set(verifiedNoSpeechEvidence.map(({ segmentId }) => segmentId)),
    );
    const expectedTranscriptByRange = new Map(
      createYouTubeCaptionRefinementTranscripts(
        track,
        binding.selectedLeadPlan,
      ).map((transcript) => [
        `${transcript.sourceStartMs}:${transcript.sourceEndMs}`,
        transcript.textKo,
      ]),
    );
    if (
      canonicalSettlements.some(
        (settlement) =>
          settlement.status === "success" &&
          expectedTranscriptByRange.get(
            `${settlement.sourceStartMs}:${settlement.sourceEndMs}`,
          ) !== settlement.textKo,
      )
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "Caption success evidence must exactly match its fenced event source.",
      );
    }
    const successCount = canonicalSettlements.filter(
      ({ status }) => status === "success",
    ).length;
    const resolvedCount = canonicalSettlements.filter(
      ({ status }) => status === "resolved",
    ).length;
    const gapCount = canonicalSettlements.filter(
      ({ status }) => status === "gap",
    ).length;
    withoutFingerprint = {
      ordinal,
      routeKind: "youtube-caption",
      billingClass: "free",
      sourceFingerprint: binding.sourceFingerprint,
      sourceDurationMs: binding.sourceDurationMs,
      selectedLeadPlanFingerprint: binding.selectedLeadPlanFingerprint,
      evidenceRevision: input.captionRevision,
      captionEventSourceFence: await captionEventSourceFence(
        binding.sourceFingerprint,
        binding.sourceDurationMs,
        binding.selectedLeadPlanFingerprint,
        input.captionRevision,
        track,
        digestAdapter,
      ),
      providerReceiptCheckpointSignature: null,
      captionSource: {
        videoId: track.videoId,
        languageCode: track.languageCode,
        isAutoGenerated: track.isAutoGenerated,
      },
      evidencePayload: {
        kind: "youtube-caption-cells",
        settlements: canonicalSettlements,
        verifiedNoSpeechEvidence,
      },
      settlement: settlementSummary(
        binding.selectedLeadPlan.segments.length,
        successCount,
        resolvedCount,
        gapCount,
      ),
    };
  } else {
    const asr = validatedAsrPayload(
      input.refinementCheckpoint,
      input.providerReceiptCheckpoint,
      binding.selectedLeadPlan,
      binding.sourceFingerprint,
      binding.sourceDurationMs,
    );
    withoutFingerprint = {
      ordinal,
      routeKind: "asr",
      billingClass: input.billingClass,
      sourceFingerprint: binding.sourceFingerprint,
      sourceDurationMs: binding.sourceDurationMs,
      selectedLeadPlanFingerprint: binding.selectedLeadPlanFingerprint,
      evidenceRevision: asr.evidenceRevision,
      captionEventSourceFence: null,
      providerReceiptCheckpointSignature: await providerCheckpointSignature(
        asr.payload.providerReceiptCheckpoint,
        digestAdapter,
      ),
      captionSource: null,
      evidencePayload: asr.payload,
      settlement: asr.settlement,
    };
  }
  return {
    entryFingerprint: await routeEntryFingerprint(
      routeEntryFingerprintPayload(withoutFingerprint),
      digestAdapter,
    ),
    ...withoutFingerprint,
  };
}

async function normalizedStoredRouteEntry(
  value: unknown,
  ordinal: number,
  binding: {
    readonly sourceFingerprint: string;
    readonly sourceDurationMs: number;
    readonly selectedLeadPlan: DiscoveredLeadRefinementPlan;
    readonly selectedLeadPlanFingerprint: string;
  },
  digestAdapter: ContentDigestAdapter,
): Promise<BroadcastRefinementEvidenceRouteEntry> {
  if (
    !isRecord(value) ||
    !hasExactKeys(value, [
      "entryFingerprint",
      "ordinal",
      "routeKind",
      "billingClass",
      "sourceFingerprint",
      "sourceDurationMs",
      "selectedLeadPlanFingerprint",
      "evidenceRevision",
      "captionEventSourceFence",
      "providerReceiptCheckpointSignature",
      "captionSource",
      "evidencePayload",
      "settlement",
    ]) ||
    !isSha256(value.entryFingerprint) ||
    value.ordinal !== ordinal ||
    value.sourceFingerprint !== binding.sourceFingerprint ||
    value.sourceDurationMs !== binding.sourceDurationMs ||
    value.selectedLeadPlanFingerprint !==
      binding.selectedLeadPlanFingerprint ||
    !isBoundedString(value.evidenceRevision, 512) ||
    !isRecord(value.evidencePayload) ||
    !isRecord(value.settlement)
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "A refinement evidence route entry has an invalid source or plan fence.",
    );
  }
  let canonical: BroadcastRefinementEvidenceRouteEntry;
  if (value.routeKind === "youtube-caption") {
    if (
      value.billingClass !== "free" ||
      !isSha256(value.captionEventSourceFence) ||
      value.providerReceiptCheckpointSignature !== null ||
      !isRecord(value.captionSource) ||
      !hasExactKeys(value.captionSource, [
        "videoId",
        "languageCode",
        "isAutoGenerated",
      ]) ||
      typeof value.captionSource.videoId !== "string" ||
      !YOUTUBE_VIDEO_ID_PATTERN.test(value.captionSource.videoId) ||
      !isBoundedString(value.captionSource.languageCode, 35) ||
      typeof value.captionSource.isAutoGenerated !== "boolean" ||
      !hasExactKeys(value.evidencePayload, [
        "kind",
        "settlements",
        "verifiedNoSpeechEvidence",
      ]) ||
      value.evidencePayload.kind !== "youtube-caption-cells"
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "A caption route entry has an invalid event-source fence.",
      );
    }
    const verifiedNoSpeechEvidence =
      normalizedCaptionSpeechActivityEvidence(
        value.evidencePayload.verifiedNoSpeechEvidence,
        binding.selectedLeadPlan,
        binding.sourceDurationMs,
      );
    const settlements = normalizedCaptionSettlements(
      value.evidencePayload.settlements,
      binding.selectedLeadPlan,
      new Set(verifiedNoSpeechEvidence.map(({ segmentId }) => segmentId)),
    );
    const summary = settlementSummary(
      binding.selectedLeadPlan.segments.length,
      settlements.filter(({ status }) => status === "success").length,
      settlements.filter(({ status }) => status === "resolved").length,
      settlements.filter(({ status }) => status === "gap").length,
    );
    canonical = {
      entryFingerprint: value.entryFingerprint,
      ordinal,
      routeKind: "youtube-caption",
      billingClass: "free",
      sourceFingerprint: binding.sourceFingerprint,
      sourceDurationMs: binding.sourceDurationMs,
      selectedLeadPlanFingerprint: binding.selectedLeadPlanFingerprint,
      evidenceRevision: value.evidenceRevision,
      captionEventSourceFence: value.captionEventSourceFence,
      providerReceiptCheckpointSignature: null,
      captionSource: {
        videoId: value.captionSource.videoId,
        languageCode: value.captionSource.languageCode,
        isAutoGenerated: value.captionSource.isAutoGenerated,
      },
      evidencePayload: {
        kind: "youtube-caption-cells",
        settlements,
        verifiedNoSpeechEvidence,
      },
      settlement: summary,
    };
  } else if (value.routeKind === "asr") {
    if (
      (value.billingClass !== "free" && value.billingClass !== "paid") ||
      value.captionEventSourceFence !== null ||
      value.captionSource !== null ||
      !isSha256(value.providerReceiptCheckpointSignature) ||
      !hasExactKeys(value.evidencePayload, [
        "kind",
        "refinementCheckpoint",
        "providerReceiptCheckpoint",
      ]) ||
      value.evidencePayload.kind !== "asr-refinement-checkpoints"
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "An ASR route entry has an invalid provider checkpoint fence.",
      );
    }
    const asr = validatedAsrPayload(
      value.evidencePayload
        .refinementCheckpoint as BroadcastRefinementTranscriptCheckpoint,
      value.evidencePayload
        .providerReceiptCheckpoint as BroadcastTranscriptProviderReceiptCheckpoint,
      binding.selectedLeadPlan,
      binding.sourceFingerprint,
      binding.sourceDurationMs,
    );
    const expectedProviderSignature = await providerCheckpointSignature(
      asr.payload.providerReceiptCheckpoint,
      digestAdapter,
    );
    if (
      value.evidenceRevision !== asr.evidenceRevision ||
      value.providerReceiptCheckpointSignature !== expectedProviderSignature
    ) {
      throw new BroadcastRefinementEvidenceLedgerError(
        "INVALID_LEDGER",
        "The ASR route revision or provider checkpoint signature is stale.",
      );
    }
    canonical = {
      entryFingerprint: value.entryFingerprint,
      ordinal,
      routeKind: "asr",
      billingClass: value.billingClass,
      sourceFingerprint: binding.sourceFingerprint,
      sourceDurationMs: binding.sourceDurationMs,
      selectedLeadPlanFingerprint: binding.selectedLeadPlanFingerprint,
      evidenceRevision: asr.evidenceRevision,
      captionEventSourceFence: null,
      providerReceiptCheckpointSignature: expectedProviderSignature,
      captionSource: null,
      evidencePayload: asr.payload,
      settlement: asr.settlement,
    };
  } else {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The refinement evidence route kind is unknown.",
    );
  }
  if (JSON.stringify(canonical.settlement) !== JSON.stringify(value.settlement)) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The stored route settlement summary is not derived from its cells.",
    );
  }
  if (
    canonical.entryFingerprint !==
    (await routeEntryFingerprint(
      routeEntryFingerprintPayload(canonical),
      digestAdapter,
    ))
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The refinement evidence route entry fingerprint is invalid.",
    );
  }
  return canonical;
}

async function normalizedLedger(
  value: unknown,
  digestAdapter: ContentDigestAdapter,
): Promise<BroadcastRefinementEvidenceLedger> {
  if (
    !isRecord(value) ||
    !hasExactKeys(value, [
      "schemaVersion",
      "generation",
      "sourceFingerprint",
      "sourceDurationMs",
      "selectedLeadPlan",
      "selectedLeadPlanFingerprint",
      "activeRouteEntryFingerprint",
      "activeRouteProjectionFingerprint",
      "routeEntries",
      "ledgerFingerprint",
    ]) ||
    value.schemaVersion !==
      BROADCAST_REFINEMENT_EVIDENCE_LEDGER_SCHEMA_VERSION ||
    !Number.isSafeInteger(value.generation) ||
    (value.generation as number) < 0 ||
    (value.generation as number) > MAX_GENERATION ||
    !isBoundedString(value.sourceFingerprint) ||
    !Number.isSafeInteger(value.sourceDurationMs) ||
    (value.sourceDurationMs as number) <= 0 ||
    (value.sourceDurationMs as number) >
      MAX_BROADCAST_CONTEXT_SOURCE_DURATION_MS ||
    !isSha256(value.selectedLeadPlanFingerprint) ||
    !(value.activeRouteEntryFingerprint === null ||
      isSha256(value.activeRouteEntryFingerprint)) ||
    !(value.activeRouteProjectionFingerprint === null ||
      isSha256(value.activeRouteProjectionFingerprint)) ||
    !Array.isArray(value.routeEntries) ||
    value.routeEntries.length >
      MAX_BROADCAST_REFINEMENT_EVIDENCE_ROUTE_ENTRIES ||
    !isSha256(value.ledgerFingerprint)
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The refinement evidence ledger failed its exact outer contract.",
    );
  }
  const sourceDurationMs = value.sourceDurationMs as number;
  const selectedLeadPlan = normalizedSelectedLeadPlan(
    value.selectedLeadPlan,
    sourceDurationMs,
  );
  const expectedPlanFingerprint = await selectedLeadPlanFingerprint(
    value.sourceFingerprint,
    sourceDurationMs,
    selectedLeadPlan,
    digestAdapter,
  );
  if (value.selectedLeadPlanFingerprint !== expectedPlanFingerprint) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The selected lead plan fingerprint is invalid.",
    );
  }
  const rawEntries: readonly unknown[] = value.routeEntries;
  const binding = {
    sourceFingerprint: value.sourceFingerprint,
    sourceDurationMs,
    selectedLeadPlan,
    selectedLeadPlanFingerprint: expectedPlanFingerprint,
  };
  const routeEntries: BroadcastRefinementEvidenceRouteEntry[] = [];
  for (const [ordinal, raw] of rawEntries.entries()) {
    routeEntries.push(
      await normalizedStoredRouteEntry(
        raw,
        ordinal,
        binding,
        digestAdapter,
      ),
    );
  }
  if (
    new Set(routeEntries.map(({ entryFingerprint }) => entryFingerprint))
      .size !== routeEntries.length
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "A refinement evidence ledger cannot repeat a route entry.",
    );
  }
  const activeEntry =
    value.activeRouteEntryFingerprint === null
      ? null
      : routeEntries.find(
          ({ entryFingerprint }) =>
            entryFingerprint === value.activeRouteEntryFingerprint,
        ) ?? null;
  if (
    (value.activeRouteEntryFingerprint === null) !== (activeEntry === null)
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The active refinement route does not exist in this ledger.",
    );
  }
  const expectedActiveProjectionFingerprint =
    activeEntry === null
      ? null
      : await activeProjectionFingerprint(
          binding.sourceFingerprint,
          binding.sourceDurationMs,
          binding.selectedLeadPlanFingerprint,
          activeEntry.entryFingerprint,
          digestAdapter,
        );
  if (
    value.activeRouteProjectionFingerprint !==
    expectedActiveProjectionFingerprint
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The active refinement route projection fingerprint is invalid.",
    );
  }
  const withoutFingerprint: Omit<
    BroadcastRefinementEvidenceLedger,
    "ledgerFingerprint"
  > = {
    schemaVersion:
      BROADCAST_REFINEMENT_EVIDENCE_LEDGER_SCHEMA_VERSION,
    generation: value.generation as number,
    sourceFingerprint: binding.sourceFingerprint,
    sourceDurationMs: binding.sourceDurationMs,
    selectedLeadPlan: binding.selectedLeadPlan,
    selectedLeadPlanFingerprint: binding.selectedLeadPlanFingerprint,
    activeRouteEntryFingerprint:
      activeEntry?.entryFingerprint ?? null,
    activeRouteProjectionFingerprint:
      expectedActiveProjectionFingerprint,
    routeEntries,
  };
  const expectedLedgerFingerprint = await ledgerFingerprint(
    withoutFingerprint,
    digestAdapter,
  );
  if (value.ledgerFingerprint !== expectedLedgerFingerprint) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The refinement evidence ledger fingerprint is invalid.",
    );
  }
  return {
    ...withoutFingerprint,
    ledgerFingerprint: expectedLedgerFingerprint,
  };
}

async function builtLedger(
  input: Omit<BroadcastRefinementEvidenceLedger, "ledgerFingerprint">,
  digestAdapter: ContentDigestAdapter,
): Promise<BroadcastRefinementEvidenceLedger> {
  const withoutFingerprint: Omit<
    BroadcastRefinementEvidenceLedger,
    "ledgerFingerprint"
  > = {
    schemaVersion: input.schemaVersion,
    generation: input.generation,
    sourceFingerprint: input.sourceFingerprint,
    sourceDurationMs: input.sourceDurationMs,
    selectedLeadPlan: input.selectedLeadPlan,
    selectedLeadPlanFingerprint: input.selectedLeadPlanFingerprint,
    activeRouteEntryFingerprint: input.activeRouteEntryFingerprint,
    activeRouteProjectionFingerprint:
      input.activeRouteProjectionFingerprint,
    routeEntries: input.routeEntries,
  };
  const result = {
    ...withoutFingerprint,
    ledgerFingerprint: await ledgerFingerprint(
      withoutFingerprint,
      digestAdapter,
    ),
  };
  const normalized = await normalizedLedger(result, digestAdapter);
  if (
    utf8ByteLength(JSON.stringify(normalized)) >
    MAX_BROADCAST_REFINEMENT_EVIDENCE_LEDGER_BYTES
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "ROUTE_ENTRY_LIMIT",
      "The refinement evidence ledger exceeds its byte limit.",
    );
  }
  return normalized;
}

async function currentLedgerForCas(
  ledger: BroadcastRefinementEvidenceLedger,
  expectedLedgerFingerprint: string,
  digestAdapter: ContentDigestAdapter,
): Promise<BroadcastRefinementEvidenceLedger> {
  const current = await normalizedLedger(ledger, digestAdapter);
  if (
    !isSha256(expectedLedgerFingerprint) ||
    current.ledgerFingerprint !== expectedLedgerFingerprint
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "CAS_MISMATCH",
      "The refinement evidence ledger changed before this update.",
    );
  }
  return current;
}

async function assertInputBinding(
  ledger: BroadcastRefinementEvidenceLedger,
  input: BroadcastRefinementEvidenceLedgerBinding,
  digestAdapter: ContentDigestAdapter,
): Promise<void> {
  let inputPlan: DiscoveredLeadRefinementPlan;
  try {
    inputPlan = normalizedSelectedLeadPlan(
      input.selectedLeadPlan,
      input.sourceDurationMs,
    );
  } catch {
    throw new BroadcastRefinementEvidenceLedgerError(
      "STALE_BINDING",
      "The proposed route does not carry the current selected lead plan.",
    );
  }
  const inputPlanFingerprint = await selectedLeadPlanFingerprint(
    input.sourceFingerprint,
    input.sourceDurationMs,
    inputPlan,
    digestAdapter,
  );
  if (
    input.sourceFingerprint !== ledger.sourceFingerprint ||
    input.sourceDurationMs !== ledger.sourceDurationMs ||
    inputPlanFingerprint !== ledger.selectedLeadPlanFingerprint ||
    JSON.stringify(inputPlan) !== JSON.stringify(ledger.selectedLeadPlan)
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "STALE_BINDING",
      "The proposed route belongs to a stale source or selected lead plan.",
    );
  }
}

export async function createBroadcastRefinementEvidenceLedger(
  input: BroadcastRefinementEvidenceLedgerBinding,
  digestAdapter: ContentDigestAdapter | null = globalThis.crypto?.subtle ??
    null,
): Promise<BroadcastRefinementEvidenceLedger> {
  const digest = requireDigest(digestAdapter);
  if (
    !isBoundedString(input.sourceFingerprint) ||
    !Number.isSafeInteger(input.sourceDurationMs) ||
    input.sourceDurationMs <= 0 ||
    input.sourceDurationMs > MAX_BROADCAST_CONTEXT_SOURCE_DURATION_MS
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "INVALID_LEDGER",
      "The refinement evidence ledger requires an exact bounded source.",
    );
  }
  const selectedLeadPlan = normalizedSelectedLeadPlan(
    input.selectedLeadPlan,
    input.sourceDurationMs,
  );
  const planFingerprint = await selectedLeadPlanFingerprint(
    input.sourceFingerprint,
    input.sourceDurationMs,
    selectedLeadPlan,
    digest,
  );
  return builtLedger(
    {
      schemaVersion:
        BROADCAST_REFINEMENT_EVIDENCE_LEDGER_SCHEMA_VERSION,
      generation: 0,
      sourceFingerprint: input.sourceFingerprint,
      sourceDurationMs: input.sourceDurationMs,
      selectedLeadPlan,
      selectedLeadPlanFingerprint: planFingerprint,
      activeRouteEntryFingerprint: null,
      activeRouteProjectionFingerprint: null,
      routeEntries: [],
    },
    digest,
  );
}

/**
 * Append-only route update. Exact duplicate entries are idempotent; a changed
 * evidence payload becomes a new entry, preserving every previous paid/free
 * route for later reactivation.
 */
export async function appendBroadcastRefinementEvidenceRouteEntry(
  ledger: BroadcastRefinementEvidenceLedger,
  expectedLedgerFingerprint: string,
  input: AppendBroadcastRefinementEvidenceInput,
  digestAdapter: ContentDigestAdapter | null = globalThis.crypto?.subtle ??
    null,
): Promise<AppendBroadcastRefinementEvidenceRouteEntryResult> {
  const digest = requireDigest(digestAdapter);
  const current = await currentLedgerForCas(
    ledger,
    expectedLedgerFingerprint,
    digest,
  );
  await assertInputBinding(current, input, digest);
  const routeEntry = await buildRouteEntry(
    current.routeEntries.length,
    {
      sourceFingerprint: current.sourceFingerprint,
      sourceDurationMs: current.sourceDurationMs,
      selectedLeadPlan: current.selectedLeadPlan,
      selectedLeadPlanFingerprint: current.selectedLeadPlanFingerprint,
    },
    input,
    digest,
  );
  const duplicate = current.routeEntries.find(
    ({ entryFingerprint }) =>
      entryFingerprint === routeEntry.entryFingerprint,
  );
  if (duplicate !== undefined) {
    return {
      ledger: current,
      routeEntryFingerprint: duplicate.entryFingerprint,
      appended: false,
    };
  }
  if (
    current.routeEntries.length >=
    MAX_BROADCAST_REFINEMENT_EVIDENCE_ROUTE_ENTRIES
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "ROUTE_ENTRY_LIMIT",
      "The refinement evidence route history is full.",
    );
  }
  const nextLedger = await builtLedger(
    {
      ...current,
      generation: current.generation + 1,
      routeEntries: [...current.routeEntries, routeEntry],
    },
    digest,
  );
  return {
    ledger: nextLedger,
    routeEntryFingerprint: routeEntry.entryFingerprint,
    appended: true,
  };
}

/**
 * Changes only the active pointer and projection cache key. Route entries are
 * never deleted or relabeled by activation.
 */
export async function activateBroadcastRefinementEvidenceRoute(
  ledger: BroadcastRefinementEvidenceLedger,
  expectedLedgerFingerprint: string,
  routeEntryFingerprint: string,
  digestAdapter: ContentDigestAdapter | null = globalThis.crypto?.subtle ??
    null,
): Promise<BroadcastRefinementEvidenceLedger> {
  const digest = requireDigest(digestAdapter);
  const current = await currentLedgerForCas(
    ledger,
    expectedLedgerFingerprint,
    digest,
  );
  const entry = current.routeEntries.find(
    ({ entryFingerprint }) =>
      entryFingerprint === routeEntryFingerprint,
  );
  if (entry === undefined) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "UNKNOWN_ROUTE_ENTRY",
      "The requested refinement evidence route is not in this ledger.",
    );
  }
  if (current.activeRouteEntryFingerprint === entry.entryFingerprint) {
    return current;
  }
  return builtLedger(
    {
      ...current,
      generation: current.generation + 1,
      activeRouteEntryFingerprint: entry.entryFingerprint,
      activeRouteProjectionFingerprint: await activeProjectionFingerprint(
        current.sourceFingerprint,
        current.sourceDurationMs,
        current.selectedLeadPlanFingerprint,
        entry.entryFingerprint,
        digest,
      ),
    },
    digest,
  );
}

export function projectBroadcastRefinementActiveEvidenceRoute(
  ledger: BroadcastRefinementEvidenceLedger,
): BroadcastRefinementActiveRouteProjection | null {
  if (
    ledger.activeRouteEntryFingerprint === null ||
    ledger.activeRouteProjectionFingerprint === null
  ) {
    return null;
  }
  const entry = ledger.routeEntries.find(
    ({ entryFingerprint }) =>
      entryFingerprint === ledger.activeRouteEntryFingerprint,
  );
  if (entry === undefined) return null;
  return {
    projectionFingerprint: ledger.activeRouteProjectionFingerprint,
    routeEntryFingerprint: entry.entryFingerprint,
    routeKind: entry.routeKind,
    billingClass: entry.billingClass,
    evidenceRevision: entry.evidenceRevision,
    publicationEligible: entry.settlement.publicationEligible,
  };
}

export function getBroadcastRefinementActiveEvidencePayload(
  ledger: BroadcastRefinementEvidenceLedger,
): BroadcastRefinementActiveEvidencePayloadProjection | null {
  if (
    ledger.activeRouteEntryFingerprint === null ||
    ledger.activeRouteProjectionFingerprint === null
  ) {
    return null;
  }
  const entry = ledger.routeEntries.find(
    ({ entryFingerprint }) =>
      entryFingerprint === ledger.activeRouteEntryFingerprint,
  );
  if (entry === undefined) return null;
  return {
    routeEntryFingerprint: entry.entryFingerprint,
    routeKind: entry.routeKind,
    billingClass: entry.billingClass,
    evidencePayload: entry.evidencePayload,
    settlement: entry.settlement,
  };
}

export function broadcastRefinementEvidenceLedgerCanPublish(
  ledger: BroadcastRefinementEvidenceLedger,
): boolean {
  return (
    projectBroadcastRefinementActiveEvidenceRoute(ledger)
      ?.publicationEligible === true
  );
}

export async function serializeBroadcastRefinementEvidenceLedger(
  ledger: BroadcastRefinementEvidenceLedger,
  digestAdapter: ContentDigestAdapter | null = globalThis.crypto?.subtle ??
    null,
): Promise<string> {
  const normalized = await normalizedLedger(
    ledger,
    requireDigest(digestAdapter),
  );
  const serialized = JSON.stringify(normalized);
  if (
    utf8ByteLength(serialized) >
    MAX_BROADCAST_REFINEMENT_EVIDENCE_LEDGER_BYTES
  ) {
    throw new BroadcastRefinementEvidenceLedgerError(
      "ROUTE_ENTRY_LIMIT",
      "The refinement evidence ledger exceeds its byte limit.",
    );
  }
  return serialized;
}

export async function parseBroadcastRefinementEvidenceLedgerJson(
  serialized: string,
  digestAdapter: ContentDigestAdapter | null = globalThis.crypto?.subtle ??
    null,
): Promise<BroadcastRefinementEvidenceLedger | null> {
  if (
    typeof serialized !== "string" ||
    serialized.length === 0 ||
    utf8ByteLength(serialized) >
      MAX_BROADCAST_REFINEMENT_EVIDENCE_LEDGER_BYTES
  ) {
    return null;
  }
  try {
    const parsed: unknown = JSON.parse(serialized);
    const normalized = await normalizedLedger(
      parsed,
      requireDigest(digestAdapter),
    );
    return JSON.stringify(normalized) === serialized ? normalized : null;
  } catch {
    return null;
  }
}
