import { describe, expect, it } from "vitest";

import {
  activateBroadcastRefinementEvidenceRoute,
  appendBroadcastRefinementEvidenceRouteEntry,
  broadcastRefinementEvidenceLedgerCanPublish,
  createBroadcastRefinementCaptionCellSettlements,
  createBroadcastRefinementEvidenceLedger,
  getBroadcastRefinementActiveEvidencePayload,
  parseBroadcastRefinementEvidenceLedgerJson,
  projectBroadcastRefinementActiveEvidenceRoute,
  serializeBroadcastRefinementEvidenceLedger,
  BroadcastRefinementEvidenceLedgerError,
  type AppendBroadcastRefinementCaptionEvidenceInput,
  type BroadcastRefinementCaptionSpeechActivityEvidence,
  type BroadcastRefinementEvidenceLedger,
} from "./broadcastRefinementEvidenceLedger";
import {
  BROADCAST_SPEECH_ACTIVITY_NO_SPEAKER_CLASS_ID,
  BROADCAST_SPEECH_ACTIVITY_OUTPUT_CLASS_COUNT,
  createBroadcastSpeechActivityPlan,
  createBroadcastSpeechActivityRunReceipt,
  postprocessBroadcastSpeechActivityLogits,
} from "./broadcastSpeechActivity";
import {
  createBroadcastRefinementTranscriptCheckpoint,
  recordBroadcastRefinementTranscriptAbstention,
  recordBroadcastRefinementTranscriptGap,
  recordBroadcastRefinementTranscriptSuccess,
  type BroadcastRefinementTranscriptCheckpoint,
} from "./broadcastRefinementTranscriptCheckpoint";
import {
  DISCOVERED_LEAD_REFINEMENT_VERSION,
  type DiscoveredLeadRefinementPlan,
} from "./discoveredLeadRefinement";
import {
  createBroadcastTranscriptProviderReceiptCheckpoint,
  recordBroadcastTranscriptProviderReceipt,
  type BroadcastTranscriptProviderReceiptCheckpoint,
} from "./broadcastTranscriptProviderReceiptCheckpoint";
import {
  BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_ID,
  BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_REVISION,
} from "./broadcastTranscriptQwen";
import {
  createBroadcastTranscriptProviderReceipt,
  createBroadcastTranscriptRouteSelection,
  type BroadcastTranscriptRouteManifest,
  type BroadcastTranscriptRouteSelection,
  type BroadcastTranscriptVerifiedResult,
} from "./broadcastTranscriptRouteManifest";
import {
  YOUTUBE_CAPTION_MODEL_REVISION,
  type YouTubeCaptionTrackResult,
} from "./youtubeCaptionTrack";

const SOURCE_FINGERPRINT = `sha256:${"a".repeat(64)}`;
const SOURCE_DURATION_MS = 90_000;

const selectedLeadPlan: DiscoveredLeadRefinementPlan = {
  version: DISCOVERED_LEAD_REFINEMENT_VERSION,
  selectedLeadIds: ["lead-food"],
  segments: [
    {
      segmentId: "refine-001",
      leadId: "lead-food",
      sourceStartMs: 0,
      sourceEndMs: 30_000,
    },
    {
      segmentId: "refine-002",
      leadId: "lead-food",
      sourceStartMs: 30_000,
      sourceEndMs: 60_000,
    },
  ],
  estimatedAsrCostUsd: 0.01,
};

const captionTrack: YouTubeCaptionTrackResult = {
  videoId: "KzAW3yow80Q",
  languageCode: "ko",
  isAutoGenerated: true,
  events: [
    {
      startMs: 5_000,
      durationMs: 5_000,
      text: "칼국수 이야기를 시작했다.",
    },
    {
      startMs: 35_000,
      durationMs: 5_000,
      text: "음식에 대한 반응이 이어졌다.",
    },
  ],
};

function binding() {
  return {
    sourceFingerprint: SOURCE_FINGERPRINT,
    sourceDurationMs: SOURCE_DURATION_MS,
    selectedLeadPlan,
  };
}

function captionInput(
  patch: Partial<AppendBroadcastRefinementCaptionEvidenceInput> = {},
): AppendBroadcastRefinementCaptionEvidenceInput {
  return {
    ...binding(),
    routeKind: "youtube-caption",
    captionRevision: YOUTUBE_CAPTION_MODEL_REVISION,
    captionTrack,
    verifiedNoSpeechEvidence: [],
    ...patch,
  };
}

async function paidRoute(): Promise<BroadcastTranscriptRouteSelection> {
  const manifest: BroadcastTranscriptRouteManifest = {
    schemaVersion: "1.1.0",
    serviceVersion: 6,
    routingPolicyVersion: "1.11.0",
    providerConfigurationVersion: "1.3.0",
    transportVersion: 3,
    transportMode: "paid-direct",
    maximumChunkDurationMs: 90_000,
    primaryMediaType: "audio/wav",
    provider: "qwen",
    modelId: BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_ID,
    modelRevision: BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_REVISION,
    effectiveFallback: { mode: "disabled" },
  };
  return createBroadcastTranscriptRouteSelection(manifest);
}

function verifiedResult(
  route: BroadcastTranscriptRouteSelection,
  sourceStartMs: number,
  sourceEndMs: number,
): BroadcastTranscriptVerifiedResult {
  const providerReceipt = createBroadcastTranscriptProviderReceipt(
    route,
    BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_ID,
    BROADCAST_TRANSCRIPT_QWEN_OMNI_MODEL_REVISION,
    false,
  );
  return {
    schemaVersion: "1.0.0",
    modelId: providerReceipt.modelId,
    modelRevision: providerReceipt.modelRevision,
    providerReceipt,
    sourceStartMs,
    sourceEndMs,
    textKo: "스트리머가 음식에 관해 조용히 설명했다.",
    detectedLanguage: "ko",
    emotion: null,
    billedSeconds: (sourceEndMs - sourceStartMs) / 1_000,
  };
}

async function asrCheckpoints(
  secondOutcome: "no-speech" | "outcome-unknown",
  noSpeechSourceDurationMs = SOURCE_DURATION_MS,
): Promise<{
  readonly refinementCheckpoint: BroadcastRefinementTranscriptCheckpoint;
  readonly providerReceiptCheckpoint: BroadcastTranscriptProviderReceiptCheckpoint;
}> {
  const route = await paidRoute();
  const plannedChunks = selectedLeadPlan.segments.map((segment) => ({
    chunkId: segment.segmentId,
    sourceStartMs: segment.sourceStartMs,
    sourceEndMs: segment.sourceEndMs,
    kind: "event" as const,
  }));
  let refinementCheckpoint =
    createBroadcastRefinementTranscriptCheckpoint({
      refinementInputSignature: "semantic-refinement-evidence-test-v1",
      plannedChunks,
    });
  let providerReceiptCheckpoint =
    createBroadcastTranscriptProviderReceiptCheckpoint({
      sourceFingerprint: SOURCE_FINGERPRINT,
      sourceDurationMs: SOURCE_DURATION_MS,
      route,
      plannedCells: plannedChunks.map(
        ({ chunkId, sourceStartMs, sourceEndMs }) => ({
          chunkId,
          sourceStartMs,
          sourceEndMs,
        }),
      ),
    });
  const firstResult = verifiedResult(route, 0, 30_000);
  refinementCheckpoint = recordBroadcastRefinementTranscriptSuccess(
    refinementCheckpoint,
    "refine-001",
    firstResult,
  );
  providerReceiptCheckpoint = recordBroadcastTranscriptProviderReceipt(
    providerReceiptCheckpoint,
    "refine-001",
    firstResult,
  );
  refinementCheckpoint =
    secondOutcome === "no-speech"
      ? recordBroadcastRefinementTranscriptAbstention(
          refinementCheckpoint,
          "refine-002",
          "no-speech",
          verifiedNoSpeechEvidenceFor(
            selectedLeadPlan.segments[1]!,
            noSpeechSourceDurationMs,
          ).receipt,
        )
      : recordBroadcastRefinementTranscriptGap(refinementCheckpoint, {
          chunkId: "refine-002",
          reason: "outcome-unknown",
          attemptCount: 1,
        });
  return { refinementCheckpoint, providerReceiptCheckpoint };
}

async function appendCaption(
  ledger: BroadcastRefinementEvidenceLedger,
): Promise<BroadcastRefinementEvidenceLedger> {
  return (
    await appendBroadcastRefinementEvidenceRouteEntry(
      ledger,
      ledger.ledgerFingerprint,
      captionInput(),
    )
  ).ledger;
}

function verifiedNoSpeechEvidenceFor(
  segment: DiscoveredLeadRefinementPlan["segments"][number],
  sourceDurationMs = SOURCE_DURATION_MS,
): BroadcastRefinementCaptionSpeechActivityEvidence {
  const plan = createBroadcastSpeechActivityPlan(sourceDurationMs, {
    sourceStartMs: segment.sourceStartMs,
    sourceEndMs: segment.sourceEndMs,
  });
  const winnerProbability = 0.95;
  const otherProbability =
    (1 - winnerProbability) /
    (BROADCAST_SPEECH_ACTIVITY_OUTPUT_CLASS_COUNT - 1);
  const noSpeakerLogits = Array.from(
    { length: BROADCAST_SPEECH_ACTIVITY_OUTPUT_CLASS_COUNT },
    (_, classId) =>
      Math.log(
        classId === BROADCAST_SPEECH_ACTIVITY_NO_SPEAKER_CLASS_ID
          ? winnerProbability
          : otherProbability,
      ),
  );
  const receipts = plan.cells.map((cell) =>
    postprocessBroadcastSpeechActivityLogits({
      operationId: `vad:${segment.segmentId}:${cell.ordinal}`,
      attemptOrdinal: 0,
      runtime: "wasm",
      cell,
      logits: [
        noSpeakerLogits,
        noSpeakerLogits,
        noSpeakerLogits,
        noSpeakerLogits,
      ],
    }),
  );
  return {
    segmentId: segment.segmentId,
    receipt: createBroadcastSpeechActivityRunReceipt(plan, receipts),
  };
}

describe("broadcast refinement evidence ledger", () => {
  it("round-trips caption -> ASR -> caption without deleting either route", async () => {
    let ledger = await createBroadcastRefinementEvidenceLedger(binding());
    const initialCaptionAppend =
      await appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        captionInput(),
      );
    expect(initialCaptionAppend.appended).toBe(true);
    ledger = initialCaptionAppend.ledger;
    const captionEntry = ledger.routeEntries[0]!;
    expect(initialCaptionAppend.routeEntryFingerprint).toBe(
      captionEntry.entryFingerprint,
    );
    const afterCaptionAppend = ledger;
    const duplicateCaptionAppend =
      await appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        captionInput(),
      );
    ledger = duplicateCaptionAppend.ledger;
    expect(duplicateCaptionAppend).toMatchObject({
      routeEntryFingerprint: captionEntry.entryFingerprint,
      appended: false,
    });
    expect(ledger).toEqual(afterCaptionAppend);
    ledger = await activateBroadcastRefinementEvidenceRoute(
      ledger,
      ledger.ledgerFingerprint,
      captionEntry.entryFingerprint,
    );
    const firstCaptionProjection =
      ledger.activeRouteProjectionFingerprint;

    const asr = await asrCheckpoints("no-speech");
    ledger = (
      await appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        {
          ...binding(),
          routeKind: "asr",
          billingClass: "paid",
          ...asr,
        },
      )
    ).ledger;
    const paidAsrEntry = ledger.routeEntries[1]!;
    ledger = await activateBroadcastRefinementEvidenceRoute(
      ledger,
      ledger.ledgerFingerprint,
      paidAsrEntry.entryFingerprint,
    );
    expect(
      projectBroadcastRefinementActiveEvidenceRoute(ledger),
    ).toMatchObject({
      routeKind: "asr",
      billingClass: "paid",
      publicationEligible: true,
    });

    ledger = await activateBroadcastRefinementEvidenceRoute(
      ledger,
      ledger.ledgerFingerprint,
      captionEntry.entryFingerprint,
    );
    expect(ledger.routeEntries).toHaveLength(2);
    expect(ledger.routeEntries[1]).toEqual(paidAsrEntry);
    expect(ledger.activeRouteProjectionFingerprint).toBe(
      firstCaptionProjection,
    );
    expect(broadcastRefinementEvidenceLedgerCanPublish(ledger)).toBe(true);
    expect(getBroadcastRefinementActiveEvidencePayload(ledger)).toEqual({
      routeEntryFingerprint: captionEntry.entryFingerprint,
      routeKind: "youtube-caption",
      billingClass: "free",
      evidencePayload: captionEntry.evidencePayload,
      settlement: captionEntry.settlement,
    });

    const serialized =
      await serializeBroadcastRefinementEvidenceLedger(ledger);
    expect(
      await parseBroadcastRefinementEvidenceLedgerJson(serialized),
    ).toEqual(ledger);
  });

  it("derives caption settlements only from exact text and verified no-speech VAD", async () => {
    const sparseCaptionTrack: YouTubeCaptionTrackResult = {
      ...captionTrack,
      events: [captionTrack.events[0]!],
    };
    const secondSegment = selectedLeadPlan.segments[1]!;
    const withoutVad = createBroadcastRefinementCaptionCellSettlements({
      sourceDurationMs: SOURCE_DURATION_MS,
      selectedLeadPlan,
      captionTrack: sparseCaptionTrack,
      verifiedNoSpeechEvidence: [],
    });
    expect(withoutVad).toEqual([
      {
        ...selectedLeadPlan.segments[0]!,
        status: "success",
        textKo: "칼국수 이야기를 시작했다.",
      },
      {
        ...secondSegment,
        status: "gap",
        reason: "outcome-unknown",
      },
    ]);

    const verifiedNoSpeechEvidence = [
      verifiedNoSpeechEvidenceFor(secondSegment),
    ];
    const withVad = createBroadcastRefinementCaptionCellSettlements({
      sourceDurationMs: SOURCE_DURATION_MS,
      selectedLeadPlan,
      captionTrack: sparseCaptionTrack,
      verifiedNoSpeechEvidence,
    });
    expect(withVad[1]).toEqual({
      ...secondSegment,
      status: "resolved",
      reason: "no-speech",
    });

    let ledger = await createBroadcastRefinementEvidenceLedger(binding());
    const appended = await appendBroadcastRefinementEvidenceRouteEntry(
      ledger,
      ledger.ledgerFingerprint,
      captionInput({
        captionTrack: sparseCaptionTrack,
        verifiedNoSpeechEvidence,
      }),
    );
    ledger = appended.ledger;
    expect(ledger.routeEntries[0]!.settlement.publicationEligible).toBe(true);
    expect(
      ledger.routeEntries[0]!.evidencePayload.kind ===
        "youtube-caption-cells"
        ? ledger.routeEntries[0]!.evidencePayload
            .verifiedNoSpeechEvidence
        : [],
    ).toEqual(verifiedNoSpeechEvidence);

    const malformedEvidence = {
      ...verifiedNoSpeechEvidence[0]!,
      receipt: {
        ...verifiedNoSpeechEvidence[0]!.receipt,
        sourceStartMs: secondSegment.sourceStartMs + 1,
      },
    };
    expect(() =>
      createBroadcastRefinementCaptionCellSettlements({
        sourceDurationMs: SOURCE_DURATION_MS,
        selectedLeadPlan,
        captionTrack: sparseCaptionTrack,
        verifiedNoSpeechEvidence: [malformedEvidence],
      }),
    ).toThrow("exact-range VAD");
  });

  it("rejects stale source and selected-lead-plan bindings before appending", async () => {
    const ledger = await createBroadcastRefinementEvidenceLedger(binding());

    await expect(
      appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        captionInput({
          sourceFingerprint: `sha256:${"c".repeat(64)}`,
        }),
      ),
    ).rejects.toMatchObject({ code: "STALE_BINDING" });

    await expect(
      appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        captionInput({
          selectedLeadPlan: {
            ...selectedLeadPlan,
            segments: selectedLeadPlan.segments.map((segment, index) =>
              index === 0
                ? { ...segment, sourceEndMs: segment.sourceEndMs - 1 }
                : segment,
            ),
          },
        }),
      ),
    ).rejects.toMatchObject({ code: "STALE_BINDING" });

    await expect(
      appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        `sha256:${"d".repeat(64)}`,
        captionInput(),
      ),
    ).rejects.toMatchObject({ code: "CAS_MISMATCH" });
  });

  it("keeps partial or outcome-unknown ASR evidence but blocks publication", async () => {
    let ledger = await createBroadcastRefinementEvidenceLedger(binding());
    const partialAsr = await asrCheckpoints("outcome-unknown");
    ledger = (
      await appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        {
          ...binding(),
          routeKind: "asr",
          billingClass: "paid",
          ...partialAsr,
        },
      )
    ).ledger;
    const partialEntry = ledger.routeEntries[0]!;
    expect(partialEntry.providerReceiptCheckpointSignature).toMatch(
      /^sha256:[a-f0-9]{64}$/u,
    );
    expect(partialEntry.settlement).toEqual({
      plannedCellCount: 2,
      successCellCount: 1,
      resolvedCellCount: 0,
      gapCellCount: 1,
      missingCellCount: 0,
      status: "blocked",
      publicationEligible: false,
    });

    ledger = await activateBroadcastRefinementEvidenceRoute(
      ledger,
      ledger.ledgerFingerprint,
      partialEntry.entryFingerprint,
    );
    expect(broadcastRefinementEvidenceLedgerCanPublish(ledger)).toBe(false);
    expect(
      projectBroadcastRefinementActiveEvidenceRoute(ledger)
        ?.projectionFingerprint,
    ).toBe(ledger.activeRouteProjectionFingerprint);
  });

  it("rejects a no-speech ASR receipt bound to a different source duration", async () => {
    const ledger = await createBroadcastRefinementEvidenceLedger(binding());
    const staleAsr = await asrCheckpoints("no-speech", 60_000);

    await expect(
      appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        {
          ...binding(),
          routeKind: "asr",
          billingClass: "paid",
          ...staleAsr,
        },
      ),
    ).rejects.toMatchObject({
      code: "INVALID_LEDGER",
    });
  });

  it("preserves an old paid ASR entry after adding and activating a free ASR entry", async () => {
    let ledger = await createBroadcastRefinementEvidenceLedger(binding());
    const asr = await asrCheckpoints("no-speech");
    ledger = (
      await appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        {
          ...binding(),
          routeKind: "asr",
          billingClass: "paid",
          ...asr,
        },
      )
    ).ledger;
    const paidEntry = ledger.routeEntries[0]!;

    ledger = (
      await appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        {
          ...binding(),
          routeKind: "asr",
          billingClass: "free",
          ...asr,
        },
      )
    ).ledger;
    const freeEntry = ledger.routeEntries[1]!;
    ledger = await activateBroadcastRefinementEvidenceRoute(
      ledger,
      ledger.ledgerFingerprint,
      freeEntry.entryFingerprint,
    );

    expect(ledger.routeEntries).toHaveLength(2);
    expect(ledger.routeEntries[0]).toEqual(paidEntry);
    expect(ledger.routeEntries.map(({ billingClass }) => billingClass)).toEqual(
      ["paid", "free"],
    );
    expect(
      projectBroadcastRefinementActiveEvidenceRoute(ledger),
    ).toMatchObject({
      routeEntryFingerprint: freeEntry.entryFingerprint,
      billingClass: "free",
      publicationEligible: true,
    });
  });

  it("fails closed on malformed, non-canonical, or fingerprint-tampered JSON", async () => {
    let ledger = await createBroadcastRefinementEvidenceLedger(binding());
    ledger = await appendCaption(ledger);
    ledger = await activateBroadcastRefinementEvidenceRoute(
      ledger,
      ledger.ledgerFingerprint,
      ledger.routeEntries[0]!.entryFingerprint,
    );
    const serialized =
      await serializeBroadcastRefinementEvidenceLedger(ledger);

    expect(
      await parseBroadcastRefinementEvidenceLedgerJson(` ${serialized}`),
    ).toBeNull();
    expect(
      await parseBroadcastRefinementEvidenceLedgerJson(
        JSON.stringify({
          ...ledger,
          unexpected: true,
        }),
      ),
    ).toBeNull();
    expect(
      await parseBroadcastRefinementEvidenceLedgerJson(
        JSON.stringify({
          ...ledger,
          activeRouteProjectionFingerprint: `sha256:${"0".repeat(64)}`,
        }),
      ),
    ).toBeNull();
    expect(
      await parseBroadcastRefinementEvidenceLedgerJson(
        JSON.stringify({
          ...ledger,
          routeEntries: ledger.routeEntries.map((entry) => ({
            ...entry,
            settlement: {
              ...entry.settlement,
              publicationEligible: false,
            },
          })),
        }),
      ),
    ).toBeNull();
  });

  it("binds the caption route to the exact event source, not only its display metadata", async () => {
    let ledger = await createBroadcastRefinementEvidenceLedger(binding());
    ledger = await appendCaption(ledger);
    const firstFence = ledger.routeEntries[0]!.captionEventSourceFence;
    ledger = (
      await appendBroadcastRefinementEvidenceRouteEntry(
        ledger,
        ledger.ledgerFingerprint,
        captionInput({
          captionTrack: {
            ...captionTrack,
            events: captionTrack.events.map((event, index) =>
              index === 0 ? { ...event, text: "다른 캡션 사건" } : event,
            ),
          },
        }),
      )
    ).ledger;

    expect(ledger.routeEntries).toHaveLength(2);
    expect(ledger.routeEntries[1]!.captionEventSourceFence).not.toBe(
      firstFence,
    );
  });

  it("surfaces its typed contract error for invalid activation", async () => {
    const ledger = await createBroadcastRefinementEvidenceLedger(binding());
    await expect(
      activateBroadcastRefinementEvidenceRoute(
        ledger,
        ledger.ledgerFingerprint,
        `sha256:${"f".repeat(64)}`,
      ),
    ).rejects.toBeInstanceOf(BroadcastRefinementEvidenceLedgerError);
  });
});
