import { createHash } from "node:crypto";

import { describe, expect, it, vi } from "vitest";

import {
  BROADCAST_CONTEXT_SCHEMA_VERSION,
  type BroadcastContextResult,
} from "./broadcastContextProtocol";
import { createBroadcastParticipantGrounding } from "./broadcastParticipantGrounding";
import { AI_BROADCAST_CONTEXT_ROUTING_REVISION } from "./aiModelRoutingPolicy";
import {
  AMORETTO_YOUTUBE_CHANNEL_HANDLE,
  AMORETTO_YOUTUBE_CHANNEL_ID,
  normalizeChannelVideoTitle,
  type ChannelPreanalysisCatalogManifest,
} from "./channelPreanalysisCatalog";
import {
  CHANNEL_PREANALYSIS_BUNDLE_MAX_BYTES,
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
  type ChannelPreanalysisBundle,
} from "./channelPreanalysisBundle";
import {
  CHANNEL_PREANALYSIS_CATALOG_FILE,
  CHANNEL_PREANALYSIS_MANIFEST_MAX_BYTES,
  fetchChannelPreanalysisVisualFingerprintCohortForLookup,
  fetchChannelPreanalysisBundle,
  fetchChannelPreanalysisManifest,
  fetchChannelPreanalysisReviewForLookup,
  parseChannelPreanalysisManifest,
  requestChannelPreanalysisMatch,
  resolveChannelPreanalysisLookupByVisualFingerprintCohort,
  type ChannelPreanalysisLookupResult,
} from "./channelPreanalysisClient";
import {
  CHANNEL_PREANALYSIS_PARTICIPANT_PROVENANCE_SCHEMA_VERSION,
  CHANNEL_PREANALYSIS_REVIEW_BUNDLE_SCHEMA_VERSION,
  CHANNEL_PREANALYSIS_REVIEW_CERTIFICATE_SCHEMA_VERSION,
  channelPreanalysisReviewBundleArtifactId,
  createChannelPreanalysisReviewContentDigests,
  type ChannelPreanalysisReviewBundle,
} from "./channelPreanalysisReviewBundle";
import {
  buildChannelPreanalysisLocalVisualCohortSamplingPlan,
  createChannelPreanalysisVisualAnchorDescriptor,
  createChannelPreanalysisVisualFingerprint,
  serializeChannelPreanalysisVisualFingerprint,
} from "./channelPreanalysisVisualFingerprint";
import { createChannelPreanalysisVisualCoverageReceipt } from "./channelPreanalysisVisualCoverage";

const VIDEO_ID = "KzAW3yow80Q";
const TITLE = "2026 07 17 - 음식 토크";
const DURATION_MS = 120_000;
const RAW_BASE = "https://catalog.test/amoretto/";
const BUNDLED_BASE = "/exclipper/preanalysis/amoretto/";
const ARTIFACT_ID = `youtube-caption-bundle:${VIDEO_ID}:v1`;
const REVIEW_ARTIFACT_ID = `review-bundle:${VIDEO_ID}:v2`;
const REVIEW_STORAGE_KEY =
  `amoretto-vods/videos/${VIDEO_ID}.review.v2.json`;

interface ManifestOptions {
  readonly videoOverrides?: Partial<
    ChannelPreanalysisCatalogManifest["videos"][number]
  >;
  readonly artifactOverrides?: Partial<
    ChannelPreanalysisCatalogManifest["artifacts"][number]
  >;
  readonly additionalVideos?: ChannelPreanalysisCatalogManifest["videos"];
}

function manifest(
  bundleText: string,
  options: ManifestOptions = {},
): ChannelPreanalysisCatalogManifest {
  const bundleBytes = new TextEncoder().encode(bundleText);
  const artifact = {
    artifactId: ARTIFACT_ID,
    videoId: VIDEO_ID,
    kind: "transcript" as const,
    revision: 1,
    storageKey: `amoretto-vods/videos/${VIDEO_ID}.v1.json`,
    contentDigest: `sha256:${createHash("sha256").update(bundleBytes).digest("hex")}`,
    byteLength: bundleBytes.byteLength,
    createdAt: "2026-07-30T00:00:00.000Z",
    ...options.artifactOverrides,
  };
  const video = {
    channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
    videoId: VIDEO_ID,
    title: TITLE,
    normalizedTitle: normalizeChannelVideoTitle(TITLE),
    durationMs: DURATION_MS,
    publishedAt: "2026-07-17T04:00:00.000Z",
    updatedAt: "2026-07-30T00:00:00.000Z",
    watchUrl: `https://www.youtube.com/watch?v=${VIDEO_ID}`,
    state: "transcript-ready" as const,
    revision: 1,
    artifactIds: [ARTIFACT_ID],
    registeredLocalSampledFingerprints: [],
    retry: null,
    ...options.videoOverrides,
  };
  return {
    schemaVersion: 1,
    channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
    channelHandle: AMORETTO_YOUTUBE_CHANNEL_HANDLE,
    revision: 1,
    generatedAt: "2026-07-30T00:00:00.000Z",
    videos: [video, ...(options.additionalVideos ?? [])],
    artifacts: [artifact],
  };
}

async function bundleJson(
  overrides: {
    readonly videoId?: string;
    readonly title?: string;
  } = {},
): Promise<string> {
  const videoId = overrides.videoId ?? VIDEO_ID;
  const title = overrides.title ?? TITLE;
  const bundle = await createChannelPreanalysisBundle({
    channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
    videoId,
    title,
    durationMs: DURATION_MS,
    publishedAt: "2026-07-17T04:00:00.000Z",
    catalogRevision: 1,
    state: "transcript-ready",
    captionTrack: {
      videoId,
      languageCode: "ko",
      isAutoGenerated: true,
      events: [{ startMs: 1_000, durationMs: 1_000, text: "음식 이야기" }],
    },
    chapters: [
      {
        chapterId: "youtube-001",
        startMs: 0,
        endMs: DURATION_MS,
        evidenceMode: "complete-transcript",
        evidenceCoverageRatio: 1,
        summaryKo: "음식 이야기",
      },
    ],
    broadcastContext: null,
    provenance: createDefaultChannelPreanalysisProvenance(
      videoId,
      "2026-07-30T00:00:00.000Z",
    ),
  });
  return JSON.stringify(bundle);
}

function visualFingerprintFixture(): {
  readonly fingerprintText: string;
  readonly artifact: ChannelPreanalysisCatalogManifest["artifacts"][number];
} {
  const frameLuma = (seed: number) =>
    Uint8Array.from(
      { length: 32 * 18 },
      (_, index) =>
        (index * (seed * 2 + 17) +
          Math.floor(index / 32) * (seed + 29) +
          seed * 43) %
        256,
    );
  const fingerprint = createChannelPreanalysisVisualFingerprint({
    videoId: VIDEO_ID,
    sourceDurationMs: DURATION_MS,
    createdAt: "2026-07-30T00:00:00.000Z",
    anchors: Array.from({ length: 12 }, (_, index) =>
      createChannelPreanalysisVisualAnchorDescriptor({
        timestampMs: (index + 1) * 9_000,
        luma: frameLuma(index),
      }),
    ),
  });
  const fingerprintText =
    serializeChannelPreanalysisVisualFingerprint(fingerprint);
  const fingerprintBytes = new TextEncoder().encode(fingerprintText);
  return {
    fingerprintText,
    artifact: {
      artifactId:
        `youtube-storyboard-visual-fingerprint:${VIDEO_ID}:v1`,
      videoId: VIDEO_ID,
      kind: "fingerprint",
      revision: 1,
      storageKey:
        `amoretto-vods/videos/${VIDEO_ID}.visual-fingerprint.v1.json`,
      contentDigest:
        `sha256:${createHash("sha256").update(fingerprintBytes).digest("hex")}`,
      byteLength: fingerprintBytes.byteLength,
      createdAt: fingerprint.createdAt,
    },
  };
}

function reviewArtifactFixture(): ChannelPreanalysisCatalogManifest["artifacts"][number] {
  return {
    artifactId: REVIEW_ARTIFACT_ID,
    videoId: VIDEO_ID,
    kind: "review",
    revision: 2,
    storageKey: REVIEW_STORAGE_KEY,
    contentDigest: `sha256:${"a".repeat(64)}`,
    byteLength: 1_024,
    createdAt: "2026-07-30T00:00:00.000Z",
  };
}

function reviewContext(): BroadcastContextResult {
  return {
    schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
    broadcastSummaryKo: "방송 전체 맥락과 검토 결과를 모두 확인했습니다.",
    hostStreamerProfile: null,
    recurringThemesKo: [],
    annotations: [],
    semanticChaptersSupported: true,
    semanticChapters: [],
    discoveredLeadsSupported: true,
    discoveredLeads: [],
    coverage: {
      status: "complete",
      coveredMs: DURATION_MS,
      coverageRatio: 1,
      gaps: [],
      partialChapterIds: [],
    },
  };
}

async function contextBundleJson(): Promise<string> {
  const transcript = JSON.parse(await bundleJson()) as ChannelPreanalysisBundle;
  return JSON.stringify({
    ...transcript,
    state: "context-ready",
    broadcastContext: reviewContext(),
    contextProvenance: {
      generatedAt: "2026-07-30T00:01:00.000Z",
      modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
      contextReceipt: {
        contractVersion: "2.0.0",
        routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
        modelId: "qwen3.7-plus",
        modelRevision:
          "qwen3.7-plus-context-editorial-jury-topic-balanced-2026-07-22",
      },
      evidenceScope: "youtube-caption-transcript-only",
      localVisualVerificationRequired: true,
    },
  });
}

async function reviewBundleJson(
  transcriptDigest: ChannelPreanalysisReviewBundle["transcriptDigest"],
  sourceVideoId = VIDEO_ID,
): Promise<string> {
  const participantGrounding = createBroadcastParticipantGrounding({
    sourceDurationMs: DURATION_MS,
    castRosterId: null,
    chapters: [],
  }, {
    visualIdentity: {
      receipt: { adapter: "visual-identity", revision: "test-visual-v1", status: "completed", inputCount: 0, processedCount: 0, unavailableReason: null },
      evidence: [],
    },
    voiceIdentity: {
      receipt: { adapter: "voice-identity", revision: "test-voice-v1", status: "completed", inputCount: 0, processedCount: 0, unavailableReason: null },
      evidence: [],
    },
  });
  const artifactRevision = 2;
  const source = {
    sourceId: "amoretto-vods" as const,
    channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
    videoId: sourceVideoId,
  };
  const visualCoverage = createChannelPreanalysisVisualCoverageReceipt({
    sourceDurationMs: DURATION_MS,
    videoId: sourceVideoId,
    sourceFingerprintDigest: visualFingerprintFixture().artifact.contentDigest as
      `sha256:${string}`,
    visualSeedTimestampsMs: [],
  });
  const unsealed = {
    source,
    broadcastContext: reviewContext(),
    visualCoverage,
    participantGrounding,
    candidates: [],
  };
  const digests = await createChannelPreanalysisReviewContentDigests(unsealed);
  const bundle: ChannelPreanalysisReviewBundle = {
    schemaVersion: CHANNEL_PREANALYSIS_REVIEW_BUNDLE_SCHEMA_VERSION,
    artifactId: channelPreanalysisReviewBundleArtifactId(
      sourceVideoId,
      artifactRevision,
    ),
    artifactRevision,
    createdAt: "2026-07-30T00:00:00.000Z",
    source,
    sourceDurationMs: DURATION_MS,
    transcriptDigest,
    broadcastContext: unsealed.broadcastContext,
    broadcastContextDigest: digests.broadcastContextDigest,
    visualCoverage,
    participantGrounding,
    participantGroundingProvenance: {
      schemaVersion:
        CHANNEL_PREANALYSIS_PARTICIPANT_PROVENANCE_SCHEMA_VERSION,
      checkpointDigest: digests.participantGroundingDigest,
      generatedAt: "2026-07-30T00:00:00.000Z",
      pipelineRevision: "scheduled-review-v1",
    },
    candidates: [],
    certificate: {
      schemaVersion: CHANNEL_PREANALYSIS_REVIEW_CERTIFICATE_SCHEMA_VERSION,
      pipelineRevision: "scheduled-review-v1",
      outcome: "verified-empty",
      sourceIdentityDigest: digests.sourceIdentityDigest,
      transcriptDigest,
      broadcastContextDigest: digests.broadcastContextDigest,
      participantGroundingDigest: digests.participantGroundingDigest,
      visualCoverageDigest: digests.visualCoverageDigest,
      candidateSetDigest: digests.candidateSetDigest,
      finalCandidateIds: [],
    },
  };
  return JSON.stringify(bundle);
}

async function preparedReviewFixture(sourceVideoId = VIDEO_ID): Promise<{
  readonly contextBundleText: string;
  readonly reviewBundleText: string;
  readonly manifest: ChannelPreanalysisCatalogManifest;
}> {
  const contextBundleText = await contextBundleJson();
  const contextBundle = JSON.parse(
    contextBundleText,
  ) as ChannelPreanalysisBundle;
  const reviewBundleText = await reviewBundleJson(
    contextBundle.transcriptDigest as ChannelPreanalysisReviewBundle["transcriptDigest"],
    sourceVideoId,
  );
  const reviewBytes = new TextEncoder().encode(reviewBundleText);
  const reviewArtifact = {
    ...reviewArtifactFixture(),
    contentDigest:
      `sha256:${createHash("sha256").update(reviewBytes).digest("hex")}` as const,
    byteLength: reviewBytes.byteLength,
  };
  const fingerprintArtifact = visualFingerprintFixture().artifact;
  const baseManifest = manifest(contextBundleText);
  return {
    contextBundleText,
    reviewBundleText,
    manifest: {
      ...baseManifest,
      videos: [
        {
          ...baseManifest.videos[0]!,
          state: "review-ready",
          revision: 2,
          artifactIds: [
            ARTIFACT_ID,
            fingerprintArtifact.artifactId,
            REVIEW_ARTIFACT_ID,
          ],
        },
      ],
      artifacts: [
        ...baseManifest.artifacts,
        fingerprintArtifact,
        reviewArtifact,
      ],
    },
  };
}

describe("channelPreanalysisClient", () => {
  it("accepts only a closed review-ready catalog entry", async () => {
    const preparedBundle = await bundleJson();
    const baseManifest = manifest(preparedBundle);
    const reviewArtifact = reviewArtifactFixture();
    const reviewReadyManifest: ChannelPreanalysisCatalogManifest = {
      ...baseManifest,
      videos: [
        {
          ...baseManifest.videos[0]!,
          state: "review-ready",
          revision: 2,
          artifactIds: [ARTIFACT_ID, REVIEW_ARTIFACT_ID],
        },
      ],
      artifacts: [...baseManifest.artifacts, reviewArtifact],
    };

    expect(
      parseChannelPreanalysisManifest(JSON.stringify(reviewReadyManifest)),
    ).toMatchObject({
      videos: [{ state: "review-ready" }],
      artifacts: [
        { kind: "transcript" },
        {
          artifactId: REVIEW_ARTIFACT_ID,
          kind: "review",
          storageKey: REVIEW_STORAGE_KEY,
        },
      ],
    });

    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify({
          ...reviewReadyManifest,
          videos: [
            {
              ...reviewReadyManifest.videos[0]!,
              artifactIds: [ARTIFACT_ID],
            },
          ],
          artifacts: baseManifest.artifacts,
        }),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));

    for (const invalidReviewArtifact of [
      { ...reviewArtifact, artifactId: `${REVIEW_ARTIFACT_ID}:wrong` },
      {
        ...reviewArtifact,
        storageKey: `amoretto-vods/videos/${VIDEO_ID}.v2.json`,
      },
      { ...reviewArtifact, contentDigest: `sha256:${"A".repeat(64)}` },
      { ...reviewArtifact, byteLength: 4 * 1024 * 1024 + 1 },
    ]) {
      expect(() =>
        parseChannelPreanalysisManifest(
          JSON.stringify({
            ...reviewReadyManifest,
            artifacts: [...baseManifest.artifacts, invalidReviewArtifact],
          }),
        ),
      ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
    }

    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify({
          ...reviewReadyManifest,
          videos: [
            {
              ...reviewReadyManifest.videos[0]!,
              revision: 3,
            },
          ],
        }),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
  });

  it("accepts a review retry only after context-ready", async () => {
    const preparedBundle = await bundleJson();
    const baseManifest = manifest(preparedBundle);
    const retryManifest: ChannelPreanalysisCatalogManifest = {
      ...baseManifest,
      videos: [
        {
          ...baseManifest.videos[0]!,
          state: "retryable",
          retry: {
            stage: "review",
            lastSuccessfulState: "context-ready",
            attemptCount: 1,
            nextAttemptAt: "2026-07-30T01:00:00.000Z",
            errorCode: "REVIEW_PROVIDER_UNAVAILABLE",
          },
        },
      ],
    };

    expect(
      parseChannelPreanalysisManifest(JSON.stringify(retryManifest)),
    ).toMatchObject({
      videos: [
        {
          state: "retryable",
          retry: {
            stage: "review",
            lastSuccessfulState: "context-ready",
          },
        },
      ],
    });

    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify({
          ...retryManifest,
          videos: [
            {
              ...retryManifest.videos[0]!,
              retry: {
                ...retryManifest.videos[0]!.retry!,
                lastSuccessfulState: "transcript-ready",
              },
            },
          ],
        }),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
  });

  it("preserves a closed review snapshot across fingerprint retry", async () => {
    const preparedBundle = await bundleJson();
    const baseManifest = manifest(preparedBundle);
    const reviewArtifact = reviewArtifactFixture();
    const retryManifest: ChannelPreanalysisCatalogManifest = {
      ...baseManifest,
      videos: [
        {
          ...baseManifest.videos[0]!,
          state: "retryable",
          revision: 2,
          artifactIds: [ARTIFACT_ID, REVIEW_ARTIFACT_ID],
          retry: {
            stage: "fingerprint",
            lastSuccessfulState: "review-ready",
            attemptCount: 1,
            nextAttemptAt: "2026-07-30T01:00:00.000Z",
            errorCode: "FINGERPRINT_UNAVAILABLE",
          },
        },
      ],
      artifacts: [...baseManifest.artifacts, reviewArtifact],
    };

    expect(
      parseChannelPreanalysisManifest(JSON.stringify(retryManifest)),
    ).toMatchObject({
      videos: [
        {
          state: "retryable",
          retry: {
            stage: "fingerprint",
            lastSuccessfulState: "review-ready",
          },
        },
      ],
    });

    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify({
          ...retryManifest,
          videos: [
            {
              ...retryManifest.videos[0]!,
              artifactIds: [ARTIFACT_ID],
            },
          ],
          artifacts: baseManifest.artifacts,
        }),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
  });

  it("loads a digest- and identity-verified review snapshot for an exact lookup", async () => {
    const prepared = await preparedReviewFixture();
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(prepared.manifest)
            : url.endsWith(".review.v2.json")
              ? prepared.reviewBundleText
              : prepared.contextBundleText,
          { status: 200 },
        ),
      );
    });
    const lookup = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      { fetchImplementation, rawBaseUrl: RAW_BASE, bundledBaseUrl: BUNDLED_BASE },
    );

    const loaded = await fetchChannelPreanalysisReviewForLookup(lookup, {
      fetchImplementation,
    });

    expect(lookup.bundle?.state).toBe("context-ready");
    expect(loaded).toMatchObject({
      review: {
        source: { videoId: VIDEO_ID },
        certificate: { outcome: "verified-empty" },
      },
      artifact: { artifactId: REVIEW_ARTIFACT_ID, kind: "review" },
    });
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("rejects review bytes with digest drift or a different source identity", async () => {
    const exact = await preparedReviewFixture();
    const tamperedReview = exact.reviewBundleText.replaceAll(
      "scheduled-review-v1",
      "scheduled-review-v2",
    );
    expect(tamperedReview.length).toBe(exact.reviewBundleText.length);

    const wrongIdentity = await preparedReviewFixture("AbCdEfGhI12");
    for (const [prepared, reviewText] of [
      [exact, tamperedReview],
      [wrongIdentity, wrongIdentity.reviewBundleText],
    ] as const) {
      const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
        const url =
          typeof input === "string"
            ? input
            : input instanceof URL
              ? input.toString()
              : input.url;
        return Promise.resolve(
          new Response(
            url.endsWith("catalog.json")
              ? JSON.stringify(prepared.manifest)
              : url.endsWith(".review.v2.json")
                ? reviewText
                : prepared.contextBundleText,
            { status: 200 },
          ),
        );
      });
      const lookup = await requestChannelPreanalysisMatch(
        { videoId: VIDEO_ID },
        {
          fetchImplementation,
          rawBaseUrl: RAW_BASE,
          bundledBaseUrl: BUNDLED_BASE,
        },
      );

      await expect(
        fetchChannelPreanalysisReviewForLookup(lookup, {
          fetchImplementation,
        }),
      ).rejects.toMatchObject({ code: "INVALID_REVIEW" });
    }
  });

  it("falls back from the raw branch catalog to the bundled Pages copy", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      if (url.startsWith(RAW_BASE)) {
        return Promise.resolve(new Response("", { status: 503 }));
      }
      return Promise.resolve(
        new Response(JSON.stringify(preparedManifest), { status: 200 }),
      );
    });
    const loaded = await fetchChannelPreanalysisManifest({
      fetchImplementation,
      rawBaseUrl: RAW_BASE,
      bundledBaseUrl: BUNDLED_BASE,
    });
    expect(loaded.source).toBe("bundled");
    expect(fetchImplementation).toHaveBeenNthCalledWith(
      1,
      `${RAW_BASE}${CHANNEL_PREANALYSIS_CATALOG_FILE}`,
      expect.any(Object),
    );
    expect(fetchImplementation).toHaveBeenNthCalledWith(
      2,
      `${BUNDLED_BASE}${CHANNEL_PREANALYSIS_CATALOG_FILE}`,
      expect.any(Object),
    );
  });

  it("loads and digest-verifies a bundle only for an exact identity", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });
    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.match.confidence).toBe("exact");
    expect(result.bundleStatus).toBe("loaded");
    expect(result.bundle?.videoId).toBe(VIDEO_ID);
    expect(result.bundleArtifact).toMatchObject({
      artifactId: ARTIFACT_ID,
      contentDigest: preparedManifest.artifacts[0]?.contentDigest,
    });
    expect(fetchImplementation).toHaveBeenCalledTimes(2);
  });

  it("loads the preserved transcript while context generation is retryable", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle, {
      videoOverrides: {
        state: "retryable",
        retry: {
          stage: "context",
          lastSuccessfulState: "transcript-ready",
          attemptCount: 1,
          nextAttemptAt: "2026-07-30T01:00:00.000Z",
          errorCode: "CONTEXT_OUTCOME_UNKNOWN",
        },
      },
    });
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );

    expect(result.match.match?.state).toBe("retryable");
    expect(result.match.match?.retry).toMatchObject({
      stage: "context",
      lastSuccessfulState: "transcript-ready",
    });
    expect(result.bundleStatus).toBe("loaded");
    expect(result.bundle?.state).toBe("transcript-ready");
    expect(result.bundle?.broadcastContext).toBeNull();
    expect(result.bundleArtifact?.artifactId).toBe(ARTIFACT_ID);
    expect(fetchImplementation).toHaveBeenCalledTimes(2);
  });

  it("uses a bundled ready snapshot while the raw catalog is still incomplete", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const rawManifest: ChannelPreanalysisCatalogManifest = {
      ...preparedManifest,
      videos: preparedManifest.videos.map((video) => ({
        ...video,
        durationMs: null,
        state: "discovered",
        artifactIds: [],
      })),
      artifacts: [],
    };
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      const isRaw = url.startsWith(RAW_BASE);
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(isRaw ? rawManifest : preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(result.bundle?.videoId).toBe(VIDEO_ID);
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("continues to bundled identity matching when raw has no match", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const rawManifest: ChannelPreanalysisCatalogManifest = {
      ...preparedManifest,
      videos: [],
      artifacts: [],
    };
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      const isRaw = url.startsWith(RAW_BASE);
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(isRaw ? rawManifest : preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("gives the bundled manifest a fresh deadline after raw stalls", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn(
      (input: RequestInfo | URL, init?: RequestInit) => {
        const url =
          typeof input === "string"
            ? input
            : input instanceof URL
              ? input.toString()
              : input.url;
        if (url === `${RAW_BASE}${CHANNEL_PREANALYSIS_CATALOG_FILE}`) {
          return new Promise<Response>((_resolve, reject) => {
            init?.signal?.addEventListener(
              "abort",
              () =>
                reject(
                  init.signal?.reason instanceof Error
                    ? init.signal.reason
                    : new Error("raw manifest aborted"),
                ),
              { once: true },
            );
          });
        }
        return Promise.resolve(
          new Response(
            url.endsWith("catalog.json")
              ? JSON.stringify(preparedManifest)
              : preparedBundle,
            { status: 200 },
          ),
        );
      },
    );

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
        manifestRequestTimeoutMs: 5,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("gives the bundled bundle a fresh deadline after raw bundle stalls", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn(
      (input: RequestInfo | URL, init?: RequestInit) => {
        const url =
          typeof input === "string"
            ? input
            : input instanceof URL
              ? input.toString()
              : input.url;
        if (
          url.startsWith(RAW_BASE) &&
          !url.endsWith(CHANNEL_PREANALYSIS_CATALOG_FILE)
        ) {
          return new Promise<Response>((_resolve, reject) => {
            init?.signal?.addEventListener(
              "abort",
              () =>
                reject(
                  init.signal?.reason instanceof Error
                    ? init.signal.reason
                    : new Error("raw bundle aborted"),
                ),
              { once: true },
            );
          });
        }
        return Promise.resolve(
          new Response(
            url.endsWith("catalog.json")
              ? JSON.stringify(preparedManifest)
              : preparedBundle,
            { status: 200 },
          ),
        );
      },
    );

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
        bundleRequestTimeoutMs: 5,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("returns a probable title-duration match without downloading its bundle", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn(() =>
      Promise.resolve(
        new Response(JSON.stringify(preparedManifest), { status: 200 }),
      ),
    );
    const result = await requestChannelPreanalysisMatch(
      { title: `${TITLE}.mp4`, durationMs: DURATION_MS + 1_000 },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.match.confidence).toBe("probable");
    expect(result.bundleStatus).toBe("not-exact");
    expect(result.bundle).toBeNull();
    expect(fetchImplementation).toHaveBeenCalledTimes(2);
  });

  it("promotes a completely renamed upload only after unique visual consensus", async () => {
    const preparedBundle = await bundleJson();
    const baseManifest = manifest(preparedBundle);
    const frameLuma = (seed: number) =>
      Uint8Array.from(
        { length: 32 * 18 },
        (_, index) =>
          (index * (seed * 2 + 17) +
            Math.floor(index / 32) * (seed + 29) +
            seed * 43) %
          256,
      );
    const fingerprint = createChannelPreanalysisVisualFingerprint({
      videoId: VIDEO_ID,
      sourceDurationMs: DURATION_MS,
      createdAt: baseManifest.videos[0]!.updatedAt,
      anchors: Array.from({ length: 12 }, (_, index) =>
        createChannelPreanalysisVisualAnchorDescriptor({
          timestampMs: (index + 1) * 9_000,
          luma: frameLuma(index),
        }),
      ),
    });
    const fingerprintText =
      serializeChannelPreanalysisVisualFingerprint(fingerprint);
    const fingerprintBytes = new TextEncoder().encode(fingerprintText);
    const fingerprintArtifact = {
      artifactId:
        `youtube-storyboard-visual-fingerprint:${VIDEO_ID}:v1`,
      videoId: VIDEO_ID,
      kind: "fingerprint" as const,
      revision: 1,
      storageKey:
        `amoretto-vods/videos/${VIDEO_ID}.visual-fingerprint.v1.json`,
      contentDigest:
        `sha256:${createHash("sha256").update(fingerprintBytes).digest("hex")}`,
      byteLength: fingerprintBytes.byteLength,
      createdAt: fingerprint.createdAt,
    };
    const preparedManifest: ChannelPreanalysisCatalogManifest = {
      ...baseManifest,
      videos: [
        {
          ...baseManifest.videos[0]!,
          artifactIds: [ARTIFACT_ID, fingerprintArtifact.artifactId],
        },
      ],
      artifacts: [...baseManifest.artifacts, fingerprintArtifact],
    };
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      if (url.endsWith("catalog.json")) {
        return Promise.resolve(
          new Response(JSON.stringify(preparedManifest), { status: 200 }),
        );
      }
      if (url.endsWith(".visual-fingerprint.v1.json")) {
        return Promise.resolve(
          new Response(fingerprintText, { status: 200 }),
        );
      }
      if (url.endsWith(`${VIDEO_ID}.v1.json`)) {
        return Promise.resolve(
          new Response(preparedBundle, { status: 200 }),
        );
      }
      return Promise.resolve(new Response("", { status: 404 }));
    });
    const lookup = await requestChannelPreanalysisMatch(
      { title: "completely-renamed-upload.mp4", durationMs: DURATION_MS },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(lookup.match.match).toBeNull();

    const cohort =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        lookup,
        DURATION_MS,
        { fetchImplementation },
      );
    expect(cohort.status).toBe("ready");
    const plan = buildChannelPreanalysisLocalVisualCohortSamplingPlan(
      cohort.fingerprints,
    );
    expect(plan).toHaveLength(12);
    const resolved =
      await resolveChannelPreanalysisLookupByVisualFingerprintCohort(
        lookup,
        cohort,
        {
          durationMs: DURATION_MS,
          samples: plan.map((timestampMs, index) => ({
            timestampMs,
            luma: frameLuma(index),
          })),
        },
        { fetchImplementation },
      );

    expect(resolved.status).toBe("verified");
    expect(resolved.lookup.match).toMatchObject({
      confidence: "exact",
      reason: "visual-fingerprint-consensus",
      match: { videoId: VIDEO_ID },
    });
    expect(resolved.lookup.bundleStatus).toBe("loaded");
    expect(resolved.lookup.bundle?.videoId).toBe(VIDEO_ID);
  });

  it("keeps an incomplete duration cohort partial and forbids exact promotion", async () => {
    const preparedBundle = await bundleJson();
    const baseManifest = manifest(preparedBundle);
    const { fingerprintText, artifact } = visualFingerprintFixture();
    const fingerprintedVideo = {
      ...baseManifest.videos[0]!,
      artifactIds: [ARTIFACT_ID, artifact.artifactId],
    };
    const missingVideoId = "EZfCGS5ms_Q";
    const missingFingerprintVideo = {
      ...baseManifest.videos[0]!,
      videoId: missingVideoId,
      title: "같은 길이의 다른 방송",
      normalizedTitle: normalizeChannelVideoTitle("같은 길이의 다른 방송"),
      watchUrl: `https://www.youtube.com/watch?v=${missingVideoId}`,
      state: "discovered" as const,
      artifactIds: [],
    };
    const partialManifest: ChannelPreanalysisCatalogManifest = {
      ...baseManifest,
      videos: [fingerprintedVideo, missingFingerprintVideo],
      artifacts: [...baseManifest.artifacts, artifact],
    };
    const lookup: ChannelPreanalysisLookupResult = {
      manifest: partialManifest,
      manifestSource: "bundled",
      manifestBaseUrl: BUNDLED_BASE,
      match: {
        confidence: "none",
        reason: "no-match",
        ambiguous: false,
        match: null,
        candidates: [],
      },
      bundleStatus: "not-exact",
      bundle: null,
      bundleArtifact: null,
    };
    const unusedFetch = vi.fn(() =>
      Promise.resolve(new Response(fingerprintText, { status: 200 })),
    );

    const partial =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        lookup,
        DURATION_MS,
        { fetchImplementation: unusedFetch },
      );
    expect(partial).toMatchObject({
      status: "partial",
      videos: [
        { videoId: VIDEO_ID },
        { videoId: missingVideoId },
      ],
      fingerprints: [],
    });
    expect(unusedFetch).not.toHaveBeenCalled();
    await expect(
      resolveChannelPreanalysisLookupByVisualFingerprintCohort(
        lookup,
        partial,
        { durationMs: DURATION_MS, samples: [] },
      ),
    ).resolves.toMatchObject({
      status: "none",
      lookup: {
        match: {
          confidence: "none",
          match: null,
        },
      },
    });

    const completeLookup: ChannelPreanalysisLookupResult = {
      ...lookup,
      manifest: {
        ...partialManifest,
        videos: [fingerprintedVideo],
      },
    };
    const unavailable =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        completeLookup,
        DURATION_MS,
        {
          fetchImplementation: () =>
            Promise.resolve(new Response("", { status: 503 })),
        },
      );
    expect(unavailable).toMatchObject({
      status: "partial",
      videos: [{ videoId: VIDEO_ID }],
      fingerprints: [],
    });
    const unverifiable =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        completeLookup,
        DURATION_MS,
        {
          fetchImplementation: () =>
            Promise.resolve(
              new Response(`${fingerprintText} `, { status: 200 }),
            ),
        },
      );
    expect(unverifiable).toMatchObject({
      status: "partial",
      videos: [{ videoId: VIDEO_ID }],
      fingerprints: [],
    });
  });

  it("never returns a fetched bundle whose transcript digest was altered", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const parsed = JSON.parse(preparedBundle) as {
      captionTrack: { events: { text: string }[] };
    };
    parsed.captionTrack.events[0]!.text = "변조된 대사";
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : JSON.stringify(parsed),
          { status: 200 },
        ),
      );
    });
    await expect(
      fetchChannelPreanalysisBundle(VIDEO_ID, {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      }),
    ).rejects.toMatchObject({ code: "INVALID_BUNDLE" });
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("preserves an exact manifest identity when its bundle is unavailable", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        url.endsWith("catalog.json")
          ? new Response(JSON.stringify(preparedManifest), { status: 200 })
          : new Response("", { status: 503 }),
      );
    });
    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.match).toMatchObject({
      confidence: "exact",
      match: { videoId: VIDEO_ID },
    });
    expect(result.bundleStatus).toBe("unavailable");
    expect(result.bundle).toBeNull();
  });

  it("verifies the full raw artifact before accepting unchanged transcript data", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const parsed = JSON.parse(preparedBundle) as {
      chapters: { summaryKo: string }[];
    };
    parsed.chapters[0]!.summaryKo = "다른 이야기";
    const mutatedBundle = JSON.stringify(parsed);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : mutatedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.bundleStatus).toBe("unavailable");
    expect(result.bundle).toBeNull();
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("falls back only as one manifest-and-bundle source pair", async () => {
    const validBundle = await bundleJson();
    const wrongBundle = await bundleJson({
      videoId: "AbCdEfGhI12",
      title: "다른 영상",
    });
    const rawManifest = manifest(wrongBundle);
    const bundledManifest = manifest(validBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      const isRaw = url.startsWith(RAW_BASE);
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(isRaw ? rawManifest : bundledManifest)
            : isRaw
              ? wrongBundle
              : validBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.bundleStatus).toBe("loaded");
    expect(result.manifestSource).toBe("bundled");
    expect(result.bundle?.videoId).toBe(VIDEO_ID);
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("hard-clamps caller-provided response limits before bundle fetch", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn();
    await expect(
      fetchChannelPreanalysisBundle(
        VIDEO_ID,
        {
          fetchImplementation,
          bundleMaxBytes: CHANNEL_PREANALYSIS_BUNDLE_MAX_BYTES + 1,
        },
        {
          source: "raw",
          baseUrl: RAW_BASE,
          manifest: preparedManifest,
        },
      ),
    ).rejects.toMatchObject({ code: "TOO_LARGE" });
    expect(fetchImplementation).not.toHaveBeenCalled();

    const manifestFetch = vi.fn();
    await expect(
      fetchChannelPreanalysisManifest({
        fetchImplementation: manifestFetch,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
        manifestMaxBytes: CHANNEL_PREANALYSIS_MANIFEST_MAX_BYTES + 1,
      }),
    ).rejects.toMatchObject({ code: "FETCH_FAILED" });
    expect(manifestFetch).not.toHaveBeenCalled();
  });

  it("rejects non-canonical storage keys and global fingerprint reuse", async () => {
    const preparedBundle = await bundleJson();
    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify(
          manifest(preparedBundle, {
            artifactOverrides: {
              storageKey:
                "amoretto-vods/videos/%2e%2e/KzAW3yow80Q.json",
            },
          }),
        ),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));

    const fingerprint =
      `local-file-sampled-sha256-v1:${"a".repeat(64)}` as const;
    const duplicateVideo = {
      channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
      videoId: "AbCdEfGhI12",
      title: "다른 영상",
      normalizedTitle: normalizeChannelVideoTitle("다른 영상"),
      durationMs: DURATION_MS,
      publishedAt: "2026-07-18T04:00:00.000Z",
      updatedAt: "2026-07-30T00:00:00.000Z",
      watchUrl: "https://www.youtube.com/watch?v=AbCdEfGhI12",
      state: "discovered" as const,
      revision: 1,
      artifactIds: [],
      registeredLocalSampledFingerprints: [
        {
          value: fingerprint,
          registeredAt: "2026-07-30T00:00:00.000Z",
        },
      ],
      retry: null,
    };
    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify(
          manifest(preparedBundle, {
            videoOverrides: {
              registeredLocalSampledFingerprints: [
                {
                  value: fingerprint,
                  registeredAt: "2026-07-30T00:00:00.000Z",
                },
              ],
            },
            additionalVideos: [duplicateVideo],
          }),
        ),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
  });

  it("strictly rejects retryable records without their retry checkpoint", async () => {
    const invalid = manifest(await bundleJson());
    const videos = invalid.videos.map((video) => ({
      ...video,
      state: "retryable" as const,
      retry: null,
    }));
    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify({ ...invalid, videos }),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
  });
});
