import { describe, expect, it } from "vitest";

import {
  BROADCAST_CONTEXT_SCHEMA_VERSION,
  type BroadcastContextResult,
} from "./broadcastContextProtocol";
import {
  CHANNEL_PREANALYSIS_CONTEXT_RECEIPT_FIELD_MAX_LENGTH,
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
  parseChannelPreanalysisBundle,
  verifyChannelPreanalysisTranscriptDigest,
  type ChannelPreanalysisBundle,
  type ChannelPreanalysisBundleValidationError,
} from "./channelPreanalysisBundle";
import { AI_BROADCAST_CONTEXT_ROUTING_REVISION } from "./aiModelRoutingPolicy";
import { AMORETTO_CHANNEL_PREANALYSIS_SOURCE } from "./channelPreanalysisSources";

const VIDEO_ID = "KzAW3yow80Q";
const DURATION_MS = 120_000;
const CONTEXT_PROVENANCE = {
  generatedAt: "2026-07-30T00:01:00.000Z",
  modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
  contextReceipt: {
    contractVersion: "2.0.0",
    routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
    modelId: "qwen3.7-plus",
    modelRevision:
      "qwen3.7-plus-context-editorial-jury-topic-balanced-2026-07-22",
  },
  evidenceScope: "youtube-caption-transcript-only",
  localVisualVerificationRequired: true,
} as const;

function compositeContextReceipt() {
  const overview = CONTEXT_PROVENANCE.contextReceipt;
  return {
    ...overview,
    componentReceipts: Array.from({ length: 4 }, (_, componentIndex) => ({
      componentIndex,
      analysisMode: componentIndex === 0 ? "overview" : "discovery",
      contractVersion: overview.contractVersion,
      routingRevision: overview.routingRevision,
      modelId: componentIndex === 0 ? overview.modelId : "qwen3.6-flash",
      modelRevision:
        componentIndex === 0
          ? overview.modelRevision
          : "qwen3.6-flash-context-discovery-2026-08-02",
      operationId: `channel-context-amoretto-vods-${String(componentIndex + 1).repeat(64)}`,
      payloadDigest: `sha256:${String(componentIndex + 5).repeat(64)}`,
      workerAttempt: componentIndex + 1,
      retryRisk:
        componentIndex === 0
          ? "possible-duplicate-provider-charge"
          : null,
    })),
  } as const;
}

async function validBundle(): Promise<ChannelPreanalysisBundle> {
  return createChannelPreanalysisBundle({
    channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
    videoId: VIDEO_ID,
    title: "2026 07 17 - 음식 토크",
    durationMs: DURATION_MS,
    publishedAt: "2026-07-17T04:00:00.000Z",
    catalogRevision: 1,
    state: "transcript-ready",
    captionTrack: {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: true,
      events: [
        { startMs: 1_000, durationMs: 2_000, text: "칼국수 이야기" },
        { startMs: 62_000, durationMs: 2_000, text: "두바이 초콜릿 이야기" },
      ],
    },
    chapters: [
      {
        chapterId: "youtube-001",
        startMs: 0,
        endMs: 60_000,
        evidenceMode: "complete-transcript",
        evidenceCoverageRatio: 1,
        summaryKo: "칼국수 이야기",
      },
      {
        chapterId: "youtube-002",
        startMs: 60_000,
        endMs: DURATION_MS,
        evidenceMode: "complete-transcript",
        evidenceCoverageRatio: 1,
        summaryKo: "두바이 초콜릿 이야기",
      },
    ],
    broadcastContext: null,
    provenance: createDefaultChannelPreanalysisProvenance(
      VIDEO_ID,
      "2026-07-30T00:00:00.000Z",
    ),
  });
}

function validContext(
  discoveredLeads: BroadcastContextResult["discoveredLeads"] = [],
): BroadcastContextResult {
  return {
    schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
    broadcastSummaryKo: "방송 전체 흐름을 정리한 내용입니다.",
    hostStreamerProfile: null,
    recurringThemesKo: [],
    annotations: [],
    semanticChaptersSupported: true,
    semanticChapters: [],
    discoveredLeadsSupported: true,
    discoveredLeads,
    coverage: {
      status: "complete",
      coveredMs: DURATION_MS,
      coverageRatio: 1,
      gaps: [],
      partialChapterIds: [],
    },
  };
}

describe("channelPreanalysisBundle", () => {
  it("creates and parses one strict digest-bound bundle", async () => {
    const bundle = await validBundle();
    expect(bundle.transcriptDigest).toMatch(/^sha256:[0-9a-f]{64}$/u);
    expect(parseChannelPreanalysisBundle(JSON.stringify(bundle))).toEqual(bundle);
    await expect(
      verifyChannelPreanalysisTranscriptDigest(bundle),
    ).resolves.toBeUndefined();
  });

  it("rejects a chapter map with a hidden coverage gap", async () => {
    const bundle = await validBundle();
    const invalid = {
      ...bundle,
      chapters: [
        bundle.chapters[0],
        { ...bundle.chapters[1], startMs: 61_000 },
      ],
    };
    expect(() => parseChannelPreanalysisBundle(JSON.stringify(invalid))).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CHAPTERS",
      }),
    );
  });

  it("rejects unknown fields instead of silently widening schema v1", async () => {
    const bundle = await validBundle();
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({ ...bundle, unreviewedData: "hidden" }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_SCHEMA",
      }),
    );
  });

  it("detects transcript mutation after publication", async () => {
    const bundle = await validBundle();
    const mutated = {
      ...bundle,
      captionTrack: {
        ...bundle.captionTrack,
        events: [
          { ...bundle.captionTrack.events[0]!, text: "변조된 대사" },
          ...bundle.captionTrack.events.slice(1),
        ],
      },
    } satisfies ChannelPreanalysisBundle;
    await expect(
      verifyChannelPreanalysisTranscriptDigest(mutated),
    ).rejects.toMatchObject({ code: "DIGEST_MISMATCH" });
  });

  it("requires lifecycle state and broadcast context to agree", async () => {
    const bundle = await validBundle();
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({ ...bundle, state: "context-ready" }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          broadcastContext: validContext(),
        }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
    expect(
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          state: "context-ready",
          broadcastContext: validContext(),
          contextProvenance: CONTEXT_PROVENANCE,
        }),
      ).state,
    ).toBe("context-ready");
  });

  it("preserves a bounded exact-key scheduled context receipt", async () => {
    const bundle = await validBundle();
    const contextReady = {
      ...bundle,
      state: "context-ready",
      broadcastContext: validContext(),
      contextProvenance: CONTEXT_PROVENANCE,
    };
    expect(
      parseChannelPreanalysisBundle(JSON.stringify(contextReady))
        .contextProvenance?.contextReceipt,
    ).toEqual(CONTEXT_PROVENANCE.contextReceipt);

    const oversizedReceipt = {
      ...contextReady,
      contextProvenance: {
        ...CONTEXT_PROVENANCE,
        contextReceipt: {
          ...CONTEXT_PROVENANCE.contextReceipt,
          modelRevision: "a".repeat(
            CHANNEL_PREANALYSIS_CONTEXT_RECEIPT_FIELD_MAX_LENGTH + 1,
          ),
        },
      },
    };
    expect(() =>
      parseChannelPreanalysisBundle(JSON.stringify(oversizedReceipt)),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );

    const missingReceipt = {
      ...contextReady,
      contextProvenance: {
        generatedAt: CONTEXT_PROVENANCE.generatedAt,
        modelRoutingRevision:
          CONTEXT_PROVENANCE.modelRoutingRevision,
        evidenceScope: CONTEXT_PROVENANCE.evidenceScope,
        localVisualVerificationRequired:
          CONTEXT_PROVENANCE.localVisualVerificationRequired,
      },
    };
    expect(() =>
      parseChannelPreanalysisBundle(JSON.stringify(missingReceipt)),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );

    const widenedReceipt = {
      ...contextReady,
      contextProvenance: {
        ...CONTEXT_PROVENANCE,
        contextReceipt: {
          ...CONTEXT_PROVENANCE.contextReceipt,
          unverifiedProvider: "qwen",
        },
      },
    };
    expect(() =>
      parseChannelPreanalysisBundle(JSON.stringify(widenedReceipt)),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
  });

  it("preserves every ordered context component receipt and rejects incomplete or forged sets", async () => {
    const bundle = await validBundle();
    const contextReceipt = compositeContextReceipt();
    const contextReady = {
      ...bundle,
      chapters: Array.from({ length: 4 }, (_, index) => ({
        chapterId: `youtube-component-${index + 1}`,
        startMs: index * 30_000,
        endMs: (index + 1) * 30_000,
        evidenceMode: "complete-transcript",
        evidenceCoverageRatio: 1,
        summaryKo: `구간 ${index + 1}`,
      })),
      state: "context-ready",
      broadcastContext: validContext(),
      contextProvenance: {
        ...CONTEXT_PROVENANCE,
        contextReceipt,
      },
    };
    expect(
      parseChannelPreanalysisBundle(JSON.stringify(contextReady))
        .contextProvenance?.contextReceipt,
    ).toEqual(contextReceipt);

    const legacyComponentReceipts = contextReceipt.componentReceipts.map(
      ({
        componentIndex,
        analysisMode,
        contractVersion,
        routingRevision,
        modelId,
        modelRevision,
        operationId,
        payloadDigest,
      }) => ({
        componentIndex,
        analysisMode,
        contractVersion,
        routingRevision,
        modelId,
        modelRevision,
        operationId,
        payloadDigest,
      }),
    );
    expect(
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...contextReady,
          contextProvenance: {
            ...contextReady.contextProvenance,
            contextReceipt: {
              ...contextReceipt,
              componentReceipts: legacyComponentReceipts,
            },
          },
        }),
      ).contextProvenance?.contextReceipt.componentReceipts,
    ).toEqual(legacyComponentReceipts);

    const expectInvalid = (componentReceipts: readonly unknown[]) => {
      expect(() =>
        parseChannelPreanalysisBundle(
          JSON.stringify({
            ...contextReady,
            contextProvenance: {
              ...contextReady.contextProvenance,
              contextReceipt: { ...contextReceipt, componentReceipts },
            },
          }),
        ),
      ).toThrowError(
        expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
          code: "INVALID_CONTEXT",
        }),
      );
    };

    expectInvalid(contextReceipt.componentReceipts.slice(0, 3));
    expectInvalid([
      ...contextReceipt.componentReceipts,
      contextReceipt.componentReceipts[3],
    ]);
    expectInvalid([
      contextReceipt.componentReceipts[0],
      contextReceipt.componentReceipts[2],
      contextReceipt.componentReceipts[1],
      contextReceipt.componentReceipts[3],
    ]);
    expectInvalid([
      contextReceipt.componentReceipts[0],
      contextReceipt.componentReceipts[1],
      {
        ...contextReceipt.componentReceipts[2],
        operationId: contextReceipt.componentReceipts[1]!.operationId,
      },
      contextReceipt.componentReceipts[3],
    ]);
    expectInvalid([
      contextReceipt.componentReceipts[0],
      {
        ...contextReceipt.componentReceipts[1],
        contractVersion: "forged-contract",
      },
      contextReceipt.componentReceipts[2],
      contextReceipt.componentReceipts[3],
    ]);
    expectInvalid(
      contextReceipt.componentReceipts.map((receipt, index) =>
        index === 1 ? { ...receipt, workerAttempt: 0 } : receipt,
      ),
    );
    expectInvalid(
      contextReceipt.componentReceipts.map((receipt, index) =>
        index === 1
          ? { ...receipt, workerAttempt: 1_000_000_000 }
          : receipt,
      ),
    );
    expectInvalid(
      contextReceipt.componentReceipts.map((receipt, index) =>
        index === 1 ? { ...receipt, retryRisk: "unknown-risk" } : receipt,
      ),
    );
    expectInvalid(
      legacyComponentReceipts.map((receipt, index) =>
        index === 1 ? { ...receipt, workerAttempt: 2 } : receipt,
      ),
    );
  });

  it("keeps a final cue that overhangs by the duration truncation, and its digest still verifies", async () => {
    // Measured on VFCOVyDeWWk: one event of 6,085 ended 44ms past a duration
    // YouTube reports in whole seconds. The whole broadcast was being rejected
    // on every scheduled retry because of it.
    const overhanging = {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: true,
      events: [
        { startMs: 1_000, durationMs: 2_000, text: "칼국수 이야기" },
        { startMs: DURATION_MS - 2_000, durationMs: 2_044, text: "마지막 대사" },
      ],
    } as const;
    const bundle = await createChannelPreanalysisBundle({
      ...(await validBundle()),
      captionTrack: overhanging,
    });
    const last = bundle.captionTrack.events.at(-1);
    // Stored verbatim. Normalising it here would leave the bytes disagreeing
    // with the digest taken over them, which is the failure this guards.
    expect(last?.durationMs).toBe(2_044);
    await expect(
      verifyChannelPreanalysisTranscriptDigest(bundle),
    ).resolves.toBeUndefined();
    const roundTripped = parseChannelPreanalysisBundle(JSON.stringify(bundle));
    expect(roundTripped.captionTrack.events.at(-1)?.durationMs).toBe(2_044);
    await expect(
      verifyChannelPreanalysisTranscriptDigest(roundTripped),
    ).resolves.toBeUndefined();
  });

  it("rejects caption and discovered-lead ranges beyond the source", async () => {
    const bundle = await validBundle();
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          captionTrack: {
            ...bundle.captionTrack,
            events: [
              {
                // Beyond what a whole-second duration truncation could ever
                // explain, which is what this bound exists to catch.
                startMs: DURATION_MS - 1_000,
                durationMs: 2_002,
                text: "영상 밖으로 넘어가는 자막",
              },
            ],
          },
        }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_TRANSCRIPT",
      }),
    );

    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          state: "context-ready",
          contextProvenance: CONTEXT_PROVENANCE,
          broadcastContext: validContext([
            {
              leadId: "lead-outside-source",
              startChapterId: "youtube-001",
              endChapterId: "youtube-002",
              startMs: DURATION_MS - 1_000,
              endMs: DURATION_MS + 1,
              category: "reaction",
              confidence: 0.8,
              eventSummaryKo: "영상 끝을 넘는 사건",
              whyThisMomentKo: "경계 검증용 단서",
              evidenceCueKo: "영상 밖 시간",
              uncertaintiesKo: [],
            },
          ]),
        }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
  });

  it(
    "refuses a producer payload whose pretty JSON exceeds 32 MiB",
    async () => {
      const oversizedText = "😀".repeat(200);
      const events = Array.from({ length: 40_000 }, (_, index) => ({
        startMs: index,
        durationMs: 0,
        text: oversizedText,
      }));
      await expect(
        createChannelPreanalysisBundle({
          channelId: AMORETTO_CHANNEL_PREANALYSIS_SOURCE.channelId,
          videoId: VIDEO_ID,
          title: "큰 자막 묶음",
          durationMs: DURATION_MS,
          publishedAt: "2026-07-17T04:00:00.000Z",
          catalogRevision: 1,
          state: "transcript-ready",
          captionTrack: {
            videoId: VIDEO_ID,
            languageCode: "ko",
            isAutoGenerated: true,
            events,
          },
          chapters: [
            {
              chapterId: "youtube-001",
              startMs: 0,
              endMs: DURATION_MS,
              evidenceMode: "complete-transcript",
              evidenceCoverageRatio: 1,
              summaryKo: "크기 경계 검증",
            },
          ],
          broadcastContext: null,
          provenance: createDefaultChannelPreanalysisProvenance(
            VIDEO_ID,
            "2026-07-30T00:00:00.000Z",
          ),
        }),
      ).rejects.toMatchObject({ code: "TOO_LARGE" });
    },
    30_000,
  );
});
