import { describe, expect, it } from "vitest";

import {
  BROADCAST_CONTEXT_SCHEMA_VERSION,
  type BroadcastContextResult,
} from "./broadcastContextProtocol";
import {
  CHANNEL_PREANALYSIS_CONTEXT_RECEIPT_FIELD_MAX_LENGTH,
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
  parseChannelPreanalysisBundle,
  verifyChannelPreanalysisTranscriptDigest,
  type ChannelPreanalysisBundle,
  type ChannelPreanalysisBundleValidationError,
} from "./channelPreanalysisBundle";
import { AI_BROADCAST_CONTEXT_ROUTING_REVISION } from "./aiModelRoutingPolicy";

const VIDEO_ID = "KzAW3yow80Q";
const DURATION_MS = 120_000;
const CONTEXT_PROVENANCE = {
  generatedAt: "2026-07-30T00:01:00.000Z",
  modelRoutingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
  contextReceipt: {
    contractVersion: "2.0.0",
    routingRevision: AI_BROADCAST_CONTEXT_ROUTING_REVISION,
    modelId: "qwen3.7-plus",
    modelRevision:
      "qwen3.7-plus-context-editorial-jury-topic-balanced-2026-07-22",
  },
  evidenceScope: "youtube-caption-transcript-only",
  localVisualVerificationRequired: true,
} as const;

async function validBundle(): Promise<ChannelPreanalysisBundle> {
  return createChannelPreanalysisBundle({
    videoId: VIDEO_ID,
    title: "2026 07 17 - 음식 토크",
    durationMs: DURATION_MS,
    publishedAt: "2026-07-17T04:00:00.000Z",
    catalogRevision: 1,
    state: "transcript-ready",
    captionTrack: {
      videoId: VIDEO_ID,
      languageCode: "ko",
      isAutoGenerated: true,
      events: [
        { startMs: 1_000, durationMs: 2_000, text: "칼국수 이야기" },
        { startMs: 62_000, durationMs: 2_000, text: "두바이 초콜릿 이야기" },
      ],
    },
    chapters: [
      {
        chapterId: "youtube-001",
        startMs: 0,
        endMs: 60_000,
        evidenceMode: "complete-transcript",
        evidenceCoverageRatio: 1,
        summaryKo: "칼국수 이야기",
      },
      {
        chapterId: "youtube-002",
        startMs: 60_000,
        endMs: DURATION_MS,
        evidenceMode: "complete-transcript",
        evidenceCoverageRatio: 1,
        summaryKo: "두바이 초콜릿 이야기",
      },
    ],
    broadcastContext: null,
    provenance: createDefaultChannelPreanalysisProvenance(
      VIDEO_ID,
      "2026-07-30T00:00:00.000Z",
    ),
  });
}

function validContext(
  discoveredLeads: BroadcastContextResult["discoveredLeads"] = [],
): BroadcastContextResult {
  return {
    schemaVersion: BROADCAST_CONTEXT_SCHEMA_VERSION,
    broadcastSummaryKo: "방송 전체 흐름을 정리한 내용입니다.",
    hostStreamerProfile: null,
    recurringThemesKo: [],
    annotations: [],
    semanticChaptersSupported: true,
    semanticChapters: [],
    discoveredLeadsSupported: true,
    discoveredLeads,
    coverage: {
      status: "complete",
      coveredMs: DURATION_MS,
      coverageRatio: 1,
      gaps: [],
      partialChapterIds: [],
    },
  };
}

describe("channelPreanalysisBundle", () => {
  it("creates and parses one strict digest-bound bundle", async () => {
    const bundle = await validBundle();
    expect(bundle.transcriptDigest).toMatch(/^sha256:[0-9a-f]{64}$/u);
    expect(parseChannelPreanalysisBundle(JSON.stringify(bundle))).toEqual(bundle);
    await expect(
      verifyChannelPreanalysisTranscriptDigest(bundle),
    ).resolves.toBeUndefined();
  });

  it("rejects a chapter map with a hidden coverage gap", async () => {
    const bundle = await validBundle();
    const invalid = {
      ...bundle,
      chapters: [
        bundle.chapters[0],
        { ...bundle.chapters[1], startMs: 61_000 },
      ],
    };
    expect(() => parseChannelPreanalysisBundle(JSON.stringify(invalid))).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CHAPTERS",
      }),
    );
  });

  it("rejects unknown fields instead of silently widening schema v1", async () => {
    const bundle = await validBundle();
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({ ...bundle, unreviewedData: "hidden" }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_SCHEMA",
      }),
    );
  });

  it("detects transcript mutation after publication", async () => {
    const bundle = await validBundle();
    const mutated = {
      ...bundle,
      captionTrack: {
        ...bundle.captionTrack,
        events: [
          { ...bundle.captionTrack.events[0]!, text: "변조된 대사" },
          ...bundle.captionTrack.events.slice(1),
        ],
      },
    } satisfies ChannelPreanalysisBundle;
    await expect(
      verifyChannelPreanalysisTranscriptDigest(mutated),
    ).rejects.toMatchObject({ code: "DIGEST_MISMATCH" });
  });

  it("requires lifecycle state and broadcast context to agree", async () => {
    const bundle = await validBundle();
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({ ...bundle, state: "context-ready" }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          broadcastContext: validContext(),
        }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
    expect(
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          state: "context-ready",
          broadcastContext: validContext(),
          contextProvenance: CONTEXT_PROVENANCE,
        }),
      ).state,
    ).toBe("context-ready");
  });

  it("preserves a bounded exact-key scheduled context receipt", async () => {
    const bundle = await validBundle();
    const contextReady = {
      ...bundle,
      state: "context-ready",
      broadcastContext: validContext(),
      contextProvenance: CONTEXT_PROVENANCE,
    };
    expect(
      parseChannelPreanalysisBundle(JSON.stringify(contextReady))
        .contextProvenance?.contextReceipt,
    ).toEqual(CONTEXT_PROVENANCE.contextReceipt);

    const oversizedReceipt = {
      ...contextReady,
      contextProvenance: {
        ...CONTEXT_PROVENANCE,
        contextReceipt: {
          ...CONTEXT_PROVENANCE.contextReceipt,
          modelRevision: "a".repeat(
            CHANNEL_PREANALYSIS_CONTEXT_RECEIPT_FIELD_MAX_LENGTH + 1,
          ),
        },
      },
    };
    expect(() =>
      parseChannelPreanalysisBundle(JSON.stringify(oversizedReceipt)),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );

    const missingReceipt = {
      ...contextReady,
      contextProvenance: {
        generatedAt: CONTEXT_PROVENANCE.generatedAt,
        modelRoutingRevision:
          CONTEXT_PROVENANCE.modelRoutingRevision,
        evidenceScope: CONTEXT_PROVENANCE.evidenceScope,
        localVisualVerificationRequired:
          CONTEXT_PROVENANCE.localVisualVerificationRequired,
      },
    };
    expect(() =>
      parseChannelPreanalysisBundle(JSON.stringify(missingReceipt)),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );

    const widenedReceipt = {
      ...contextReady,
      contextProvenance: {
        ...CONTEXT_PROVENANCE,
        contextReceipt: {
          ...CONTEXT_PROVENANCE.contextReceipt,
          unverifiedProvider: "qwen",
        },
      },
    };
    expect(() =>
      parseChannelPreanalysisBundle(JSON.stringify(widenedReceipt)),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
  });

  it("keeps a final cue that overhangs by the duration truncation, clamped to the source", async () => {
    // Measured on VFCOVyDeWWk: one event of 6,085 ended 44ms past a duration
    // YouTube reports in whole seconds. The whole broadcast was being rejected
    // on every scheduled retry because of it.
    const bundle = await validBundle();
    const parsed = parseChannelPreanalysisBundle(
      JSON.stringify({
        ...bundle,
        captionTrack: {
          ...bundle.captionTrack,
          events: [
            {
              startMs: DURATION_MS - 2_000,
              durationMs: 2_044,
              text: "마지막 대사",
            },
          ],
        },
      }),
    );
    const [event] = parsed.captionTrack.events;
    expect(event?.startMs).toBe(DURATION_MS - 2_000);
    expect(event?.durationMs).toBe(2_000);
    expect(event!.startMs + event!.durationMs).toBe(DURATION_MS);
  });

  it("rejects caption and discovered-lead ranges beyond the source", async () => {
    const bundle = await validBundle();
    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          captionTrack: {
            ...bundle.captionTrack,
            events: [
              {
                // Beyond what a whole-second duration truncation could ever
                // explain, which is what this bound exists to catch.
                startMs: DURATION_MS - 1_000,
                durationMs: 2_002,
                text: "영상 밖으로 넘어가는 자막",
              },
            ],
          },
        }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_TRANSCRIPT",
      }),
    );

    expect(() =>
      parseChannelPreanalysisBundle(
        JSON.stringify({
          ...bundle,
          state: "context-ready",
          contextProvenance: CONTEXT_PROVENANCE,
          broadcastContext: validContext([
            {
              leadId: "lead-outside-source",
              startChapterId: "youtube-001",
              endChapterId: "youtube-002",
              startMs: DURATION_MS - 1_000,
              endMs: DURATION_MS + 1,
              category: "reaction",
              confidence: 0.8,
              eventSummaryKo: "영상 끝을 넘는 사건",
              whyThisMomentKo: "경계 검증용 단서",
              evidenceCueKo: "영상 밖 시간",
              uncertaintiesKo: [],
            },
          ]),
        }),
      ),
    ).toThrowError(
      expect.objectContaining<Partial<ChannelPreanalysisBundleValidationError>>({
        code: "INVALID_CONTEXT",
      }),
    );
  });

  it(
    "refuses a producer payload whose pretty JSON exceeds 32 MiB",
    async () => {
      const oversizedText = "😀".repeat(200);
      const events = Array.from({ length: 40_000 }, (_, index) => ({
        startMs: index,
        durationMs: 0,
        text: oversizedText,
      }));
      await expect(
        createChannelPreanalysisBundle({
          videoId: VIDEO_ID,
          title: "큰 자막 묶음",
          durationMs: DURATION_MS,
          publishedAt: "2026-07-17T04:00:00.000Z",
          catalogRevision: 1,
          state: "transcript-ready",
          captionTrack: {
            videoId: VIDEO_ID,
            languageCode: "ko",
            isAutoGenerated: true,
            events,
          },
          chapters: [
            {
              chapterId: "youtube-001",
              startMs: 0,
              endMs: DURATION_MS,
              evidenceMode: "complete-transcript",
              evidenceCoverageRatio: 1,
              summaryKo: "크기 경계 검증",
            },
          ],
          broadcastContext: null,
          provenance: createDefaultChannelPreanalysisProvenance(
            VIDEO_ID,
            "2026-07-30T00:00:00.000Z",
          ),
        }),
      ).rejects.toMatchObject({ code: "TOO_LARGE" });
    },
    30_000,
  );
});
