import { createHash } from "node:crypto";

import { describe, expect, it, vi } from "vitest";

import {
  AMORETTO_YOUTUBE_CHANNEL_HANDLE,
  AMORETTO_YOUTUBE_CHANNEL_ID,
  normalizeChannelVideoTitle,
  type ChannelPreanalysisCatalogManifest,
} from "./channelPreanalysisCatalog";
import {
  CHANNEL_PREANALYSIS_BUNDLE_MAX_BYTES,
  createChannelPreanalysisBundle,
  createDefaultChannelPreanalysisProvenance,
} from "./channelPreanalysisBundle";
import {
  CHANNEL_PREANALYSIS_CATALOG_FILE,
  CHANNEL_PREANALYSIS_MANIFEST_MAX_BYTES,
  fetchChannelPreanalysisVisualFingerprintCohortForLookup,
  fetchChannelPreanalysisBundle,
  fetchChannelPreanalysisManifest,
  parseChannelPreanalysisManifest,
  requestChannelPreanalysisMatch,
  resolveChannelPreanalysisLookupByVisualFingerprintCohort,
  type ChannelPreanalysisLookupResult,
} from "./channelPreanalysisClient";
import {
  buildChannelPreanalysisLocalVisualCohortSamplingPlan,
  createChannelPreanalysisVisualAnchorDescriptor,
  createChannelPreanalysisVisualFingerprint,
  serializeChannelPreanalysisVisualFingerprint,
} from "./channelPreanalysisVisualFingerprint";

const VIDEO_ID = "KzAW3yow80Q";
const TITLE = "2026 07 17 - 음식 토크";
const DURATION_MS = 120_000;
const RAW_BASE = "https://catalog.test/amoretto/";
const BUNDLED_BASE = "/exclipper/preanalysis/amoretto/";
const ARTIFACT_ID = `youtube-caption-bundle:${VIDEO_ID}:v1`;

interface ManifestOptions {
  readonly videoOverrides?: Partial<
    ChannelPreanalysisCatalogManifest["videos"][number]
  >;
  readonly artifactOverrides?: Partial<
    ChannelPreanalysisCatalogManifest["artifacts"][number]
  >;
  readonly additionalVideos?: ChannelPreanalysisCatalogManifest["videos"];
}

function manifest(
  bundleText: string,
  options: ManifestOptions = {},
): ChannelPreanalysisCatalogManifest {
  const bundleBytes = new TextEncoder().encode(bundleText);
  const artifact = {
    artifactId: ARTIFACT_ID,
    videoId: VIDEO_ID,
    kind: "transcript" as const,
    revision: 1,
    storageKey: `amoretto-vods/videos/${VIDEO_ID}.v1.json`,
    contentDigest: `sha256:${createHash("sha256").update(bundleBytes).digest("hex")}`,
    byteLength: bundleBytes.byteLength,
    createdAt: "2026-07-30T00:00:00.000Z",
    ...options.artifactOverrides,
  };
  const video = {
    channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
    videoId: VIDEO_ID,
    title: TITLE,
    normalizedTitle: normalizeChannelVideoTitle(TITLE),
    durationMs: DURATION_MS,
    publishedAt: "2026-07-17T04:00:00.000Z",
    updatedAt: "2026-07-30T00:00:00.000Z",
    watchUrl: `https://www.youtube.com/watch?v=${VIDEO_ID}`,
    state: "transcript-ready" as const,
    revision: 1,
    artifactIds: [ARTIFACT_ID],
    registeredLocalSampledFingerprints: [],
    retry: null,
    ...options.videoOverrides,
  };
  return {
    schemaVersion: 1,
    channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
    channelHandle: AMORETTO_YOUTUBE_CHANNEL_HANDLE,
    revision: 1,
    generatedAt: "2026-07-30T00:00:00.000Z",
    videos: [video, ...(options.additionalVideos ?? [])],
    artifacts: [artifact],
  };
}

async function bundleJson(
  overrides: {
    readonly videoId?: string;
    readonly title?: string;
  } = {},
): Promise<string> {
  const videoId = overrides.videoId ?? VIDEO_ID;
  const title = overrides.title ?? TITLE;
  const bundle = await createChannelPreanalysisBundle({
    videoId,
    title,
    durationMs: DURATION_MS,
    publishedAt: "2026-07-17T04:00:00.000Z",
    catalogRevision: 1,
    state: "transcript-ready",
    captionTrack: {
      videoId,
      languageCode: "ko",
      isAutoGenerated: true,
      events: [{ startMs: 1_000, durationMs: 1_000, text: "음식 이야기" }],
    },
    chapters: [
      {
        chapterId: "youtube-001",
        startMs: 0,
        endMs: DURATION_MS,
        evidenceMode: "complete-transcript",
        evidenceCoverageRatio: 1,
        summaryKo: "음식 이야기",
      },
    ],
    broadcastContext: null,
    provenance: createDefaultChannelPreanalysisProvenance(
      videoId,
      "2026-07-30T00:00:00.000Z",
    ),
  });
  return JSON.stringify(bundle);
}

function visualFingerprintFixture(): {
  readonly fingerprintText: string;
  readonly artifact: ChannelPreanalysisCatalogManifest["artifacts"][number];
} {
  const frameLuma = (seed: number) =>
    Uint8Array.from(
      { length: 32 * 18 },
      (_, index) =>
        (index * (seed * 2 + 17) +
          Math.floor(index / 32) * (seed + 29) +
          seed * 43) %
        256,
    );
  const fingerprint = createChannelPreanalysisVisualFingerprint({
    videoId: VIDEO_ID,
    sourceDurationMs: DURATION_MS,
    createdAt: "2026-07-30T00:00:00.000Z",
    anchors: Array.from({ length: 12 }, (_, index) =>
      createChannelPreanalysisVisualAnchorDescriptor({
        timestampMs: (index + 1) * 9_000,
        luma: frameLuma(index),
      }),
    ),
  });
  const fingerprintText =
    serializeChannelPreanalysisVisualFingerprint(fingerprint);
  const fingerprintBytes = new TextEncoder().encode(fingerprintText);
  return {
    fingerprintText,
    artifact: {
      artifactId:
        `youtube-storyboard-visual-fingerprint:${VIDEO_ID}:v1`,
      videoId: VIDEO_ID,
      kind: "fingerprint",
      revision: 1,
      storageKey:
        `amoretto-vods/videos/${VIDEO_ID}.visual-fingerprint.v1.json`,
      contentDigest:
        `sha256:${createHash("sha256").update(fingerprintBytes).digest("hex")}`,
      byteLength: fingerprintBytes.byteLength,
      createdAt: fingerprint.createdAt,
    },
  };
}

describe("channelPreanalysisClient", () => {
  it("falls back from the raw branch catalog to the bundled Pages copy", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      if (url.startsWith(RAW_BASE)) {
        return Promise.resolve(new Response("", { status: 503 }));
      }
      return Promise.resolve(
        new Response(JSON.stringify(preparedManifest), { status: 200 }),
      );
    });
    const loaded = await fetchChannelPreanalysisManifest({
      fetchImplementation,
      rawBaseUrl: RAW_BASE,
      bundledBaseUrl: BUNDLED_BASE,
    });
    expect(loaded.source).toBe("bundled");
    expect(fetchImplementation).toHaveBeenNthCalledWith(
      1,
      `${RAW_BASE}${CHANNEL_PREANALYSIS_CATALOG_FILE}`,
      expect.any(Object),
    );
    expect(fetchImplementation).toHaveBeenNthCalledWith(
      2,
      `${BUNDLED_BASE}${CHANNEL_PREANALYSIS_CATALOG_FILE}`,
      expect.any(Object),
    );
  });

  it("loads and digest-verifies a bundle only for an exact identity", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });
    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.match.confidence).toBe("exact");
    expect(result.bundleStatus).toBe("loaded");
    expect(result.bundle?.videoId).toBe(VIDEO_ID);
    expect(result.bundleArtifact).toMatchObject({
      artifactId: ARTIFACT_ID,
      contentDigest: preparedManifest.artifacts[0]?.contentDigest,
    });
    expect(fetchImplementation).toHaveBeenCalledTimes(2);
  });

  it("loads the preserved transcript while context generation is retryable", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle, {
      videoOverrides: {
        state: "retryable",
        retry: {
          stage: "context",
          lastSuccessfulState: "transcript-ready",
          attemptCount: 1,
          nextAttemptAt: "2026-07-30T01:00:00.000Z",
          errorCode: "CONTEXT_OUTCOME_UNKNOWN",
        },
      },
    });
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );

    expect(result.match.match?.state).toBe("retryable");
    expect(result.match.match?.retry).toMatchObject({
      stage: "context",
      lastSuccessfulState: "transcript-ready",
    });
    expect(result.bundleStatus).toBe("loaded");
    expect(result.bundle?.state).toBe("transcript-ready");
    expect(result.bundle?.broadcastContext).toBeNull();
    expect(result.bundleArtifact?.artifactId).toBe(ARTIFACT_ID);
    expect(fetchImplementation).toHaveBeenCalledTimes(2);
  });

  it("uses a bundled ready snapshot while the raw catalog is still incomplete", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const rawManifest: ChannelPreanalysisCatalogManifest = {
      ...preparedManifest,
      videos: preparedManifest.videos.map((video) => ({
        ...video,
        durationMs: null,
        state: "discovered",
        artifactIds: [],
      })),
      artifacts: [],
    };
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      const isRaw = url.startsWith(RAW_BASE);
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(isRaw ? rawManifest : preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(result.bundle?.videoId).toBe(VIDEO_ID);
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("continues to bundled identity matching when raw has no match", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const rawManifest: ChannelPreanalysisCatalogManifest = {
      ...preparedManifest,
      videos: [],
      artifacts: [],
    };
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      const isRaw = url.startsWith(RAW_BASE);
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(isRaw ? rawManifest : preparedManifest)
            : preparedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("gives the bundled manifest a fresh deadline after raw stalls", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn(
      (input: RequestInfo | URL, init?: RequestInit) => {
        const url =
          typeof input === "string"
            ? input
            : input instanceof URL
              ? input.toString()
              : input.url;
        if (url === `${RAW_BASE}${CHANNEL_PREANALYSIS_CATALOG_FILE}`) {
          return new Promise<Response>((_resolve, reject) => {
            init?.signal?.addEventListener(
              "abort",
              () =>
                reject(
                  init.signal?.reason instanceof Error
                    ? init.signal.reason
                    : new Error("raw manifest aborted"),
                ),
              { once: true },
            );
          });
        }
        return Promise.resolve(
          new Response(
            url.endsWith("catalog.json")
              ? JSON.stringify(preparedManifest)
              : preparedBundle,
            { status: 200 },
          ),
        );
      },
    );

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
        manifestRequestTimeoutMs: 5,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("gives the bundled bundle a fresh deadline after raw bundle stalls", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn(
      (input: RequestInfo | URL, init?: RequestInit) => {
        const url =
          typeof input === "string"
            ? input
            : input instanceof URL
              ? input.toString()
              : input.url;
        if (
          url.startsWith(RAW_BASE) &&
          !url.endsWith(CHANNEL_PREANALYSIS_CATALOG_FILE)
        ) {
          return new Promise<Response>((_resolve, reject) => {
            init?.signal?.addEventListener(
              "abort",
              () =>
                reject(
                  init.signal?.reason instanceof Error
                    ? init.signal.reason
                    : new Error("raw bundle aborted"),
                ),
              { once: true },
            );
          });
        }
        return Promise.resolve(
          new Response(
            url.endsWith("catalog.json")
              ? JSON.stringify(preparedManifest)
              : preparedBundle,
            { status: 200 },
          ),
        );
      },
    );

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
        bundleRequestTimeoutMs: 5,
      },
    );

    expect(result.manifestSource).toBe("bundled");
    expect(result.bundleStatus).toBe("loaded");
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("returns a probable title-duration match without downloading its bundle", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn(() =>
      Promise.resolve(
        new Response(JSON.stringify(preparedManifest), { status: 200 }),
      ),
    );
    const result = await requestChannelPreanalysisMatch(
      { title: `${TITLE}.mp4`, durationMs: DURATION_MS + 1_000 },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.match.confidence).toBe("probable");
    expect(result.bundleStatus).toBe("not-exact");
    expect(result.bundle).toBeNull();
    expect(fetchImplementation).toHaveBeenCalledTimes(2);
  });

  it("promotes a completely renamed upload only after unique visual consensus", async () => {
    const preparedBundle = await bundleJson();
    const baseManifest = manifest(preparedBundle);
    const frameLuma = (seed: number) =>
      Uint8Array.from(
        { length: 32 * 18 },
        (_, index) =>
          (index * (seed * 2 + 17) +
            Math.floor(index / 32) * (seed + 29) +
            seed * 43) %
          256,
      );
    const fingerprint = createChannelPreanalysisVisualFingerprint({
      videoId: VIDEO_ID,
      sourceDurationMs: DURATION_MS,
      createdAt: baseManifest.videos[0]!.updatedAt,
      anchors: Array.from({ length: 12 }, (_, index) =>
        createChannelPreanalysisVisualAnchorDescriptor({
          timestampMs: (index + 1) * 9_000,
          luma: frameLuma(index),
        }),
      ),
    });
    const fingerprintText =
      serializeChannelPreanalysisVisualFingerprint(fingerprint);
    const fingerprintBytes = new TextEncoder().encode(fingerprintText);
    const fingerprintArtifact = {
      artifactId:
        `youtube-storyboard-visual-fingerprint:${VIDEO_ID}:v1`,
      videoId: VIDEO_ID,
      kind: "fingerprint" as const,
      revision: 1,
      storageKey:
        `amoretto-vods/videos/${VIDEO_ID}.visual-fingerprint.v1.json`,
      contentDigest:
        `sha256:${createHash("sha256").update(fingerprintBytes).digest("hex")}`,
      byteLength: fingerprintBytes.byteLength,
      createdAt: fingerprint.createdAt,
    };
    const preparedManifest: ChannelPreanalysisCatalogManifest = {
      ...baseManifest,
      videos: [
        {
          ...baseManifest.videos[0]!,
          artifactIds: [ARTIFACT_ID, fingerprintArtifact.artifactId],
        },
      ],
      artifacts: [...baseManifest.artifacts, fingerprintArtifact],
    };
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      if (url.endsWith("catalog.json")) {
        return Promise.resolve(
          new Response(JSON.stringify(preparedManifest), { status: 200 }),
        );
      }
      if (url.endsWith(".visual-fingerprint.v1.json")) {
        return Promise.resolve(
          new Response(fingerprintText, { status: 200 }),
        );
      }
      if (url.endsWith(`${VIDEO_ID}.v1.json`)) {
        return Promise.resolve(
          new Response(preparedBundle, { status: 200 }),
        );
      }
      return Promise.resolve(new Response("", { status: 404 }));
    });
    const lookup = await requestChannelPreanalysisMatch(
      { title: "completely-renamed-upload.mp4", durationMs: DURATION_MS },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(lookup.match.match).toBeNull();

    const cohort =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        lookup,
        DURATION_MS,
        { fetchImplementation },
      );
    expect(cohort.status).toBe("ready");
    const plan = buildChannelPreanalysisLocalVisualCohortSamplingPlan(
      cohort.fingerprints,
    );
    expect(plan).toHaveLength(12);
    const resolved =
      await resolveChannelPreanalysisLookupByVisualFingerprintCohort(
        lookup,
        cohort,
        {
          durationMs: DURATION_MS,
          samples: plan.map((timestampMs, index) => ({
            timestampMs,
            luma: frameLuma(index),
          })),
        },
        { fetchImplementation },
      );

    expect(resolved.status).toBe("verified");
    expect(resolved.lookup.match).toMatchObject({
      confidence: "exact",
      reason: "visual-fingerprint-consensus",
      match: { videoId: VIDEO_ID },
    });
    expect(resolved.lookup.bundleStatus).toBe("loaded");
    expect(resolved.lookup.bundle?.videoId).toBe(VIDEO_ID);
  });

  it("keeps an incomplete duration cohort partial and forbids exact promotion", async () => {
    const preparedBundle = await bundleJson();
    const baseManifest = manifest(preparedBundle);
    const { fingerprintText, artifact } = visualFingerprintFixture();
    const fingerprintedVideo = {
      ...baseManifest.videos[0]!,
      artifactIds: [ARTIFACT_ID, artifact.artifactId],
    };
    const missingVideoId = "EZfCGS5ms_Q";
    const missingFingerprintVideo = {
      ...baseManifest.videos[0]!,
      videoId: missingVideoId,
      title: "같은 길이의 다른 방송",
      normalizedTitle: normalizeChannelVideoTitle("같은 길이의 다른 방송"),
      watchUrl: `https://www.youtube.com/watch?v=${missingVideoId}`,
      state: "discovered" as const,
      artifactIds: [],
    };
    const partialManifest: ChannelPreanalysisCatalogManifest = {
      ...baseManifest,
      videos: [fingerprintedVideo, missingFingerprintVideo],
      artifacts: [...baseManifest.artifacts, artifact],
    };
    const lookup: ChannelPreanalysisLookupResult = {
      manifest: partialManifest,
      manifestSource: "bundled",
      manifestBaseUrl: BUNDLED_BASE,
      match: {
        confidence: "none",
        reason: "no-match",
        ambiguous: false,
        match: null,
        candidates: [],
      },
      bundleStatus: "not-exact",
      bundle: null,
      bundleArtifact: null,
    };
    const unusedFetch = vi.fn(() =>
      Promise.resolve(new Response(fingerprintText, { status: 200 })),
    );

    const partial =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        lookup,
        DURATION_MS,
        { fetchImplementation: unusedFetch },
      );
    expect(partial).toMatchObject({
      status: "partial",
      videos: [
        { videoId: VIDEO_ID },
        { videoId: missingVideoId },
      ],
      fingerprints: [],
    });
    expect(unusedFetch).not.toHaveBeenCalled();
    await expect(
      resolveChannelPreanalysisLookupByVisualFingerprintCohort(
        lookup,
        partial,
        { durationMs: DURATION_MS, samples: [] },
      ),
    ).resolves.toMatchObject({
      status: "none",
      lookup: {
        match: {
          confidence: "none",
          match: null,
        },
      },
    });

    const completeLookup: ChannelPreanalysisLookupResult = {
      ...lookup,
      manifest: {
        ...partialManifest,
        videos: [fingerprintedVideo],
      },
    };
    const unavailable =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        completeLookup,
        DURATION_MS,
        {
          fetchImplementation: () =>
            Promise.resolve(new Response("", { status: 503 })),
        },
      );
    expect(unavailable).toMatchObject({
      status: "partial",
      videos: [{ videoId: VIDEO_ID }],
      fingerprints: [],
    });
    const unverifiable =
      await fetchChannelPreanalysisVisualFingerprintCohortForLookup(
        completeLookup,
        DURATION_MS,
        {
          fetchImplementation: () =>
            Promise.resolve(
              new Response(`${fingerprintText} `, { status: 200 }),
            ),
        },
      );
    expect(unverifiable).toMatchObject({
      status: "partial",
      videos: [{ videoId: VIDEO_ID }],
      fingerprints: [],
    });
  });

  it("never returns a fetched bundle whose transcript digest was altered", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const parsed = JSON.parse(preparedBundle) as {
      captionTrack: { events: { text: string }[] };
    };
    parsed.captionTrack.events[0]!.text = "변조된 대사";
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : JSON.stringify(parsed),
          { status: 200 },
        ),
      );
    });
    await expect(
      fetchChannelPreanalysisBundle(VIDEO_ID, {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      }),
    ).rejects.toMatchObject({ code: "INVALID_BUNDLE" });
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("preserves an exact manifest identity when its bundle is unavailable", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        url.endsWith("catalog.json")
          ? new Response(JSON.stringify(preparedManifest), { status: 200 })
          : new Response("", { status: 503 }),
      );
    });
    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.match).toMatchObject({
      confidence: "exact",
      match: { videoId: VIDEO_ID },
    });
    expect(result.bundleStatus).toBe("unavailable");
    expect(result.bundle).toBeNull();
  });

  it("verifies the full raw artifact before accepting unchanged transcript data", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const parsed = JSON.parse(preparedBundle) as {
      chapters: { summaryKo: string }[];
    };
    parsed.chapters[0]!.summaryKo = "다른 이야기";
    const mutatedBundle = JSON.stringify(parsed);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(preparedManifest)
            : mutatedBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.bundleStatus).toBe("unavailable");
    expect(result.bundle).toBeNull();
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("falls back only as one manifest-and-bundle source pair", async () => {
    const validBundle = await bundleJson();
    const wrongBundle = await bundleJson({
      videoId: "AbCdEfGhI12",
      title: "다른 영상",
    });
    const rawManifest = manifest(wrongBundle);
    const bundledManifest = manifest(validBundle);
    const fetchImplementation = vi.fn((input: RequestInfo | URL) => {
      const url =
        typeof input === "string"
          ? input
          : input instanceof URL
            ? input.toString()
            : input.url;
      const isRaw = url.startsWith(RAW_BASE);
      return Promise.resolve(
        new Response(
          url.endsWith("catalog.json")
            ? JSON.stringify(isRaw ? rawManifest : bundledManifest)
            : isRaw
              ? wrongBundle
              : validBundle,
          { status: 200 },
        ),
      );
    });

    const result = await requestChannelPreanalysisMatch(
      { videoId: VIDEO_ID },
      {
        fetchImplementation,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
      },
    );
    expect(result.bundleStatus).toBe("loaded");
    expect(result.manifestSource).toBe("bundled");
    expect(result.bundle?.videoId).toBe(VIDEO_ID);
    expect(fetchImplementation).toHaveBeenCalledTimes(4);
  });

  it("hard-clamps caller-provided response limits before bundle fetch", async () => {
    const preparedBundle = await bundleJson();
    const preparedManifest = manifest(preparedBundle);
    const fetchImplementation = vi.fn();
    await expect(
      fetchChannelPreanalysisBundle(
        VIDEO_ID,
        {
          fetchImplementation,
          bundleMaxBytes: CHANNEL_PREANALYSIS_BUNDLE_MAX_BYTES + 1,
        },
        {
          source: "raw",
          baseUrl: RAW_BASE,
          manifest: preparedManifest,
        },
      ),
    ).rejects.toMatchObject({ code: "TOO_LARGE" });
    expect(fetchImplementation).not.toHaveBeenCalled();

    const manifestFetch = vi.fn();
    await expect(
      fetchChannelPreanalysisManifest({
        fetchImplementation: manifestFetch,
        rawBaseUrl: RAW_BASE,
        bundledBaseUrl: BUNDLED_BASE,
        manifestMaxBytes: CHANNEL_PREANALYSIS_MANIFEST_MAX_BYTES + 1,
      }),
    ).rejects.toMatchObject({ code: "FETCH_FAILED" });
    expect(manifestFetch).not.toHaveBeenCalled();
  });

  it("rejects non-canonical storage keys and global fingerprint reuse", async () => {
    const preparedBundle = await bundleJson();
    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify(
          manifest(preparedBundle, {
            artifactOverrides: {
              storageKey:
                "amoretto-vods/videos/%2e%2e/KzAW3yow80Q.json",
            },
          }),
        ),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));

    const fingerprint =
      `local-file-sampled-sha256-v1:${"a".repeat(64)}` as const;
    const duplicateVideo = {
      channelId: AMORETTO_YOUTUBE_CHANNEL_ID,
      videoId: "AbCdEfGhI12",
      title: "다른 영상",
      normalizedTitle: normalizeChannelVideoTitle("다른 영상"),
      durationMs: DURATION_MS,
      publishedAt: "2026-07-18T04:00:00.000Z",
      updatedAt: "2026-07-30T00:00:00.000Z",
      watchUrl: "https://www.youtube.com/watch?v=AbCdEfGhI12",
      state: "discovered" as const,
      revision: 1,
      artifactIds: [],
      registeredLocalSampledFingerprints: [
        {
          value: fingerprint,
          registeredAt: "2026-07-30T00:00:00.000Z",
        },
      ],
      retry: null,
    };
    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify(
          manifest(preparedBundle, {
            videoOverrides: {
              registeredLocalSampledFingerprints: [
                {
                  value: fingerprint,
                  registeredAt: "2026-07-30T00:00:00.000Z",
                },
              ],
            },
            additionalVideos: [duplicateVideo],
          }),
        ),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
  });

  it("strictly rejects retryable records without their retry checkpoint", async () => {
    const invalid = manifest(await bundleJson());
    const videos = invalid.videos.map((video) => ({
      ...video,
      state: "retryable" as const,
      retry: null,
    }));
    expect(() =>
      parseChannelPreanalysisManifest(
        JSON.stringify({ ...invalid, videos }),
      ),
    ).toThrowError(expect.objectContaining({ code: "INVALID_MANIFEST" }));
  });
});
