import { afterEach, describe, expect, it, vi } from "vitest";

import {
  YouTubeCaptionSandboxError,
  parseYouTubeCaptionSandboxResult,
  requestYouTubeCaptionTrackInSandbox,
} from "./youtubeCaptionSandbox";

const expected = {
  nonce: "0123456789abcdef0123456789abcdef",
  requestId: "fedcba9876543210fedcba9876543210",
  videoId: "KzAW3yow80Q",
} as const;

function success(overrides: Record<string, unknown> = {}) {
  return {
    kind: "exclipper-youtube-caption-result",
    nonce: expected.nonce,
    requestId: expected.requestId,
    ok: true,
    videoId: expected.videoId,
    languageCode: "ko",
    isAutoGenerated: true,
    captionJson: JSON.stringify({
      events: [{
        tStartMs: 1_000,
        dDurationMs: 2_000,
        segs: [{ utf8: "칼국수 이야기" }],
      }],
    }),
    ...overrides,
  };
}

function installSandboxDomHarness() {
  type MessageListener = (event: MessageEvent<unknown>) => void;
  const listeners = new Set<MessageListener>();
  const contentWindow = {
    postMessage: vi.fn(),
  };
  const frame = {
    hidden: false,
    referrerPolicy: "",
    src: "",
    sandbox: { add: vi.fn() },
    contentWindow,
    setAttribute: vi.fn(),
    remove: vi.fn(),
  };
  const body = { append: vi.fn() };
  vi.stubGlobal("window", {
    addEventListener: (
      type: string,
      listener: EventListenerOrEventListenerObject,
    ) => {
      if (type === "message" && typeof listener === "function") {
        listeners.add(listener);
      }
    },
    removeEventListener: (
      type: string,
      listener: EventListenerOrEventListenerObject,
    ) => {
      if (type === "message" && typeof listener === "function") {
        listeners.delete(listener);
      }
    },
  });
  vi.stubGlobal("document", {
    body,
    createElement: vi.fn(() => frame),
  });
  return {
    body,
    contentWindow,
    frame,
    listeners,
    emit(
      data: unknown,
      options: {
        readonly source?: object;
        readonly origin?: string;
      } = {},
    ) {
      const event = {
        data,
        source: options.source ?? contentWindow,
        origin: options.origin ?? "null",
      } as unknown as MessageEvent<unknown>;
      for (const listener of [...listeners]) listener(event);
    },
  };
}

afterEach(() => {
  vi.useRealTimers();
  vi.unstubAllGlobals();
});

describe("parseYouTubeCaptionSandboxResult", () => {
  it("accepts a source-fenced Korean JSON3 track", () => {
    expect(parseYouTubeCaptionSandboxResult(success(), expected)).toMatchObject({
      videoId: expected.videoId,
      languageCode: "ko",
      isAutoGenerated: true,
      events: [{ startMs: 1_000, durationMs: 2_000, text: "칼국수 이야기" }],
    });
  });

  it("rejects a result for a different source", () => {
    expect(() =>
      parseYouTubeCaptionSandboxResult(
        success({ videoId: "EZfCGS5ms_Q" }),
        expected,
      ),
    ).toThrow(YouTubeCaptionSandboxError);
  });

  it("reports a no-caption observation without weakening its schema", () => {
    try {
      parseYouTubeCaptionSandboxResult({
        kind: "exclipper-youtube-caption-result",
        nonce: expected.nonce,
        requestId: expected.requestId,
        ok: false,
        errorCode: "CAPTIONS_NOT_FOUND",
      }, expected);
      throw new Error("Expected a sandbox failure.");
    } catch (error) {
      expect(error).toBeInstanceOf(YouTubeCaptionSandboxError);
      expect((error as YouTubeCaptionSandboxError).code).toBe(
        "CAPTIONS_NOT_FOUND",
      );
    }
  });

  it("rejects empty or malformed caption payloads", () => {
    expect(() =>
      parseYouTubeCaptionSandboxResult(
        success({ captionJson: JSON.stringify({ events: [] }) }),
        expected,
      ),
    ).toThrow(YouTubeCaptionSandboxError);
    expect(() =>
      parseYouTubeCaptionSandboxResult(
        success({ captionJson: "not-json" }),
        expected,
      ),
    ).toThrow(YouTubeCaptionSandboxError);
  });
});

describe("requestYouTubeCaptionTrackInSandbox", () => {
  it("source-fences messages, posts once, and removes the frame after success", async () => {
    const harness = installSandboxDomHarness();
    const pending = requestYouTubeCaptionTrackInSandbox(expected.videoId);
    expect(harness.body.append).toHaveBeenCalledWith(harness.frame);
    expect(harness.frame.src).toContain(
      "/youtube-caption-sandbox.html#",
    );
    const nonce = harness.frame.src.split("#")[1]!;
    const ready = {
      kind: "exclipper-youtube-caption-ready",
      nonce,
    };

    harness.emit(ready, { source: {} });
    harness.emit(ready, { origin: "https://11qaws.github.io" });
    expect(harness.contentWindow.postMessage).not.toHaveBeenCalled();

    harness.emit(ready);
    harness.emit(ready);
    expect(harness.contentWindow.postMessage).toHaveBeenCalledTimes(1);
    const request = harness.contentWindow.postMessage.mock.calls[0]![0] as {
      readonly requestId: string;
    };
    harness.emit(success({
      nonce,
      requestId: request.requestId,
    }));

    await expect(pending).resolves.toMatchObject({
      videoId: expected.videoId,
      events: [{ text: "칼국수 이야기" }],
    });
    expect(harness.frame.remove).toHaveBeenCalledTimes(1);
    expect(harness.listeners.size).toBe(0);
  });

  it("removes the frame when the parent aborts", async () => {
    const harness = installSandboxDomHarness();
    const controller = new AbortController();
    const pending = requestYouTubeCaptionTrackInSandbox(expected.videoId, {
      signal: controller.signal,
    });

    controller.abort(new Error("cancelled"));

    await expect(pending).rejects.toThrow("cancelled");
    expect(harness.frame.remove).toHaveBeenCalledTimes(1);
    expect(harness.listeners.size).toBe(0);
  });

  it("removes the frame after a bounded timeout", async () => {
    vi.useFakeTimers();
    const harness = installSandboxDomHarness();
    const pending = requestYouTubeCaptionTrackInSandbox(expected.videoId, {
      timeoutMs: 25,
    });
    const rejection = pending.catch((error: unknown) => error);

    await vi.advanceTimersByTimeAsync(25);

    await expect(rejection).resolves.toMatchObject({
      code: "TIMEOUT",
    });
    expect(harness.frame.remove).toHaveBeenCalledTimes(1);
    expect(harness.listeners.size).toBe(0);
  });
});
