import {
  MAX_YOUTUBE_CAPTION_EVENTS,
  YOUTUBE_VIDEO_ID_PATTERN,
  parseYouTubeCaptionJson3,
  type YouTubeCaptionTrackReference,
  type YouTubeCaptionTrackResult,
} from "./youtubeCaptionTrack";

const YOUTUBE_CAPTION_SANDBOX_PATH =
  `${import.meta.env.BASE_URL}youtube-caption-sandbox.html` as const;
const YOUTUBE_CAPTION_SANDBOX_TIMEOUT_MS = 25_000;
const MAX_YOUTUBE_CAPTION_RESPONSE_BYTES = 8 * 1024 * 1024;
const SANDBOX_NONCE_PATTERN = /^[a-f0-9]{32}$/u;
const SANDBOX_REQUEST_ID_PATTERN = /^[a-f0-9]{32}$/u;

type YouTubeCaptionSandboxFailureCode =
  | "CAPTIONS_NOT_FOUND"
  | "PLAYER_UNAVAILABLE"
  | "CAPTION_UNAVAILABLE"
  | "INVALID_RESPONSE"
  | "TIMEOUT";

interface YouTubeCaptionSandboxRequest {
  readonly kind: "exclipper-youtube-caption-request";
  readonly nonce: string;
  readonly requestId: string;
  readonly videoId: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function exactKeys(
  value: Record<string, unknown>,
  keys: readonly string[],
): boolean {
  const actual = Object.keys(value).sort();
  const expected = [...keys].sort();
  return (
    actual.length === expected.length &&
    actual.every((key, index) => key === expected[index])
  );
}

function randomHex128(cryptoImplementation: Crypto): string {
  const bytes = new Uint8Array(16);
  cryptoImplementation.getRandomValues(bytes);
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join(
    "",
  );
}

function isFailureCode(
  value: unknown,
): value is YouTubeCaptionSandboxFailureCode {
  return (
    value === "CAPTIONS_NOT_FOUND" ||
    value === "PLAYER_UNAVAILABLE" ||
    value === "CAPTION_UNAVAILABLE" ||
    value === "INVALID_RESPONSE" ||
    value === "TIMEOUT"
  );
}

export class YouTubeCaptionSandboxError extends Error {
  readonly code: YouTubeCaptionSandboxFailureCode | "UNSUPPORTED";

  constructor(
    code: YouTubeCaptionSandboxFailureCode | "UNSUPPORTED",
    message: string,
  ) {
    super(message);
    this.name = "YouTubeCaptionSandboxError";
    this.code = code;
  }
}

export function parseYouTubeCaptionSandboxResult(
  value: unknown,
  expected: {
    readonly nonce: string;
    readonly requestId: string;
    readonly videoId: string;
  },
): YouTubeCaptionTrackResult {
  if (
    !SANDBOX_NONCE_PATTERN.test(expected.nonce) ||
    !SANDBOX_REQUEST_ID_PATTERN.test(expected.requestId) ||
    !YOUTUBE_VIDEO_ID_PATTERN.test(expected.videoId) ||
    !isRecord(value) ||
    value.kind !== "exclipper-youtube-caption-result" ||
    value.nonce !== expected.nonce ||
    value.requestId !== expected.requestId ||
    typeof value.ok !== "boolean"
  ) {
    throw new YouTubeCaptionSandboxError(
      "INVALID_RESPONSE",
      "YouTube caption sandbox returned an invalid response.",
    );
  }
  if (!value.ok) {
    if (
      !exactKeys(value, [
        "kind",
        "nonce",
        "requestId",
        "ok",
        "errorCode",
      ]) ||
      !isFailureCode(value.errorCode)
    ) {
      throw new YouTubeCaptionSandboxError(
        "INVALID_RESPONSE",
        "YouTube caption sandbox returned an invalid failure.",
      );
    }
    throw new YouTubeCaptionSandboxError(
      value.errorCode,
      value.errorCode === "CAPTIONS_NOT_FOUND"
        ? "Korean YouTube captions are unavailable."
        : "YouTube caption sandbox is temporarily unavailable.",
    );
  }
  if (
    !exactKeys(value, [
      "kind",
      "nonce",
      "requestId",
      "ok",
      "videoId",
      "languageCode",
      "isAutoGenerated",
      "captionJson",
    ]) ||
    value.videoId !== expected.videoId ||
    typeof value.languageCode !== "string" ||
    !(value.languageCode === "ko" || value.languageCode.startsWith("ko-")) ||
    typeof value.isAutoGenerated !== "boolean" ||
    typeof value.captionJson !== "string" ||
    new TextEncoder().encode(value.captionJson).byteLength >
      MAX_YOUTUBE_CAPTION_RESPONSE_BYTES
  ) {
    throw new YouTubeCaptionSandboxError(
      "INVALID_RESPONSE",
      "YouTube caption sandbox returned invalid caption data.",
    );
  }
  let payload: unknown;
  try {
    payload = JSON.parse(value.captionJson) as unknown;
  } catch {
    throw new YouTubeCaptionSandboxError(
      "INVALID_RESPONSE",
      "YouTube caption sandbox returned invalid JSON.",
    );
  }
  const track: YouTubeCaptionTrackReference = {
    videoId: expected.videoId,
    languageCode: value.languageCode,
    isAutoGenerated: value.isAutoGenerated,
    baseUrl: "https://www.youtube.com/api/timedtext",
  };
  const result = parseYouTubeCaptionJson3(payload, track);
  if (
    result === null ||
    result.events.length === 0 ||
    result.events.length > MAX_YOUTUBE_CAPTION_EVENTS
  ) {
    throw new YouTubeCaptionSandboxError(
      "INVALID_RESPONSE",
      "YouTube caption sandbox returned unusable captions.",
    );
  }
  return result;
}

export function canRequestYouTubeCaptionsInSandbox(): boolean {
  return (
    typeof window !== "undefined" &&
    typeof document !== "undefined" &&
    document.body !== null &&
    typeof globalThis.crypto?.getRandomValues === "function"
  );
}

export function requestYouTubeCaptionTrackInSandbox(
  videoId: string,
  options: {
    readonly signal?: AbortSignal;
    readonly timeoutMs?: number;
  } = {},
): Promise<YouTubeCaptionTrackResult> {
  if (!YOUTUBE_VIDEO_ID_PATTERN.test(videoId)) {
    return Promise.reject(new RangeError("Invalid YouTube video ID."));
  }
  if (!canRequestYouTubeCaptionsInSandbox()) {
    return Promise.reject(
      new YouTubeCaptionSandboxError(
        "UNSUPPORTED",
        "YouTube caption sandbox is unavailable.",
      ),
    );
  }

  const nonce = randomHex128(globalThis.crypto);
  const requestId = randomHex128(globalThis.crypto);
  const frame = document.createElement("iframe");
  frame.hidden = true;
  frame.setAttribute("aria-hidden", "true");
  frame.setAttribute("tabindex", "-1");
  frame.sandbox.add("allow-scripts");
  frame.referrerPolicy = "no-referrer";
  frame.src = `${YOUTUBE_CAPTION_SANDBOX_PATH}#${nonce}`;

  return new Promise((resolve, reject) => {
    let settled = false;
    let requestPosted = false;
    const timeout = globalThis.setTimeout(
      () =>
        settle(
          reject,
          new YouTubeCaptionSandboxError(
            "TIMEOUT",
            "YouTube caption sandbox timed out.",
          ),
        ),
      options.timeoutMs ?? YOUTUBE_CAPTION_SANDBOX_TIMEOUT_MS,
    );

    function cleanup(): void {
      globalThis.clearTimeout(timeout);
      window.removeEventListener("message", onMessage);
      options.signal?.removeEventListener("abort", onAbort);
      frame.remove();
    }

    function settle<T>(
      callback: (value: T) => void,
      value: T,
    ): void {
      if (settled) return;
      settled = true;
      cleanup();
      callback(value);
    }

    function onAbort(): void {
      settle(
        reject,
        options.signal?.reason instanceof Error
          ? options.signal.reason
          : new DOMException("The operation was aborted.", "AbortError"),
      );
    }

    function onMessage(event: MessageEvent<unknown>): void {
      if (
        event.source !== frame.contentWindow ||
        event.origin !== "null" ||
        !isRecord(event.data) ||
        event.data.nonce !== nonce
      ) {
        return;
      }
      if (event.data.kind === "exclipper-youtube-caption-ready") {
        if (requestPosted) return;
        requestPosted = true;
        const request: YouTubeCaptionSandboxRequest = {
          kind: "exclipper-youtube-caption-request",
          nonce,
          requestId,
          videoId,
        };
        frame.contentWindow?.postMessage(request, "*");
        return;
      }
      try {
        settle(
          resolve,
          parseYouTubeCaptionSandboxResult(event.data, {
            nonce,
            requestId,
            videoId,
          }),
        );
      } catch (error) {
        settle(
          reject,
          error instanceof Error
            ? error
            : new YouTubeCaptionSandboxError(
                "INVALID_RESPONSE",
                "YouTube caption sandbox failed.",
              ),
        );
      }
    }

    window.addEventListener("message", onMessage);
    options.signal?.addEventListener("abort", onAbort, { once: true });
    if (options.signal?.aborted === true) {
      onAbort();
      return;
    }
    document.body.append(frame);
  });
}
