import { describe, expect, it, vi } from "vitest";

import { requestYouTubeCaptionTrack } from "./youtubeCaptionClient";

const VIDEO_ID = "KzAW3yow80Q";

function captionPayload(): string {
  return JSON.stringify({
    videoId: VIDEO_ID,
    languageCode: "ko",
    isAutoGenerated: true,
    events: [{ startMs: 1_000, durationMs: 2_000, text: "칼국수 이야기" }],
  });
}

function okResponse(): Response {
  return new Response(captionPayload(), { status: 200 });
}

describe("requestYouTubeCaptionTrack retries", () => {
  /**
   * A single transient 502 used to drop the whole analysis onto bounded audio
   * transcription — many minutes and real spend for a broadcast whose captions
   * were available the whole time.
   */
  it("recovers from a transient 502", async () => {
    const fetchImplementation = vi
      .fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
      .mockResolvedValueOnce(new Response("bad gateway", { status: 502 }))
      .mockResolvedValueOnce(okResponse());

    const track = await requestYouTubeCaptionTrack(VIDEO_ID, {
      fetchImplementation,
      retryDelaysMs: [0, 0],
    });

    expect(fetchImplementation).toHaveBeenCalledTimes(2);
    expect(track.videoId).toBe(VIDEO_ID);
    expect(track.events).toHaveLength(1);
  });

  it("recovers from a transport failure", async () => {
    const fetchImplementation = vi
      .fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
      .mockRejectedValueOnce(new TypeError("network down"))
      .mockResolvedValueOnce(okResponse());

    const track = await requestYouTubeCaptionTrack(VIDEO_ID, {
      fetchImplementation,
      retryDelaysMs: [0],
    });

    expect(fetchImplementation).toHaveBeenCalledTimes(2);
    expect(track.videoId).toBe(VIDEO_ID);
  });

  it.each([429, 500, 503])("retries status %i", async (status) => {
    const fetchImplementation = vi
      .fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
      .mockResolvedValueOnce(new Response("", { status }))
      .mockResolvedValueOnce(okResponse());

    await expect(
      requestYouTubeCaptionTrack(VIDEO_ID, {
        fetchImplementation,
        retryDelaysMs: [0],
      }),
    ).resolves.toMatchObject({ videoId: VIDEO_ID });
    expect(fetchImplementation).toHaveBeenCalledTimes(2);
  });

  it.each([400, 403, 404])(
    "does not retry status %i, which will not clear on its own",
    async (status) => {
      const fetchImplementation = vi
        .fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
        .mockResolvedValue(new Response("", { status }));

      await expect(
        requestYouTubeCaptionTrack(VIDEO_ID, {
          fetchImplementation,
          retryDelaysMs: [0, 0],
        }),
      ).rejects.toThrow();
      expect(fetchImplementation).toHaveBeenCalledTimes(1);
    },
  );

  it("gives up after the configured attempts", async () => {
    const fetchImplementation = vi
      .fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
      .mockResolvedValue(new Response("", { status: 502 }));

    await expect(
      requestYouTubeCaptionTrack(VIDEO_ID, {
        fetchImplementation,
        retryDelaysMs: [0, 0],
      }),
    ).rejects.toThrow();
    expect(fetchImplementation).toHaveBeenCalledTimes(3);
  });

  it("does not retry once the caller aborted", async () => {
    const controller = new AbortController();
    const fetchImplementation = vi
      .fn<(input: RequestInfo | URL, init?: RequestInit) => Promise<Response>>()
      .mockImplementation(() => {
        controller.abort(new Error("cancelled"));
        return Promise.reject(new Error("cancelled"));
      });

    await expect(
      requestYouTubeCaptionTrack(VIDEO_ID, {
        fetchImplementation,
        signal: controller.signal,
        retryDelaysMs: [0, 0],
      }),
    ).rejects.toThrow();
    expect(fetchImplementation).toHaveBeenCalledTimes(1);
  });
});
