import { describe, expect, it } from "vitest";
import {
  createYouTubeCaptionChapters,
  createYouTubeCaptionRefinementTranscripts,
  createYouTubeCaptionTranscriptCellOutcomes,
  extractKoreanYouTubeCaptionTrack,
  extractKoreanYouTubeCaptionTrackFromPlayerResponse,
  parseYouTubeCaptionJson3,
  youtubeVideoIdFromSourceName,
  youtubeVideoIdFromUserInput,
} from "./youtubeCaptionTrack";
import { createCaptionDiscoveredLeadRefinementPlan } from "./discoveredLeadRefinement";

describe("youtubeCaptionTrack", () => {
  it("extracts the Korean caption URL from a bounded player response", () => {
    const player = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            { languageCode: "en", baseUrl: "https://www.youtube.com/api/timedtext?lang=en" },
            { languageCode: "ko", kind: "asr", baseUrl: "https://www.youtube.com/api/timedtext?lang=ko" },
          ],
        },
      },
    };
    const track = extractKoreanYouTubeCaptionTrack(
      `<script>var ytInitialPlayerResponse = ${JSON.stringify(player)};</script>`,
      "KzAW3yow80Q",
    );
    expect(track).toMatchObject({
      videoId: "KzAW3yow80Q",
      languageCode: "ko",
      isAutoGenerated: true,
    });
    expect(new URL(track!.baseUrl).searchParams.get("fmt")).toBe("json3");
    expect(
      extractKoreanYouTubeCaptionTrackFromPlayerResponse(player, "KzAW3yow80Q"),
    ).toEqual(track);
  });

  it("normalizes timestamped JSON3 events without inventing text", () => {
    const track = {
      videoId: "KzAW3yow80Q",
      languageCode: "ko",
      isAutoGenerated: true,
      baseUrl: "https://www.youtube.com/api/timedtext?fmt=json3",
    };
    expect(parseYouTubeCaptionJson3({
      events: [
        { tStartMs: 1_000, dDurationMs: 2_000, segs: [{ utf8: "제가 " }, { utf8: "틀렸어요" }] },
      ],
    }, track)).toEqual({
      videoId: "KzAW3yow80Q",
      languageCode: "ko",
      isAutoGenerated: true,
      events: [{ startMs: 1_000, durationMs: 2_000, text: "제가 틀렸어요" }],
    });
  });

  it("detects a bracketed video id and builds a bounded complete transcript map", () => {
    expect(
      youtubeVideoIdFromSourceName("2026 07 17 - 음식 토크[KzAW3yow80Q].mp4"),
    ).toBe("KzAW3yow80Q");
    expect(youtubeVideoIdFromSourceName("내 영상.mp4")).toBeNull();
    const chapters = createYouTubeCaptionChapters(
      {
        videoId: "KzAW3yow80Q",
        languageCode: "ko",
        isAutoGenerated: true,
        events: [
          { startMs: 1_000, durationMs: 2_000, text: "방송을 시작합니다." },
          { startMs: 121_000, durationMs: 2_000, text: "제가 잘못했습니다." },
        ],
      },
      240_000,
    );
    expect(chapters).toHaveLength(2);
    expect(chapters[0]?.summaryKo).toContain("방송을 시작");
    expect(chapters[1]?.summaryKo).toContain("잘못했습니다");
    expect(chapters.every((chapter) => chapter.evidenceMode === "complete-transcript")).toBe(true);
  });

  it("covers only exact planned cells that contain caption text", () => {
    const outcomes = createYouTubeCaptionTranscriptCellOutcomes(
      {
        videoId: "KzAW3yow80Q",
        languageCode: "ko",
        isAutoGenerated: true,
        events: [
          { startMs: 5_000, durationMs: 1_000, text: "첫 구간의 실제 자막" },
          { startMs: 65_000, durationMs: 1_000, text: "셋째 구간의 실제 자막" },
        ],
      },
      [
        { chunkId: "asr-0-n5c", sourceStartMs: 0, sourceEndMs: 30_000 },
        {
          chunkId: "asr-n5c-1ek0",
          sourceStartMs: 30_000,
          sourceEndMs: 60_000,
        },
        {
          chunkId: "asr-1ek0-1z4o",
          sourceStartMs: 60_000,
          sourceEndMs: 90_000,
        },
      ],
      90_000,
    );

    expect(outcomes.map(({ chunkId }) => chunkId)).toEqual([
      "asr-0-n5c",
      "asr-1ek0-1z4o",
    ]);
    expect(outcomes.map(({ chapter }) => ({
      startMs: chapter.startMs,
      endMs: chapter.endMs,
      summaryKo: chapter.summaryKo,
    }))).toEqual([
      {
        startMs: 0,
        endMs: 30_000,
        summaryKo: "첫 구간의 실제 자막",
      },
      {
        startMs: 60_000,
        endMs: 90_000,
        summaryKo: "셋째 구간의 실제 자막",
      },
    ]);
  });

  it("turns a broad semantic lead into exact thirty-second caption cells", () => {
    const lead = {
      leadId: "food-quiz",
      startChapterId: "youtube-010",
      endChapterId: "youtube-012",
      startMs: 1_170_000,
      endMs: 1_410_000,
      category: "reaction" as const,
      confidence: 0.9,
      eventSummaryKo: "음식 이름을 두고 항변한다.",
      whyThisMomentKo: "반응이 완결된다.",
      evidenceCueKo: "칼국수는 맞잖아요",
      uncertaintiesKo: [],
    };
    const plan = createCaptionDiscoveredLeadRefinementPlan([lead]);
    const transcripts = createYouTubeCaptionRefinementTranscripts(
      {
        videoId: "KzAW3yow80Q",
        languageCode: "ko",
        isAutoGenerated: true,
        events: [
          { startMs: 1_178_880, durationMs: 2_000, text: "저 어 그 칼국수" },
          { startMs: 1_398_240, durationMs: 2_000, text: "껍데기잖아요 [비명]" },
        ],
      },
      plan,
    );
    expect(plan.estimatedAsrCostUsd).toBe(0);
    const firstSegment = plan.segments[0];
    expect(firstSegment).toBeDefined();
    expect(
      (firstSegment?.sourceEndMs ?? 0) - (firstSegment?.sourceStartMs ?? 0),
    ).toBe(30_000);
    expect(transcripts).toEqual([
      expect.objectContaining({ textKo: "저 어 그 칼국수" }),
      expect.objectContaining({ textKo: "껍데기잖아요 [비명]" }),
    ]);
  });
});

describe("youtubeVideoIdFromUserInput", () => {
  // 사람은 주소창을 복사한다. ID 11자를 손으로 뽑아내게 하면 그 순간 이 기능을
  // 안 쓰게 된다.
  it.each([
    ["https://www.youtube.com/watch?v=KzAW3yow80Q", "KzAW3yow80Q"],
    ["https://youtu.be/KzAW3yow80Q", "KzAW3yow80Q"],
    ["https://www.youtube.com/watch?v=KzAW3yow80Q&t=120s", "KzAW3yow80Q"],
    ["https://www.youtube.com/watch?v=KzAW3yow80Q&list=PLabc", "KzAW3yow80Q"],
    ["https://www.youtube.com/embed/KzAW3yow80Q", "KzAW3yow80Q"],
    ["https://www.youtube.com/live/KzAW3yow80Q", "KzAW3yow80Q"],
    ["https://youtu.be/KzAW3yow80Q?si=xyz", "KzAW3yow80Q"],
    ["KzAW3yow80Q", "KzAW3yow80Q"],
    ["  KzAW3yow80Q  ", "KzAW3yow80Q"],
    // 호스트는 보지 않는다. 꺼낸 값은 유튜브 영상 ID 로만 쓰이므로, 어느 주소에서
    // 나왔든 자막 조회가 성공하거나 404 로 끝난다. 호스트를 검사하면 유튜브가
    // 주소 형태를 바꿀 때마다 조용히 못 읽게 된다.
    ["https://example.com/watch?v=KzAW3yow80Q", "KzAW3yow80Q"],
  ])("reads %s", (input, expected) => {
    expect(youtubeVideoIdFromUserInput(input)).toBe(expected);
  });

  it.each([[""], ["   "], ["https://www.youtube.com/"], ["tooshort"]])(
    "refuses %s",
    (input) => {
      expect(youtubeVideoIdFromUserInput(input)).toBeNull();
    },
  );
});
